-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.achievement_claims

-- @owner
-- owner: postgres

-- @columns
create table public.achievement_claims (
  player_id text not null,
  key text not null,
  packs integer default 0 not null,
  title text,
  frame text,
  claimed_at timestamp with time zone default now() not null,
  shards integer default 0 not null
);

-- @constraints
alter table public.achievement_claims add constraint achievement_claims_amount_check CHECK (((packs >= 0) AND (shards >= 0)));
alter table public.achievement_claims add constraint achievement_claims_pkey PRIMARY KEY (player_id, key);
alter table public.achievement_claims add constraint achievement_claims_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

-- @indexes
CREATE UNIQUE INDEX achievement_claims_pkey ON public.achievement_claims USING btree (player_id, key);

-- @rls
alter table public.achievement_claims enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.achievement_claims to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.achievement_claims to service_role;
