-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.achievement_switch_map

-- @owner
-- owner: postgres

-- @columns
create table public.achievement_switch_map (
  old_key text not null,
  track text not null,
  proves integer not null,
  adds boolean default false not null
);

-- @constraints
alter table public.achievement_switch_map add constraint achievement_switch_map_pkey PRIMARY KEY (old_key);
alter table public.achievement_switch_map add constraint achievement_switch_map_proves_check CHECK ((proves >= 0));
alter table public.achievement_switch_map add constraint achievement_switch_map_track_fkey FOREIGN KEY (track) REFERENCES achievement_tracks(key);

-- @indexes
CREATE UNIQUE INDEX achievement_switch_map_pkey ON public.achievement_switch_map USING btree (old_key);

-- @rls
alter table public.achievement_switch_map enable row level security;

-- @grants
grant select on table public.achievement_switch_map to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.achievement_switch_map to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.achievement_switch_map to service_role;
