-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.admin_actions

-- @owner
-- owner: postgres

-- @columns
create table public.admin_actions (
  id bigint generated always as identity not null,
  at timestamp with time zone default now() not null,
  actor text not null,
  action text not null,
  target_kind text,
  target_id text,
  before jsonb,
  after jsonb,
  reason text,
  source text not null,
  undo_of bigint
);

-- @constraints
alter table public.admin_actions add constraint admin_actions_action_check CHECK ((length(TRIM(BOTH FROM action)) > 0));
alter table public.admin_actions add constraint admin_actions_actor_check CHECK ((length(TRIM(BOTH FROM actor)) > 0));
alter table public.admin_actions add constraint admin_actions_pkey PRIMARY KEY (id);
alter table public.admin_actions add constraint admin_actions_source_check CHECK ((source = ANY (ARRAY['studio'::text, 'bot'::text, 'sql'::text])));
alter table public.admin_actions add constraint admin_actions_undo_of_fkey FOREIGN KEY (undo_of) REFERENCES admin_actions(id);

-- @indexes
CREATE INDEX admin_actions_at ON public.admin_actions USING btree (at DESC);
CREATE UNIQUE INDEX admin_actions_one_undo ON public.admin_actions USING btree (undo_of) WHERE (undo_of IS NOT NULL);
CREATE UNIQUE INDEX admin_actions_pkey ON public.admin_actions USING btree (id);
CREATE INDEX admin_actions_target ON public.admin_actions USING btree (target_kind, target_id, at DESC);

-- @rls
alter table public.admin_actions enable row level security;

-- @grants
grant select on table public.admin_actions to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.admin_actions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.admin_actions to service_role;
