-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.app_sessions

-- @owner
-- owner: postgres

-- @columns
create table public.app_sessions (
  id bigint generated always as identity not null,
  player_id text not null,
  started_at timestamp with time zone default now() not null,
  last_seen_at timestamp with time zone default now() not null,
  ended_at timestamp with time zone,
  client jsonb default '{}'::jsonb not null
);

-- @constraints
alter table public.app_sessions add constraint app_sessions_pkey PRIMARY KEY (id);
alter table public.app_sessions add constraint app_sessions_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

-- @indexes
CREATE UNIQUE INDEX app_sessions_pkey ON public.app_sessions USING btree (id);
CREATE INDEX app_sessions_player ON public.app_sessions USING btree (player_id, last_seen_at DESC);
CREATE INDEX app_sessions_started ON public.app_sessions USING btree (started_at);

-- @rls
alter table public.app_sessions enable row level security;

-- @grants
grant select on table public.app_sessions to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.app_sessions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.app_sessions to service_role;
