-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.artist_submissions

-- @owner
-- owner: postgres

-- @columns
create table public.artist_submissions (
  id bigint generated always as identity not null,
  submitted_by text not null,
  subject_name text not null,
  proposed_rarity card_rarity default 'normal'::card_rarity not null,
  image_url text,
  artist_credit text not null,
  lore text,
  status submission_status default 'pending'::submission_status not null,
  reviewed_by text,
  created_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.artist_submissions add constraint artist_submissions_pkey PRIMARY KEY (id);

-- @indexes
CREATE UNIQUE INDEX artist_submissions_pkey ON public.artist_submissions USING btree (id);

-- @rls
alter table public.artist_submissions enable row level security;

-- @grants
grant select on table public.artist_submissions to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.artist_submissions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.artist_submissions to service_role;
