-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.auctions

-- @owner
-- owner: postgres

-- @columns
create table public.auctions (
  id bigint default nextval('auctions_id_seq'::regclass) not null,
  seller_id text not null,
  card_id bigint not null,
  min_rarity text,
  min_count integer default 0 not null,
  min_cards bigint[] default '{}'::bigint[] not null,
  min_mode text default 'and'::text not null,
  status text default 'live'::text not null,
  accepted_bid_id bigint,
  created_at timestamp with time zone default now() not null,
  ends_at timestamp with time zone not null,
  settled_at timestamp with time zone,
  notice_message_id text,
  notice_dirty boolean default true not null,
  notice_at timestamp with time zone,
  accepted_at timestamp with time zone
);

-- @constraints
alter table public.auctions add constraint auctions_accepted_bid_id_fkey FOREIGN KEY (accepted_bid_id) REFERENCES auction_bids(id);
alter table public.auctions add constraint auctions_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards(id);
alter table public.auctions add constraint auctions_min_count_check CHECK (((min_count >= 0) AND (min_count <= 5)));
alter table public.auctions add constraint auctions_min_mode_check CHECK ((min_mode = ANY (ARRAY['and'::text, 'or'::text])));
alter table public.auctions add constraint auctions_min_rarity_check CHECK ((min_rarity = ANY (ARRAY['normal'::text, 'illustrated_rare'::text, 'secret_rare'::text, 'full_art'::text, 'gold'::text, 'promo'::text, 'event'::text])));
alter table public.auctions add constraint auctions_pkey PRIMARY KEY (id);
alter table public.auctions add constraint auctions_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.auctions add constraint auctions_status_check CHECK ((status = ANY (ARRAY['live'::text, 'accepted'::text, 'sold'::text, 'closed'::text, 'expired'::text])));

-- @indexes
CREATE UNIQUE INDEX auctions_one_live ON public.auctions USING btree (seller_id) WHERE (status = ANY (ARRAY['live'::text, 'accepted'::text]));
CREATE UNIQUE INDEX auctions_pkey ON public.auctions USING btree (id);
CREATE INDEX auctions_status ON public.auctions USING btree (status, ends_at);

-- @rls
alter table public.auctions enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.auctions to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.auctions to service_role;

-- @triggers
CREATE TRIGGER card_trades_auction AFTER INSERT OR UPDATE OF status ON public.auctions FOR EACH ROW WHEN ((new.status = 'sold'::text)) EXECUTE FUNCTION card_trades_from_auction();
