-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.auction_bids

-- @owner
-- owner: postgres

-- @columns
create table public.auction_bids (
  id bigint default nextval('auction_bids_id_seq'::regclass) not null,
  auction_id bigint not null,
  bidder_id text not null,
  cards bigint[] not null,
  status text default 'open'::text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.auction_bids add constraint auction_bids_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE;
alter table public.auction_bids add constraint auction_bids_bidder_id_fkey FOREIGN KEY (bidder_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.auction_bids add constraint auction_bids_cards_check CHECK (((cardinality(cards) >= 1) AND (cardinality(cards) <= 5)));
alter table public.auction_bids add constraint auction_bids_pkey PRIMARY KEY (id);
alter table public.auction_bids add constraint auction_bids_status_check CHECK ((status = ANY (ARRAY['open'::text, 'accepted'::text, 'won'::text, 'declined'::text, 'returned'::text, 'withdrawn'::text])));

-- @indexes
CREATE INDEX auction_bids_bidder ON public.auction_bids USING btree (bidder_id, status);
CREATE UNIQUE INDEX auction_bids_one_open ON public.auction_bids USING btree (auction_id, bidder_id) WHERE (status = ANY (ARRAY['open'::text, 'accepted'::text]));
CREATE UNIQUE INDEX auction_bids_pkey ON public.auction_bids USING btree (id);

-- @rls
alter table public.auction_bids enable row level security;

-- @grants
grant select on table public.auction_bids to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.auction_bids to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.auction_bids to service_role;
