-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.card_trades

-- @owner
-- owner: postgres

-- @columns
create table public.card_trades (
  id bigint generated always as identity not null,
  kind text not null,
  from_id text not null,
  to_id text not null,
  from_cards bigint[] not null,
  to_cards bigint[] not null,
  offer_id bigint,
  auction_id bigint,
  created_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.card_trades add constraint card_trades_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE SET NULL;
alter table public.card_trades add constraint card_trades_auction_id_key UNIQUE (auction_id);
alter table public.card_trades add constraint card_trades_from_id_fkey FOREIGN KEY (from_id) REFERENCES players(id);
alter table public.card_trades add constraint card_trades_kind_check CHECK ((kind = ANY (ARRAY['offer'::text, 'auction'::text])));
alter table public.card_trades add constraint card_trades_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES trade_offers(id) ON DELETE SET NULL;
alter table public.card_trades add constraint card_trades_offer_id_key UNIQUE (offer_id);
alter table public.card_trades add constraint card_trades_pkey PRIMARY KEY (id);
alter table public.card_trades add constraint card_trades_to_id_fkey FOREIGN KEY (to_id) REFERENCES players(id);

-- @indexes
CREATE UNIQUE INDEX card_trades_auction_id_key ON public.card_trades USING btree (auction_id);
CREATE INDEX card_trades_from ON public.card_trades USING btree (from_id, created_at);
CREATE UNIQUE INDEX card_trades_offer_id_key ON public.card_trades USING btree (offer_id);
CREATE UNIQUE INDEX card_trades_pkey ON public.card_trades USING btree (id);
CREATE INDEX card_trades_to ON public.card_trades USING btree (to_id, created_at);

-- @rls
alter table public.card_trades enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_trades to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_trades to service_role;

-- @triggers
CREATE TRIGGER ach_wish_trade AFTER INSERT ON public.card_trades FOR EACH ROW EXECUTE FUNCTION ach_wish_trade();
