-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.cards

-- @owner
-- owner: postgres

-- @columns
create table public.cards (
  id bigint generated always as identity not null,
  subject_id bigint not null,
  name text not null,
  rarity card_rarity not null,
  source card_source default 'draw'::card_source not null,
  image_url text,
  artist_credit text,
  lore text,
  in_draw_pool boolean default true not null,
  created_at timestamp with time zone default now() not null,
  season text,
  event text,
  tradeable boolean default true not null
);

-- @constraints
alter table public.cards add constraint cards_pkey PRIMARY KEY (id);
alter table public.cards add constraint cards_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE;

-- @indexes
CREATE UNIQUE INDEX cards_pkey ON public.cards USING btree (id);
CREATE INDEX cards_pool_rarity_idx ON public.cards USING btree (rarity) WHERE in_draw_pool;

-- @rls
alter table public.cards enable row level security;

-- @policies
create policy "public read cards" on public.cards as permissive for select to public
  using (true);

-- @grants
grant select on table public.cards to anon;
grant select on table public.cards to authenticated;
grant select on table public.cards to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.cards to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.cards to service_role;

-- @triggers
CREATE TRIGGER cards_event_rules BEFORE INSERT OR UPDATE OF rarity, tradeable, in_draw_pool ON public.cards FOR EACH ROW EXECUTE FUNCTION cards_event_rules();
