-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.card_plays

-- @owner
-- owner: postgres

-- @columns
create table public.card_plays (
  id bigint default nextval('card_plays_id_seq'::regclass) not null,
  player_id text not null,
  target_id text not null,
  aimed_at text not null,
  card_id bigint not null,
  subject_id bigint not null,
  primitive text not null,
  kind text not null,
  rarity text not null,
  amount numeric,
  duration_s integer,
  outcome text not null,
  created_at timestamp with time zone default now() not null,
  posted_at timestamp with time zone,
  seen_at timestamp with time zone,
  refund_reason text,
  refund_seen_at timestamp with time zone
);

-- @constraints
alter table public.card_plays add constraint card_plays_aimed_at_fkey FOREIGN KEY (aimed_at) REFERENCES players(id);
alter table public.card_plays add constraint card_plays_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards(id);
alter table public.card_plays add constraint card_plays_kind_check CHECK ((kind = ANY (ARRAY['boon'::text, 'prank'::text, 'neutral'::text])));
alter table public.card_plays add constraint card_plays_outcome_check CHECK ((outcome = ANY (ARRAY['applied'::text, 'blocked'::text, 'reflected'::text, 'decoyed'::text, 'redirected'::text, 'delayed'::text, 'refunded'::text])));
alter table public.card_plays add constraint card_plays_pkey PRIMARY KEY (id);
alter table public.card_plays add constraint card_plays_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id);
alter table public.card_plays add constraint card_plays_primitive_fkey FOREIGN KEY (primitive) REFERENCES effect_primitives(primitive);
alter table public.card_plays add constraint card_plays_rarity_check CHECK ((rarity = ANY (ARRAY['normal'::text, 'illustrated_rare'::text, 'secret_rare'::text, 'full_art'::text, 'gold'::text, 'promo'::text, 'event'::text])));
alter table public.card_plays add constraint card_plays_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id);
alter table public.card_plays add constraint card_plays_target_id_fkey FOREIGN KEY (target_id) REFERENCES players(id);

-- @indexes
CREATE UNIQUE INDEX card_plays_pkey ON public.card_plays USING btree (id);
CREATE INDEX card_plays_player_day ON public.card_plays USING btree (player_id, created_at);
CREATE INDEX card_plays_target_day ON public.card_plays USING btree (target_id, created_at);
CREATE INDEX card_plays_unposted ON public.card_plays USING btree (id) WHERE (posted_at IS NULL);

-- @rls
alter table public.card_plays enable row level security;

-- @grants
grant select on table public.card_plays to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_plays to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_plays to service_role;
