-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.card_sets

-- @owner
-- owner: postgres

-- @columns
create table public.card_sets (
  id text not null,
  name text not null,
  code text not null,
  released_at timestamp with time zone,
  pullable boolean default true not null,
  sort integer default 0 not null,
  last_number integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  pack_color text not null,
  pack_art_url text,
  season integer not null,
  cover_card_id bigint
);

-- @constraints
alter table public.card_sets add constraint card_sets_code_check CHECK ((code ~ '^[A-Z0-9]{1,8}$'::text));
alter table public.card_sets add constraint card_sets_code_key UNIQUE (code);
alter table public.card_sets add constraint card_sets_cover_in_set FOREIGN KEY (cover_card_id, id) REFERENCES cards(id, set_id) ON UPDATE RESTRICT ON DELETE SET NULL (cover_card_id);
alter table public.card_sets add constraint card_sets_id_check CHECK ((id ~ '^[A-Z0-9]{1,8}$'::text));
alter table public.card_sets add constraint card_sets_last_number_check CHECK ((last_number >= 0));
alter table public.card_sets add constraint card_sets_name_key UNIQUE (name);
alter table public.card_sets add constraint card_sets_pack_color_hex CHECK ((pack_color ~ '^#[0-9a-f]{6}$'::text));
alter table public.card_sets add constraint card_sets_pkey PRIMARY KEY (id);
alter table public.card_sets add constraint card_sets_season_positive CHECK ((season > 0));

-- @indexes
CREATE UNIQUE INDEX card_sets_code_key ON public.card_sets USING btree (code);
CREATE UNIQUE INDEX card_sets_name_key ON public.card_sets USING btree (name);
CREATE UNIQUE INDEX card_sets_pkey ON public.card_sets USING btree (id);

-- @rls
alter table public.card_sets enable row level security;

-- @grants
grant select on table public.card_sets to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_sets to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_sets to service_role;
