-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.card_effect_cooldowns

-- @owner
-- owner: postgres

-- @columns
create table public.card_effect_cooldowns (
  player_id text not null,
  subject_id bigint not null,
  ready_at timestamp with time zone not null
);

-- @constraints
alter table public.card_effect_cooldowns add constraint card_effect_cooldowns_pkey PRIMARY KEY (player_id, subject_id);
alter table public.card_effect_cooldowns add constraint card_effect_cooldowns_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id);
alter table public.card_effect_cooldowns add constraint card_effect_cooldowns_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id);

-- @indexes
CREATE UNIQUE INDEX card_effect_cooldowns_pkey ON public.card_effect_cooldowns USING btree (player_id, subject_id);

-- @rls
alter table public.card_effect_cooldowns enable row level security;

-- @grants
grant select on table public.card_effect_cooldowns to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_effect_cooldowns to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.card_effect_cooldowns to service_role;
