-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.daily_activity

-- @owner
-- owner: postgres

-- @columns
create table public.daily_activity (
  player_id text not null,
  activity_date date not null,
  message_count integer default 0 not null,
  base_claimed boolean default false not null,
  bonus_claimed boolean default false not null
);

-- @constraints
alter table public.daily_activity add constraint daily_activity_message_count_check CHECK ((message_count >= 0));
alter table public.daily_activity add constraint daily_activity_pkey PRIMARY KEY (player_id, activity_date);
alter table public.daily_activity add constraint daily_activity_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

-- @indexes
CREATE UNIQUE INDEX daily_activity_pkey ON public.daily_activity USING btree (player_id, activity_date);

-- @rls
alter table public.daily_activity enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.daily_activity to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.daily_activity to service_role;
