-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.discord_effects

-- @owner
-- owner: postgres

-- @columns
create table public.discord_effects (
  id bigint default nextval('discord_effects_id_seq'::regclass) not null,
  play_id bigint not null,
  target_id text not null,
  primitive text not null,
  amount numeric,
  duration_s integer,
  options jsonb default '{}'::jsonb not null,
  status text default 'pending'::text not null,
  execute_after timestamp with time zone default now() not null,
  revert_at timestamp with time zone,
  original_value text,
  error text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.discord_effects add constraint discord_effects_pkey PRIMARY KEY (id);
alter table public.discord_effects add constraint discord_effects_play_id_fkey FOREIGN KEY (play_id) REFERENCES card_plays(id);
alter table public.discord_effects add constraint discord_effects_primitive_fkey FOREIGN KEY (primitive) REFERENCES effect_primitives(primitive);
alter table public.discord_effects add constraint discord_effects_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text, 'done'::text, 'failed'::text, 'reverted'::text, 'skipped'::text])));
alter table public.discord_effects add constraint discord_effects_target_id_fkey FOREIGN KEY (target_id) REFERENCES players(id);

-- @indexes
CREATE UNIQUE INDEX discord_effects_pkey ON public.discord_effects USING btree (id);
CREATE INDEX discord_effects_todo ON public.discord_effects USING btree (status, execute_after);

-- @rls
alter table public.discord_effects enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.discord_effects to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.discord_effects to service_role;
