-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- view public.draw_pool

-- @owner
-- owner: postgres

-- @definition
create view public.draw_pool as
 SELECT c.id,
    c.subject_id,
    c.name,
    c.rarity,
    c.source,
    c.image_url,
    c.artist_credit,
    c.lore,
    c.set_id,
    c.set_number
   FROM cards c
     JOIN card_sets s ON s.id = c.set_id
  WHERE c.in_draw_pool AND c.source::text = 'draw'::text AND s.pullable;

-- @columns
--   id bigint
--   subject_id bigint
--   name text
--   rarity card_rarity
--   source card_source
--   image_url text
--   artist_credit text
--   lore text
--   set_id text
--   set_number integer

-- @grants
grant select on table public.draw_pool to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.draw_pool to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.draw_pool to service_role;
