-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.dungeon_payouts

-- @owner
-- owner: postgres

-- @columns
create table public.dungeon_payouts (
  mode text not null,
  period date not null,
  winners jsonb default '[]'::jsonb not null,
  paid_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.dungeon_payouts add constraint dungeon_payouts_mode_check CHECK ((mode = ANY (ARRAY['daily'::text, 'gauntlet'::text])));
alter table public.dungeon_payouts add constraint dungeon_payouts_pkey PRIMARY KEY (mode, period);

-- @indexes
CREATE UNIQUE INDEX dungeon_payouts_pkey ON public.dungeon_payouts USING btree (mode, period);

-- @rls
alter table public.dungeon_payouts enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.dungeon_payouts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.dungeon_payouts to service_role;
