-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.dungeon_monsters

-- @owner
-- owner: postgres

-- @columns
create table public.dungeon_monsters (
  key text not null,
  name text not null,
  model text not null,
  hp integer not null,
  atk integer not null,
  tags text[] default '{}'::text[] not null,
  moves jsonb default '[]'::jsonb not null
);

-- @constraints
alter table public.dungeon_monsters add constraint dungeon_monsters_pkey PRIMARY KEY (key);

-- @indexes
CREATE UNIQUE INDEX dungeon_monsters_pkey ON public.dungeon_monsters USING btree (key);

-- @rls
alter table public.dungeon_monsters enable row level security;

-- @grants
grant select on table public.dungeon_monsters to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.dungeon_monsters to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.dungeon_monsters to service_role;
