-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.dungeon_days

-- @owner
-- owner: postgres

-- @columns
create table public.dungeon_days (
  day date not null,
  name text not null,
  rule jsonb not null,
  floors jsonb not null,
  created_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.dungeon_days add constraint dungeon_days_pkey PRIMARY KEY (day);

-- @indexes
CREATE UNIQUE INDEX dungeon_days_pkey ON public.dungeon_days USING btree (day);

-- @rls
alter table public.dungeon_days enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.dungeon_days to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.dungeon_days to service_role;
