-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.effect_primitives

-- @owner
-- owner: postgres

-- @columns
create table public.effect_primitives (
  primitive text not null,
  kind text not null,
  channel text not null,
  max_amount numeric,
  max_duration_s integer,
  stacks boolean default false not null,
  enabled boolean default false not null,
  note text
);

-- @constraints
alter table public.effect_primitives add constraint effect_primitives_channel_check CHECK ((channel = ANY (ARRAY['app'::text, 'discord'::text, 'voice'::text])));
alter table public.effect_primitives add constraint effect_primitives_kind_check CHECK ((kind = ANY (ARRAY['boon'::text, 'prank'::text, 'neutral'::text])));
alter table public.effect_primitives add constraint effect_primitives_pkey PRIMARY KEY (primitive);

-- @indexes
CREATE UNIQUE INDEX effect_primitives_pkey ON public.effect_primitives USING btree (primitive);

-- @rls
alter table public.effect_primitives enable row level security;

-- @grants
grant select on table public.effect_primitives to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.effect_primitives to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.effect_primitives to service_role;
