-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.event_payouts

-- @owner
-- owner: postgres

-- @columns
create table public.event_payouts (
  event_id bigint not null,
  period text not null,
  paid_at timestamp with time zone default now() not null,
  members integer default 0 not null,
  packs integer default 0 not null,
  shards integer default 0 not null,
  cards integer default 0 not null
);

-- @constraints
alter table public.event_payouts add constraint event_payouts_cards_check CHECK ((cards >= 0));
alter table public.event_payouts add constraint event_payouts_event_id_fkey FOREIGN KEY (event_id) REFERENCES events(id);
alter table public.event_payouts add constraint event_payouts_members_check CHECK ((members >= 0));
alter table public.event_payouts add constraint event_payouts_packs_check CHECK ((packs >= 0));
alter table public.event_payouts add constraint event_payouts_period_check CHECK ((period ~ '^(start|end|tick:.+)$'::text));
alter table public.event_payouts add constraint event_payouts_pkey PRIMARY KEY (event_id, period);
alter table public.event_payouts add constraint event_payouts_shards_check CHECK ((shards >= 0));

-- @indexes
CREATE UNIQUE INDEX event_payouts_pkey ON public.event_payouts USING btree (event_id, period);

-- @rls
alter table public.event_payouts enable row level security;

-- @grants
grant select on table public.event_payouts to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.event_payouts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.event_payouts to service_role;
