-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.gauntlet_weeks

-- @owner
-- owner: postgres

-- @columns
create table public.gauntlet_weeks (
  week date not null,
  name text not null,
  squad bigint[] not null,
  theme text,
  floors jsonb not null,
  created_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.gauntlet_weeks add constraint gauntlet_weeks_pkey PRIMARY KEY (week);

-- @indexes
CREATE UNIQUE INDEX gauntlet_weeks_pkey ON public.gauntlet_weeks USING btree (week);

-- @rls
alter table public.gauntlet_weeks enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.gauntlet_weeks to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.gauntlet_weeks to service_role;
