-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.hunts

-- @owner
-- owner: postgres

-- @columns
create table public.hunts (
  id bigint default nextval('hunts_id_seq'::regclass) not null,
  name text not null,
  tier text not null,
  weak_points jsonb not null,
  hp_max bigint not null,
  hp_remaining bigint not null,
  opens_at timestamp with time zone default now() not null,
  closes_at timestamp with time zone not null,
  status text default 'active'::text not null,
  defeated_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  settled_at timestamp with time zone,
  resist_points jsonb default '[]'::jsonb not null,
  passive jsonb default '{}'::jsonb not null,
  hp_share bigint,
  stats jsonb
);

-- @constraints
alter table public.hunts add constraint hunts_hp_check CHECK (((hp_max > 0) AND (hp_remaining >= 0)));
alter table public.hunts add constraint hunts_pkey PRIMARY KEY (id);
alter table public.hunts add constraint hunts_status_check CHECK ((status = ANY (ARRAY['active'::text, 'defeated'::text, 'expired'::text])));
alter table public.hunts add constraint hunts_tier_check CHECK ((tier = ANY (ARRAY['Normal'::text, 'Heroic'::text, 'Mythic'::text])));

-- @indexes
CREATE UNIQUE INDEX hunts_pkey ON public.hunts USING btree (id);

-- @rls
alter table public.hunts enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunts to service_role;
