-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.hunt_combat_state

-- @owner
-- owner: postgres

-- @columns
create table public.hunt_combat_state (
  hunt_id bigint not null,
  player_id text not null,
  hit_date date not null,
  round integer default 0 not null,
  boss_enrage numeric default 1.0 not null,
  enrage_until integer default 0 not null,
  updated_at timestamp with time zone default now() not null,
  boss_weaken numeric default 0 not null,
  weaken_until integer default 0 not null,
  boss_expose numeric default 0 not null,
  expose_until integer default 0 not null,
  stunned_until integer default 0 not null,
  marks jsonb default '{}'::jsonb not null
);

-- @constraints
alter table public.hunt_combat_state add constraint hunt_combat_state_hunt_id_fkey FOREIGN KEY (hunt_id) REFERENCES hunts(id) ON DELETE CASCADE;
alter table public.hunt_combat_state add constraint hunt_combat_state_pkey PRIMARY KEY (hunt_id, player_id, hit_date);
alter table public.hunt_combat_state add constraint hunt_combat_state_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id);

-- @indexes
CREATE UNIQUE INDEX hunt_combat_state_pkey ON public.hunt_combat_state USING btree (hunt_id, player_id, hit_date);

-- @rls
alter table public.hunt_combat_state enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunt_combat_state to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunt_combat_state to service_role;
