-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.hunt_combat_log

-- @owner
-- owner: postgres

-- @columns
create table public.hunt_combat_log (
  id bigint default nextval('hunt_combat_log_id_seq'::regclass) not null,
  hunt_id bigint not null,
  player_id text not null,
  card_id bigint not null,
  ts timestamp with time zone default now() not null,
  cp integer,
  outcome text,
  bonus boolean,
  crit boolean,
  block boolean,
  damage integer,
  countered boolean,
  counter_dmg integer,
  card_hp_after integer,
  card_downed boolean,
  boss_hp_after bigint
);

-- @constraints
alter table public.hunt_combat_log add constraint hunt_combat_log_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards(id);
alter table public.hunt_combat_log add constraint hunt_combat_log_damage_check CHECK (((damage >= 0) AND (counter_dmg >= 0)));
alter table public.hunt_combat_log add constraint hunt_combat_log_hunt_id_fkey FOREIGN KEY (hunt_id) REFERENCES hunts(id) ON DELETE CASCADE;
alter table public.hunt_combat_log add constraint hunt_combat_log_outcome_check CHECK ((outcome = ANY (ARRAY['hit'::text, 'crit'::text, 'blocked'::text, 'miss'::text])));
alter table public.hunt_combat_log add constraint hunt_combat_log_pkey PRIMARY KEY (id);
alter table public.hunt_combat_log add constraint hunt_combat_log_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id);

-- @indexes
CREATE INDEX hunt_combat_log_hunt ON public.hunt_combat_log USING btree (hunt_id);
CREATE UNIQUE INDEX hunt_combat_log_pkey ON public.hunt_combat_log USING btree (id);

-- @rls
alter table public.hunt_combat_log enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunt_combat_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunt_combat_log to service_role;
