-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.hunt_events

-- @owner
-- owner: postgres

-- @columns
create table public.hunt_events (
  id bigint default nextval('hunt_events_id_seq'::regclass) not null,
  hunt_id bigint not null,
  kind text not null,
  payload jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  posted_at timestamp with time zone
);

-- @constraints
alter table public.hunt_events add constraint hunt_events_hunt_id_fkey FOREIGN KEY (hunt_id) REFERENCES hunts(id) ON DELETE CASCADE;
alter table public.hunt_events add constraint hunt_events_kind_check CHECK ((kind = ANY (ARRAY['spawn'::text, 'attack'::text, 'player_done'::text, 'defeat'::text, 'expired'::text, 'nudge'::text, 'leaderboard'::text])));
alter table public.hunt_events add constraint hunt_events_pkey PRIMARY KEY (id);

-- @indexes
CREATE INDEX hunt_events_hunt_id_idx ON public.hunt_events USING btree (hunt_id);
CREATE UNIQUE INDEX hunt_events_pkey ON public.hunt_events USING btree (id);
CREATE INDEX hunt_events_unposted ON public.hunt_events USING btree (id) WHERE (posted_at IS NULL);

-- @rls
alter table public.hunt_events enable row level security;

-- @grants
grant select on table public.hunt_events to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunt_events to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.hunt_events to service_role;
