-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.pack_ledger

-- @owner
-- owner: postgres

-- @columns
create table public.pack_ledger (
  id bigint generated always as identity not null,
  player_id text not null,
  amount integer not null,
  reason text not null,
  granted_by text,
  created_at timestamp with time zone default now() not null,
  ref_kind text,
  ref_id text,
  ledger text generated always as ('pack'::text) stored
);

-- @constraints
alter table public.pack_ledger add constraint pack_ledger_amount_check CHECK ((amount <> 0));
alter table public.pack_ledger add constraint pack_ledger_pkey PRIMARY KEY (id);
alter table public.pack_ledger add constraint pack_ledger_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.pack_ledger add constraint pack_ledger_reason_check FOREIGN KEY (ledger, reason) REFERENCES ledger_reasons(ledger, reason);
alter table public.pack_ledger add constraint pack_ledger_ref_check CHECK (((ref_kind IS NOT NULL) AND (ref_id IS NOT NULL)));

-- @indexes
CREATE UNIQUE INDEX pack_ledger_pkey ON public.pack_ledger USING btree (id);
CREATE INDEX pack_ledger_player_idx ON public.pack_ledger USING btree (player_id, created_at DESC);

-- @rls
alter table public.pack_ledger enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.pack_ledger to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.pack_ledger to service_role;

-- @triggers
CREATE TRIGGER pack_ledger_reason_guard BEFORE INSERT OR UPDATE OF reason ON public.pack_ledger FOR EACH ROW EXECUTE FUNCTION ledger_reason_guard('pack', 'pack_ledger_reason_check');
