-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.page_views

-- @owner
-- owner: postgres

-- @columns
create table public.page_views (
  id bigint generated always as identity not null,
  player_id text not null,
  view text not null,
  ref text,
  at timestamp with time zone default now() not null
);

-- @constraints
alter table public.page_views add constraint page_views_pkey PRIMARY KEY (id);
alter table public.page_views add constraint page_views_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.page_views add constraint page_views_ref_check CHECK ((char_length(ref) <= 40));
alter table public.page_views add constraint page_views_view_check CHECK ((view ~ '^[a-z_]{1,30}$'::text));

-- @indexes
CREATE UNIQUE INDEX page_views_pkey ON public.page_views USING btree (id);
CREATE INDEX page_views_player ON public.page_views USING btree (player_id, at);
CREATE INDEX page_views_view ON public.page_views USING btree (view, at);

-- @rls
alter table public.page_views enable row level security;

-- @grants
grant select on table public.page_views to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.page_views to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.page_views to service_role;
