-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.player_cards

-- @owner
-- owner: postgres

-- @columns
create table public.player_cards (
  player_id text not null,
  card_id bigint not null,
  quantity integer default 1 not null,
  first_obtained_at timestamp with time zone default now() not null,
  ascension integer default 0 not null,
  stat_points jsonb default '{}'::jsonb not null,
  first_source text default 'pull'::text not null
);

-- @constraints
alter table public.player_cards add constraint player_cards_ascension_check CHECK ((ascension >= 0));
alter table public.player_cards add constraint player_cards_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE;
alter table public.player_cards add constraint player_cards_pkey PRIMARY KEY (player_id, card_id);
alter table public.player_cards add constraint player_cards_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.player_cards add constraint player_cards_quantity_check CHECK ((quantity > 0));

-- @indexes
CREATE INDEX player_cards_card ON public.player_cards USING btree (card_id);
CREATE UNIQUE INDEX player_cards_pkey ON public.player_cards USING btree (player_id, card_id);
CREATE INDEX player_cards_pull_feed ON public.player_cards USING btree (first_obtained_at DESC) WHERE (first_source = 'pull'::text);

-- @rls
alter table public.player_cards enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.player_cards to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.player_cards to service_role;
