-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.playing_posts

-- @owner
-- owner: postgres

-- @columns
create table public.playing_posts (
  player_id text not null,
  day date not null,
  message_id text not null,
  updated_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.playing_posts add constraint playing_posts_pkey PRIMARY KEY (player_id, day);
alter table public.playing_posts add constraint playing_posts_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

-- @indexes
CREATE UNIQUE INDEX playing_posts_pkey ON public.playing_posts USING btree (player_id, day);

-- @rls
alter table public.playing_posts enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.playing_posts to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.playing_posts to service_role;
