-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.players

-- @owner
-- owner: postgres

-- @columns
create table public.players (
  id text not null,
  username text not null,
  created_at timestamp with time zone default now() not null,
  pack_balance integer default 0 not null,
  first_pack_ping_at timestamp with time zone,
  spotlight bigint[] default '{}'::bigint[] not null,
  avatar text,
  title text,
  frame text,
  stat_reset_week text,
  notify_prefs jsonb default '{}'::jsonb not null,
  tutorial jsonb default '{}'::jsonb not null,
  shard_balance integer default 0 not null,
  guild_joined_at timestamp with time zone,
  left_guild_at timestamp with time zone
);

-- @constraints
alter table public.players add constraint players_pack_balance_nonneg CHECK ((pack_balance >= 0));
alter table public.players add constraint players_pkey PRIMARY KEY (id);
alter table public.players add constraint players_shard_balance_nonneg CHECK ((shard_balance >= 0));
alter table public.players add constraint players_spotlight_max3 CHECK ((COALESCE(array_length(spotlight, 1), 0) <= 3));

-- @indexes
CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

-- @rls
alter table public.players enable row level security;

-- @grants
grant select on table public.players to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.players to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.players to service_role;

-- @triggers
CREATE TRIGGER players_welcome_packs AFTER INSERT ON public.players FOR EACH ROW EXECUTE FUNCTION welcome_packs();
