-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.player_reports

-- @owner
-- owner: postgres

-- @columns
create table public.player_reports (
  id bigint generated always as identity not null,
  player_id text not null,
  kind text not null,
  body text not null,
  context jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null,
  issue_number integer,
  issue_url text,
  synced_at timestamp with time zone,
  attempts integer default 0 not null,
  last_error text,
  target_id text
);

-- @constraints
alter table public.player_reports add constraint player_reports_body_check CHECK (((char_length(body) >= 5) AND (char_length(body) <= 1500)));
alter table public.player_reports add constraint player_reports_kind_check CHECK ((kind = ANY (ARRAY['bug'::text, 'feedback'::text, 'idea'::text])));
alter table public.player_reports add constraint player_reports_pkey PRIMARY KEY (id);
alter table public.player_reports add constraint player_reports_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.player_reports add constraint player_reports_target_id_fkey FOREIGN KEY (target_id) REFERENCES players(id);

-- @indexes
CREATE UNIQUE INDEX player_reports_pkey ON public.player_reports USING btree (id);
CREATE INDEX player_reports_player_day ON public.player_reports USING btree (player_id, created_at);
CREATE INDEX player_reports_unsynced ON public.player_reports USING btree (id) WHERE (synced_at IS NULL);

-- @rls
alter table public.player_reports enable row level security;

-- @grants
grant select on table public.player_reports to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.player_reports to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.player_reports to service_role;
