-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.roster_power_history

-- @owner
-- owner: postgres

-- @columns
create table public.roster_power_history (
  id bigint default nextval('roster_power_history_id_seq'::regclass) not null,
  captured_at timestamp with time zone default now() not null,
  players integer not null,
  owned_cards integer not null,
  total_power bigint not null,
  boss_hp_normal bigint not null,
  boss_hp_heroic bigint not null,
  boss_hp_mythic bigint not null,
  deployable_power bigint default 0 not null
);

-- @constraints
alter table public.roster_power_history add constraint roster_power_history_pkey PRIMARY KEY (id);

-- @indexes
CREATE UNIQUE INDEX roster_power_history_pkey ON public.roster_power_history USING btree (id);

-- @rls
alter table public.roster_power_history enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.roster_power_history to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.roster_power_history to service_role;
