-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.schema_migrations

-- @owner
-- owner: postgres

-- @columns
create table public.schema_migrations (
  id bigint default nextval('schema_migrations_id_seq'::regclass) not null,
  file text not null,
  sha256 text not null,
  applied_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.schema_migrations add constraint schema_migrations_pkey PRIMARY KEY (id);

-- @indexes
CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id);

-- @rls
alter table public.schema_migrations enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.schema_migrations to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.schema_migrations to service_role;
