-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.settings_log

-- @owner
-- owner: postgres

-- @columns
create table public.settings_log (
  id bigint generated always as identity not null,
  key text not null,
  op text not null,
  old_value jsonb,
  new_value jsonb,
  changed_at timestamp with time zone default now() not null,
  changed_by text not null
);

-- @constraints
alter table public.settings_log add constraint settings_log_op_check CHECK ((op = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text])));
alter table public.settings_log add constraint settings_log_pkey PRIMARY KEY (id);

-- @indexes
CREATE INDEX settings_log_key ON public.settings_log USING btree (key, changed_at DESC);
CREATE UNIQUE INDEX settings_log_pkey ON public.settings_log USING btree (id);

-- @rls
alter table public.settings_log enable row level security;

-- @grants
grant select on table public.settings_log to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.settings_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.settings_log to service_role;
