-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.shard_ledger

-- @owner
-- owner: postgres

-- @columns
create table public.shard_ledger (
  id bigint generated always as identity not null,
  player_id text not null,
  amount integer not null,
  reason text not null,
  ref_kind text,
  ref_id text,
  created_at timestamp with time zone default now() not null,
  ledger text generated always as ('shard'::text) stored
);

-- @constraints
alter table public.shard_ledger add constraint shard_ledger_amount_check CHECK ((amount <> 0));
alter table public.shard_ledger add constraint shard_ledger_pkey PRIMARY KEY (id);
alter table public.shard_ledger add constraint shard_ledger_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.shard_ledger add constraint shard_ledger_reason_check FOREIGN KEY (ledger, reason) REFERENCES ledger_reasons(ledger, reason);
alter table public.shard_ledger add constraint shard_ledger_ref_check CHECK (((ref_kind IS NOT NULL) AND (ref_id IS NOT NULL)));

-- @indexes
CREATE UNIQUE INDEX shard_ledger_pkey ON public.shard_ledger USING btree (id);
CREATE INDEX shard_ledger_player ON public.shard_ledger USING btree (player_id, created_at DESC);

-- @rls
alter table public.shard_ledger enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.shard_ledger to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.shard_ledger to service_role;

-- @triggers
CREATE TRIGGER shard_ledger_reason_guard BEFORE INSERT OR UPDATE OF reason ON public.shard_ledger FOR EACH ROW EXECUTE FUNCTION ledger_reason_guard('shard', 'shard_ledger_reason_check');
