-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.shop_purchases

-- @owner
-- owner: postgres

-- @columns
create table public.shop_purchases (
  id bigint generated always as identity not null,
  player_id text not null,
  day date not null,
  kind text not null,
  slot integer,
  card_id bigint,
  qty integer default 1 not null,
  price integer not null,
  created_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.shop_purchases add constraint shop_purchases_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards(id);
alter table public.shop_purchases add constraint shop_purchases_kind_check CHECK ((kind = ANY (ARRAY['pack'::text, 'card'::text, 'stat_reset'::text])));
alter table public.shop_purchases add constraint shop_purchases_pkey PRIMARY KEY (id);
alter table public.shop_purchases add constraint shop_purchases_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.shop_purchases add constraint shop_purchases_price_check CHECK ((price >= 0));
alter table public.shop_purchases add constraint shop_purchases_qty_check CHECK ((qty > 0));

-- @indexes
CREATE UNIQUE INDEX shop_purchases_one_slot ON public.shop_purchases USING btree (player_id, day, slot) WHERE (kind = 'card'::text);
CREATE UNIQUE INDEX shop_purchases_pkey ON public.shop_purchases USING btree (id);
CREATE INDEX shop_purchases_player ON public.shop_purchases USING btree (player_id, day);

-- @rls
alter table public.shop_purchases enable row level security;

-- @grants
grant select on table public.shop_purchases to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.shop_purchases to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.shop_purchases to service_role;
