-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.shop_stock

-- @owner
-- owner: postgres

-- @columns
create table public.shop_stock (
  day date not null,
  slot integer not null,
  card_id bigint not null,
  rarity text not null,
  price integer not null
);

-- @constraints
alter table public.shop_stock add constraint shop_stock_card_id_fkey FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE;
alter table public.shop_stock add constraint shop_stock_pkey PRIMARY KEY (day, slot);
alter table public.shop_stock add constraint shop_stock_price_check CHECK ((price > 0));
alter table public.shop_stock add constraint shop_stock_rarity_check CHECK ((rarity = ANY (ARRAY['normal'::text, 'illustrated_rare'::text, 'secret_rare'::text, 'full_art'::text, 'gold'::text, 'promo'::text, 'event'::text])));

-- @indexes
CREATE INDEX shop_stock_card ON public.shop_stock USING btree (card_id, day);
CREATE UNIQUE INDEX shop_stock_pkey ON public.shop_stock USING btree (day, slot);

-- @rls
alter table public.shop_stock enable row level security;

-- @grants
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.shop_stock to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.shop_stock to service_role;
