-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.stat_point_log

-- @owner
-- owner: postgres

-- @columns
create table public.stat_point_log (
  id bigint generated always as identity not null,
  player_id text not null,
  card_id bigint not null,
  stat text not null,
  delta numeric not null,
  points numeric not null,
  reason text not null,
  changed_at timestamp with time zone default now() not null,
  changed_by text not null
);

-- @constraints
alter table public.stat_point_log add constraint stat_point_log_pkey PRIMARY KEY (id);
alter table public.stat_point_log add constraint stat_point_log_reason_check CHECK ((reason = ANY (ARRAY['spend'::text, 'reset'::text, 'other'::text])));

-- @indexes
CREATE INDEX stat_point_log_card ON public.stat_point_log USING btree (card_id, changed_at DESC);
CREATE UNIQUE INDEX stat_point_log_pkey ON public.stat_point_log USING btree (id);
CREATE INDEX stat_point_log_player ON public.stat_point_log USING btree (player_id, changed_at DESC);

-- @rls
alter table public.stat_point_log enable row level security;

-- @grants
grant select on table public.stat_point_log to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.stat_point_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.stat_point_log to service_role;
