-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.tutorial_steps

-- @owner
-- owner: postgres

-- @columns
create table public.tutorial_steps (
  player_id text not null,
  step text not null,
  done_at timestamp with time zone default now() not null
);

-- @constraints
alter table public.tutorial_steps add constraint tutorial_steps_pkey PRIMARY KEY (player_id, step);
alter table public.tutorial_steps add constraint tutorial_steps_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;
alter table public.tutorial_steps add constraint tutorial_steps_step_check CHECK (((char_length(step) >= 1) AND (char_length(step) <= 40)));

-- @indexes
CREATE INDEX tutorial_steps_done ON public.tutorial_steps USING btree (done_at);
CREATE UNIQUE INDEX tutorial_steps_pkey ON public.tutorial_steps USING btree (player_id, step);

-- @rls
alter table public.tutorial_steps enable row level security;

-- @grants
grant select on table public.tutorial_steps to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.tutorial_steps to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.tutorial_steps to service_role;
