-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.voice_minutes

-- @owner
-- owner: postgres

-- @columns
create table public.voice_minutes (
  player_id text not null,
  day date not null,
  minutes integer default 0 not null
);

-- @constraints
alter table public.voice_minutes add constraint voice_minutes_minutes_check CHECK ((minutes >= 0));
alter table public.voice_minutes add constraint voice_minutes_pkey PRIMARY KEY (player_id, day);
alter table public.voice_minutes add constraint voice_minutes_player_id_fkey FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

-- @indexes
CREATE UNIQUE INDEX voice_minutes_pkey ON public.voice_minutes USING btree (player_id, day);

-- @rls
alter table public.voice_minutes enable row level security;

-- @grants
grant select on table public.voice_minutes to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.voice_minutes to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.voice_minutes to service_role;
