-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.
-- table public.wishlist_log

-- @owner
-- owner: postgres

-- @columns
create table public.wishlist_log (
  id bigint generated always as identity not null,
  player_id text not null,
  slot integer not null,
  op text not null,
  card_id bigint,
  old_card_id bigint,
  changed_at timestamp with time zone default now() not null,
  changed_by text not null
);

-- @constraints
alter table public.wishlist_log add constraint wishlist_log_op_check CHECK ((op = ANY (ARRAY['add'::text, 'remove'::text, 'replace'::text, 'set_top'::text, 'unset_top'::text])));
alter table public.wishlist_log add constraint wishlist_log_pkey PRIMARY KEY (id);

-- @indexes
CREATE INDEX wishlist_log_card ON public.wishlist_log USING btree (card_id, changed_at DESC);
CREATE UNIQUE INDEX wishlist_log_pkey ON public.wishlist_log USING btree (id);
CREATE INDEX wishlist_log_player ON public.wishlist_log USING btree (player_id, changed_at DESC);

-- @rls
alter table public.wishlist_log enable row level security;

-- @grants
grant select on table public.wishlist_log to lptcg_backup;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.wishlist_log to postgres;
grant delete, insert, maintain, references, select, trigger, truncate, update on table public.wishlist_log to service_role;
