-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @extensions
create extension pg_cron with schema pg_catalog version '1.6.4';
create extension pg_stat_statements with schema extensions version '1.11';
create extension pgcrypto with schema extensions version '1.3';
create extension plpgsql with schema pg_catalog version '1.0';
create extension supabase_vault with schema vault version '0.3.1';
create extension "uuid-ossp" with schema extensions version '1.1';
