-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @enums
create type public.card_rarity as enum ('normal', 'illustrated_rare', 'secret_rare', 'full_art', 'gold', 'promo', 'event');
create type public.card_source as enum ('draw', 'achievement', 'event', 'promo');
create type public.submission_status as enum ('pending', 'approved', 'rejected');

-- @domains

-- @composite types
