#!/bin/sh
# Review 2 of design 26 (Nathan, 2026-10-01), then the phone sets (landscape + portrait).
cd /c/Users/vaugh/discord-design
MRULES="$(sed -n 's/^RULES="\(.*\)"$/\1/p' design/mobile-jobs.sh | head -1)"
run() { echo "== $2"; pen --in "design/$1" --out "design/$2.pen" --prompt "$3" --export "design/$2.png" --export-scale 2 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tail -2; }
run 26-hall-c.pen 26-hall-d "Change the Hall and Auction frames after Nathan's second review (keep everything else). Nathan's words: 03 Trading Hall: I like the separation but instead of rows that you have to click through, have two sub views in the window itself for Wanted and For Trade; those two sub views are right where the current Wanted title is (one grid at a time, the pager stays). 04 and 05: instead of You Give say Your Offer, and instead of You Get say Their Offer. 06 Auctions: the same sub tab approach, Open Auctions and My Auctions, so they can see all the auctions or just their auctions; they can click into any auction to get the information; in their own auction they can see the information and either close the auction early with no accepts or accept a bid regardless of the time left, and then the bidder accepts the offer too, so it is 2 stepped. 07 Start an auction: give the auctioneer the ability to set the length of the auction, at most 14 days. 08 Seller view: the auctioneer can click on the bid cards to see the card information. 09 Bidder view: in My cards, the cards that are on the auctioneer's wishlist or named in their requirements are highlighted and shown first. Sample names only."
run 26-hall-d.pen 27-hall-land "MOBILE LANDSCAPE set for the Trading Hall and Auctions: frames of 844 x 390 (a phone held sideways in the Discord app), side by side, titled, one for each desktop frame of the Wishlist, Hall and Auction screens in this file (profile with wishlist, edit a wishlist slot, Hall with the Wanted | For trade sub views, offer on a Wanted card, offer on a For trade card, Auctions with Open | My sub views, start an auction, seller view, bidder view). $MRULES"
run 27-hall-land.pen 27-hall-port "MOBILE PORTRAIT set for the Trading Hall and Auctions: frames of 390 x 760 (a phone held upright in the Discord app), side by side, titled, one for each desktop frame of the Wishlist, Hall and Auction screens in this file (profile with wishlist, edit a wishlist slot, Hall with the Wanted | For trade sub views, offer on a Wanted card, offer on a For trade card, Auctions with Open | My sub views, start an auction, seller view, bidder view). $MRULES"
echo ALL-DONE
