#!/bin/sh
# The mobile design set (Nathan, 2026-10-01): landscape 844x390 + portrait 390x760, 4 jobs in a chain.
cd /c/Users/vaugh/discord-design
RULES="STRICT: this is a LAYOUT change only. Each mobile frame shows exactly the sections, buttons, labels, numbers and data of the matching DESKTOP screen already in this file, rearranged to fit. Do NOT add any feature, button, tab, stat, badge, icon, text or data that the desktop screen does not have, and do not remove any. Rules for every frame: the same colors, fonts and components as the desktop screens; the 5-item dock (Home, Collection, gold OPEN in the middle, Hunt, Community) is ALWAYS visible; ZERO SCROLLING anywhere: no page scroll and no scroll inside any panel, list, sheet or box. Do NOT shrink things to make them fit: keep everything easy to read (body text at least 12 px, small labels at least 10.5 px, names never cut to a few letters, card art at least 72 px wide, buttons at least 40 px tall). Instead SET LIMITS on what each screen shows: the Leaderboard shows the top 10 at most, Live pulls the newest 5, Live in voice at most 4 tiles then a +N chip, the attack feed the newest 4, the bell the newest 5; the card grids show one page of readable cards and use the pager that the desktop screens already have (the < 1 of 4 > control); no explanatory subtitles or helper sentences under labels; tap targets at least 40 px; the raid boss is the live 3D model, no box or circle around it; the Discord mobile overlay may cover the top-left 60 px, keep it free of buttons."
run() { echo "== $2"; pen --in "design/$1" --out "design/$2.pen" --prompt "$3 $RULES" --export "design/$2.png" --export-scale 2 2>&1 | sed 's/\x1b\[[0-9;]*m//g' | tail -2; }
run 22-tutorial-steps.pen 24-mobile-land-a "MOBILE LANDSCAPE set, part 1: 5 frames of 844 x 390 (a phone held sideways in the Discord app), side by side, titled. 1) Home: a slim top bar (exactly these icons at 34 px: calendar, ?, bell, trophy, avatar; there is NO wrench), the Pride Hunt card on the left (boss name, HP bar, Join the hunt) and Live pulls on the right as a short list; Live in voice as one row of small tiles under the hunt card. 2) Collection: the desktop filter panel as a narrow rail on the left, a card grid in the middle that fills the height, and no side panel (a tap opens the full-screen card view). 3) The full-screen card view: the big card on the left, its name, rarity, stars, stats and effect on the right, a close X. 4) Hunt squad select: the boss on the left, 8 squad slots as one row of small card slots, the pick grid on the right, Auto-pick and Lock in buttons. 5) Hunt battle: the live boss in the middle, the HP bar on top, the 8 squad cards as one row at the bottom above the dock, the attack feed as a narrow column on the right."
run 24-mobile-land-a.pen 24-mobile-land-b "MOBILE LANDSCAPE set, part 2: 5 frames of 844 x 390, side by side, titled. 1) Community: the same sections as the desktop Community screen (the member list and the trade offers), side by side. 2) The OPEN chooser (1, 5 or 10 packs, as on desktop) as a compact sheet above the dock. 3) The 1-pack reveal: 5 cards in one row that fill the height, the reactions row and Done. 4) The 10-pack reveal: 50 small cards in a 17 x 3 grid that fills the space between the top bar and the dock, '50 cards', '0 / 50', Reveal all and X. 5) The Dailies panel as a right-side sheet the full height of the window (summary 0 / 5 packs and the 5 rows: Check in, Chat, Hunt the boss, Voice with someone, Trade or boon)."
run 24-mobile-land-b.pen 25-mobile-port-a "MOBILE PORTRAIT set, part 1: 5 frames of 390 x 760 (a phone held upright in the Discord app), side by side, titled. 1) Home: a top bar with the lion emblem only and exactly these icons at 34 px: calendar, ?, bell, avatar (NO wrench; the trophy button moves into the Community screen as the same button), the Pride Hunt card full width (live boss, name, HP bar, Join the hunt), Live in voice as one horizontal row of tiles, Live pulls as the newest rows that fit. 2) Collection: the search field, and the desktop filter panel behind a Filters button (a bottom sheet with the same filters), a 3-column card grid with the desktop pager. 3) The full-screen card view: the big card on top, name, rarity, stars, stats and effect below, a close X. 4) Hunt squad select: the boss on top, the 8 squad slots as one row of small slots, a 3-column pick grid, Auto-pick and Lock in above the dock. 5) Hunt battle: the live boss on top, the HP bar, the attack feed as a short list, the 8 squad cards as two rows of 4 above the dock."
run 25-mobile-port-a.pen 25-mobile-port-b "MOBILE PORTRAIT set, part 2: 5 frames of 390 x 760, side by side, titled. 1) Community: the same sections as the desktop Community screen stacked in one column (the member list, then the trade offers), plus the trophy button from the top bar. 2) The OPEN chooser (1, 5 or 10 packs, as on desktop) as a bottom sheet above the dock. 3) The 1-pack reveal: 5 cards as 3 + 2, the reactions row and Done. 4) The 10-pack reveal: 50 small cards in a 7-column grid that fills the space, '50 cards', '0 / 50', Reveal all and X. 5) The Dailies as a bottom sheet (summary 0 / 5 packs and the 5 rows); show that the bell and Help use the same bottom sheet."
echo ALL-DONE
