-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ach_tracks_on(text)
-- md5: c4da6cb7debb9257c64647b4441bc5e6   (md5(replace(pg_get_functiondef('public.ach_tracks_on(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ach_tracks_on(p_player text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select coalesce((select coalesce((value->>'enabled')::boolean, false)
                       or coalesce(value->'users', '[]'::jsonb) ? p_player
                     from settings where key = 'achievement_tracks'), false);
$function$;
-- @grants public.ach_tracks_on(text)
grant execute on function public.ach_tracks_on(text) to postgres;
grant execute on function public.ach_tracks_on(text) to service_role;
