-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ach_tier_paid_before(text, text, integer)
-- md5: 21e4e5610b1c63d9eec726a9a36d3e49   (md5(replace(pg_get_functiondef('public.ach_tier_paid_before(text, text, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ach_tier_paid_before(p_player text, p_track text, p_tier integer)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select p_tier between 1 and 5 and ach_tier_need(p_track, p_tier) <= (
    select greatest(coalesce(sum(m.proves) filter (where m.adds), 0), coalesce(max(m.proves) filter (where not m.adds), 0))
      from achievement_switch_map m join achievement_claims c on c.key = m.old_key and c.player_id = p_player
     where m.track = p_track);
$function$;
-- @grants public.ach_tier_paid_before(text, text, integer)
grant execute on function public.ach_tier_paid_before(text, text, integer) to postgres;
grant execute on function public.ach_tier_paid_before(text, text, integer) to service_role;
