-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ach_tier_reward(text, integer)
-- md5: 95d335569c2099edce04023e82e3e163   (md5(replace(pg_get_functiondef('public.ach_tier_reward(text, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ach_tier_reward(p_track text, p_tier integer)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select case p_tier
    when 1 then balance_get('achievement_rewards')->'tiers'->0
    when 2 then balance_get('achievement_rewards')->'tiers'->1
    when 3 then balance_get('achievement_rewards')->'tiers'->2 || jsonb_build_object('title', t.titles[1])
    when 4 then balance_get('achievement_rewards')->'tiers'->3 || jsonb_build_object('title', t.titles[2], 'frame', 'diamond:' || t.key)
    when 5 then balance_get('achievement_rewards')->'tiers'->4 || jsonb_build_object('title', t.titles[3], 'frame', 'mythic:' || t.key)
    else balance_get('achievement_rewards')->'step' || jsonb_build_object('title', t.titles[3] || ' +' || (p_tier - 5))
  end from achievement_tracks t where t.key = p_track and p_tier >= 1;
$function$;
-- @grants public.ach_tier_reward(text, integer)
grant execute on function public.ach_tier_reward(text, integer) to postgres;
grant execute on function public.ach_tier_reward(text, integer) to service_role;
