-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ach_tag_badges(text)
-- md5: 8843b3946ad845ece37481b4955dbf5c   (md5(replace(pg_get_functiondef('public.ach_tag_badges(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ach_tag_badges(p_player text)
 RETURNS TABLE(key text, season text, short text, tag text, label text, title text, need integer, have integer, packs integer)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with pool as (
    select coalesce(c.season, 'Season 1') season, c.subject_id, c.id card_id, s.tag_slugs
      from cards c join subjects s on s.id = c.subject_id
     where c.in_draw_pool and c.rarity::text <> 'event'),
  subj as (
    select p.season, p.subject_id, t.slug
      from pool p cross join lateral unnest(p.tag_slugs) t(slug)
     where t.slug like 'origin:%' or t.slug like 'type:%'
     group by 1, 2, 3),
  mine as (
    select distinct p.season, p.subject_id from pool p
      join player_cards pc on pc.card_id = p.card_id and pc.player_id = p_player and pc.quantity > 0),
  b as (
    select s.season, s.slug, count(*)::int need, count(m.subject_id)::int have
      from subj s left join mine m on m.season = s.season and m.subject_id = s.subject_id
     group by 1, 2)
  select 'tag:' || sh.short || ':' || b.slug, b.season, sh.short, b.slug,
         initcap(split_part(b.slug, ':', 2)), initcap(split_part(b.slug, ':', 2)) || ' Master ' || sh.short,
         b.need, b.have, (ceil(b.need / balance_num('achievement_rewards', 'tag_badge', 'cards_per_pack')) + balance_num('achievement_rewards', 'tag_badge', 'extra_packs'))::int
    from b cross join lateral (select coalesce('S' || substring(b.season from '(\d+)'), b.season) short) sh
   order by b.season, b.slug like 'type:%', b.need desc, b.slug;
$function$;
-- @grants public.ach_tag_badges(text)
grant execute on function public.ach_tag_badges(text) to postgres;
grant execute on function public.ach_tag_badges(text) to service_role;
