-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ach_has_element(jsonb)
-- md5: 2a18b4f269a791202de3031f7966aa65   (md5(replace(pg_get_functiondef('public.ach_has_element(jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ach_has_element(p_tags jsonb)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  -- One element list: card_element / element_aliases (card_decisions.sql).
  select public.card_element(array(select jsonb_array_elements_text(case when jsonb_typeof(p_tags->'traits') = 'array' then p_tags->'traits' else '[]'::jsonb end))) is not null;
$function$;
-- @grants public.ach_has_element(jsonb)
grant execute on function public.ach_has_element(jsonb) to postgres;
grant execute on function public.ach_has_element(jsonb) to service_role;
