-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.achievement_view(text)
-- md5: 0249f80104a4a598ab003001cfc2f3d5   (md5(replace(pg_get_functiondef('public.achievement_view(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.achievement_view(p_player text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare vals jsonb; tracks jsonb := '[]'::jsonb; badges jsonb := '[]'::jsonb; t record; b record;
  val bigint; reached int; claimed int; ready int := 0; nxt bigint;
begin
  if not ach_tracks_on(p_player) then return jsonb_build_object('enabled', false); end if;
  vals := ach_track_values(p_player);
  for t in select * from achievement_tracks order by ord loop
    val := coalesce((vals->>t.key)::bigint, 0);
    reached := 0;
    loop
      nxt := ach_tier_need(t.key, reached + 1);
      exit when nxt is null or val < nxt or reached > 2000;
      reached := reached + 1;
    end loop;
    select count(*) into claimed from achievement_claims where player_id = p_player and key like 'track:' || t.key || ':%';
    -- claimed counts the tiers paid; a tier is never claimed out of order, so reached - claimed is ready
    ready := ready + greatest(reached - claimed, 0);
    tracks := tracks || jsonb_build_object('key', t.key, 'group', t.grp, 'name', t.name, 'value', val,
      'tiers', to_jsonb(t.tiers), 'step', t.step, 'titles', to_jsonb(t.titles),
      'reached', reached, 'claimed', claimed, 'next', nxt);
  end loop;
  for b in select x.*, exists (select 1 from achievement_claims c where c.player_id = p_player and c.key = x.key) done
             from ach_tag_badges(p_player) x loop
    if b.have >= b.need and not b.done then ready := ready + 1; end if;
    badges := badges || jsonb_build_object('key', b.key, 'season', b.season, 'short', b.short, 'tag', b.tag, 'label', b.label,
      'title', b.title, 'need', b.need, 'have', b.have, 'packs', b.packs, 'claimed', b.done);
  end loop;
  return jsonb_build_object('enabled', true, 'tracks', tracks, 'badges', badges, 'ready', ready,
    'retired', (select coalesce(jsonb_agg(old_key), '[]'::jsonb) from achievement_switch_map));
end $function$;
-- @grants public.achievement_view(text)
grant execute on function public.achievement_view(text) to postgres;
grant execute on function public.achievement_view(text) to service_role;
