-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.achievement_gallery(text)
-- md5: beac899fe15339260423c3897d1c5b20   (md5(replace(pg_get_functiondef('public.achievement_gallery(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.achievement_gallery(p_player text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with own_t as (select title v, count(distinct player_id) n, bool_or(player_id = p_player) mine
                   from achievement_claims where title is not null group by title),
       own_f as (select frame v, count(distinct player_id) n, bool_or(player_id = p_player) mine
                   from achievement_claims where frame is not null group by frame),
       plus as (select t.key, max(substring(c.title from ' \+(\d+)$')::int) best
                  from achievement_tracks t join achievement_claims c on c.player_id = p_player and c.key like 'track:' || t.key || ':%'
                 where c.title like t.titles[3] || ' +%' group by t.key),
       items as (
         select t.ord, t.key track, 'title' kind, t.titles[i] v, i + 2 tier, t.tiers[i + 2] need, null::text badge
           from achievement_tracks t cross join generate_series(1, 3) i
         union all
         select t.ord, t.key, 'frame', f || ':' || t.key, case f when 'diamond' then 4 else 5 end,
                t.tiers[case f when 'diamond' then 4 else 5 end], null
           from achievement_tracks t cross join unnest(array['diamond', 'mythic']) f
         union all
         select 1000, null, 'title', b.title, null, b.need, b.key from ach_tag_badges(p_player) b)
  select jsonb_build_object(
    'members', (select count(distinct player_id) from achievement_claims),
    'items', coalesce((select jsonb_agg(jsonb_build_object('kind', i.kind, 'value', i.v, 'track', i.track, 'tier', i.tier,
               'need', i.need, 'badge', i.badge, 'owners', coalesce(case i.kind when 'title' then ot.n else of.n end, 0),
               'mine', coalesce(case i.kind when 'title' then ot.mine else of.mine end, false),
               'plus', case when i.kind = 'title' and i.tier = 5 then p.best end)
               order by i.ord, i.kind desc, i.tier)
             from items i left join own_t ot on i.kind = 'title' and ot.v = i.v left join own_f of on i.kind = 'frame' and of.v = i.v
             left join plus p on p.key = i.track), '[]'::jsonb),
    'owned', jsonb_build_object(
      'titles', coalesce((select jsonb_object_agg(v, jsonb_build_object('owners', n, 'mine', mine)) from own_t), '{}'::jsonb),
      'frames', coalesce((select jsonb_object_agg(v, jsonb_build_object('owners', n, 'mine', mine)) from own_f), '{}'::jsonb)));
$function$;
-- @grants public.achievement_gallery(text)
grant execute on function public.achievement_gallery(text) to postgres;
grant execute on function public.achievement_gallery(text) to service_role;
