-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.add_cards_to_player(text, bigint[])
-- md5: 95870387c3be9cb49983099a84d4ca94   (md5(replace(pg_get_functiondef('public.add_cards_to_player(text, bigint[])'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.add_cards_to_player(p_player_id text, p_card_ids bigint[])
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_open text; v_reason text := 'pack'; r record;
begin
  -- open_packs wrote its pack_ledger 'opened' rows (one open id) just before this call, in this transaction.
  select ref_id into v_open from pack_ledger
   where player_id = p_player_id and reason = 'opened' and ref_kind = 'open' and created_at = now()
   order by id desc limit 1;
  if v_open is null then
    -- No pack spent: the bot's openTestPacks (testers draw without a pack). One id for the cards of this call.
    v_reason := 'test_pack'; v_open := gen_random_uuid()::text;
  end if;
  for r in select cid, count(*)::int as n from unnest(p_card_ids) as cid group by cid order by cid loop
    perform card_move(p_player_id, r.cid, r.n, v_reason, case when v_reason = 'pack' then 'open' else 'test_open' end, v_open, 'pull');
  end loop;
end $function$;
-- @grants public.add_cards_to_player(text, bigint[])
grant execute on function public.add_cards_to_player(text, bigint[]) to postgres;
grant execute on function public.add_cards_to_player(text, bigint[]) to service_role;
