-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.add_card_to_player(text, bigint, text)
-- md5: de0c71f999a111e3b5ca9138fc4e3dc5   (md5(replace(pg_get_functiondef('public.add_card_to_player(text, bigint, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.add_card_to_player(p_player_id text, p_card_id bigint, p_source text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_reason text; v_kind text; v_ref text; g record;
begin
  -- The callers that other files guard pass only a source; the ref is the source row they wrote earlier in
  -- this transaction (the same now()). The other paths call card_move with their ref directly.
  if p_source = 'gift' then  -- claim_gift: the card gift claimed now
    select id, reason into g from gift_claims
     where player_id = p_player_id and card_id = p_card_id and kind = 'card' and claimed_at = now()
     order by id desc limit 1;
    if g.id is not null then
      v_reason := case when g.reason = 'member_gift' then 'gift_received' else 'event' end;
      v_kind := 'gift'; v_ref := g.id::text;
    end if;
  elsif p_source = 'shop' then  -- buy_shop_item: today's slot with this card that the member has not bought yet
    select s.day::text || ':' || s.slot into v_ref from shop_stock s
     where s.day = shop_day() and s.card_id = p_card_id
       and not exists (select 1 from shop_purchases x where x.player_id = p_player_id and x.day = s.day and x.kind = 'card' and x.slot = s.slot)
     order by s.slot limit 1;
    if v_ref is not null then v_reason := 'shop'; v_kind := 'shop_card'; end if;
  elsif p_source = 'dungeon' then  -- dungeon_settle: the member's active run that holds the card
    select r.id::text into v_ref from dungeon_runs r
     where r.player_id = p_player_id and r.status = 'active'
       and exists (select 1 from jsonb_array_elements_text(coalesce(r.state->'bank'->'cards', '[]') || coalesce(r.state->'pend'->'cards', '[]')) e
                    where e = p_card_id::text)
     order by r.id desc limit 1;
    if v_ref is not null then v_reason := 'dungeon_loot'; v_kind := 'dungeon_run'; end if;
  elsif p_source = 'dungeon_prize' then  -- dungeon_pay: the payout row made now
    select mode || ':' || period::text into v_ref from dungeon_payouts where paid_at = now() order by mode, period limit 1;
    if v_ref is not null then v_reason := 'dungeon_prize'; v_kind := 'dungeon_payout'; end if;
  end if;
  if v_kind is null then  -- no known source row: an admin move, traceable to its transaction
    v_reason := 'admin'; v_kind := 'tx'; v_ref := txid_current()::text;
  end if;
  perform card_move(p_player_id, p_card_id, 1, v_reason, v_kind, v_ref, coalesce(p_source, 'pull'));
end $function$;
-- @grants public.add_card_to_player(text, bigint, text)
grant execute on function public.add_card_to_player(text, bigint, text) to postgres;
grant execute on function public.add_card_to_player(text, bigint, text) to service_role;
