-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.add_voice_minutes(text[])
-- md5: 9752ca75dd040d5f115263d6d7541b2d   (md5(replace(pg_get_functiondef('public.add_voice_minutes(text[])'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.add_voice_minutes(p_ids text[])
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := coalesce((select value from settings where key = 'dailies'), '{}'::jsonb);
  mult numeric := (balance_get('pack_earn_multiplier') #>> '{}')::numeric;
  n int;
begin
  if coalesce((cfg->>'enabled')::boolean, false) is not true or mult <= 0 then return 0; end if;
  insert into voice_minutes as v (player_id, day, minutes)
    select distinct u.id, (now() at time zone 'America/Denver')::date, 1
    from unnest(p_ids) as u(id) join players p on p.id = u.id
  on conflict (player_id, day) do update set minutes = v.minutes + 1;
  get diagnostics n = row_count;
  return n;
end $function$;
-- @grants public.add_voice_minutes(text[])
grant execute on function public.add_voice_minutes(text[]) to postgres;
grant execute on function public.add_voice_minutes(text[]) to service_role;
