-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_balance_set(text, text, text[], jsonb, jsonb, text, bigint)
-- md5: c989095bdc480e95222faab011319608   (md5(replace(pg_get_functiondef('public.admin_balance_set(text, text, text[], jsonb, jsonb, text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_balance_set(p_actor text, p_key text, p_path text[], p_before jsonb, p_after jsonb, p_reason text, p_undo_of bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_val jsonb; v_cur jsonb; v_new jsonb; v_id bigint; v_path text[] := coalesce(p_path, '{}');
begin
  perform admin_write_begin(p_actor, p_reason);
  if p_after is null then raise exception using errcode = 'LP400', message = 'admin: the new value is required'; end if;
  select value into v_val from balance where key = p_key for update;
  if not found then raise exception using errcode = 'LP400', message = format('admin: no balance key %s', p_key); end if;
  v_cur := v_val #> v_path;
  if v_cur is null then raise exception using errcode = 'LP400', message = format('admin: balance %s has no value at %s', p_key, array_to_string(v_path, '.')); end if;
  if v_cur is distinct from p_before then perform admin_stale(btrim(format('balance %s %s', p_key, array_to_string(v_path, '.'))), v_cur, p_before); end if;
  if jsonb_typeof(p_after) <> jsonb_typeof(v_cur) then
    raise exception using errcode = 'LP400', message = format('admin: balance %s %s must stay a %s', p_key, array_to_string(v_path, '.'), jsonb_typeof(v_cur));
  end if;
  if p_after = v_cur then raise exception using errcode = 'LP400', message = 'admin: the new value is the same as the live value'; end if;
  v_new := case when cardinality(v_path) = 0 then p_after else jsonb_set(v_val, v_path, p_after, false) end;
  if p_key = 'pulls' then perform admin_check_pulls(v_new); end if;
  update balance set value = v_new where key = p_key;   -- balance_check and balance_check_settings check the shape here
  v_id := admin_log_action(p_actor, 'balance_set', 'balance', p_key, jsonb_build_object('path', to_jsonb(v_path), 'value', v_cur),
    jsonb_build_object('path', to_jsonb(v_path), 'value', p_after), p_reason, 'studio', p_undo_of);
  return jsonb_build_object('action_id', v_id, 'key', p_key, 'path', to_jsonb(v_path), 'before', v_cur, 'after', p_after);
end $function$;
-- @grants public.admin_balance_set(text, text, text[], jsonb, jsonb, text, bigint)
grant execute on function public.admin_balance_set(text, text, text[], jsonb, jsonb, text, bigint) to postgres;
grant execute on function public.admin_balance_set(text, text, text[], jsonb, jsonb, text, bigint) to service_role;
