-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_event_save(jsonb, timestamp with time zone, text, text)
-- md5: fabbe94949521a6d2fa6b28ed87e29e9   (md5(replace(pg_get_functiondef('public.admin_event_save(jsonb, timestamp with time zone, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_event_save(p_event jsonb, p_expected_updated_at timestamp with time zone, p_actor text, p_reason text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare e events; c events; v_errors text[]; v_fields jsonb; v_id bigint; k text;
  editable constant text[] := array['key', 'kind', 'title', 'description', 'starts_at', 'ends_at', 'audience', 'rewards', 'rules'];
begin
  if coalesce(trim(p_actor), '') = '' then raise exception 'admin_event_save: the actor is required'; end if;
  if p_event is null or jsonb_typeof(p_event) <> 'object' then return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', jsonb_build_array('the event must be an object')); end if;
  for k in select jsonb_object_keys(p_event) loop
    if k <> 'id' and not k = any(editable) then return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', jsonb_build_array(format('%s cannot be set', k))); end if;
  end loop;
  v_fields := p_event - 'id';
  begin
    v_id := (p_event->>'id')::bigint;
    if v_id is null then
      c := jsonb_populate_record(null::events, v_fields || jsonb_build_object('status', 'draft', 'created_by', p_actor));
      c.audience := coalesce(c.audience, '{"all": true}'); c.rewards := coalesce(c.rewards, '{}'); c.rules := coalesce(c.rules, '{}');
      c.description := coalesce(c.description, '');
    else
      select * into e from events where id = v_id for update;
      if not found then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
      c := jsonb_populate_record(e, v_fields);
    end if;
  exception when invalid_text_representation or datetime_field_overflow or invalid_datetime_format or numeric_value_out_of_range then
    return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', jsonb_build_array('a value has the wrong type: ' || sqlerrm));
  end;
  if v_id is not null then
    if e.updated_at is distinct from p_expected_updated_at then return jsonb_build_object('ok', false, 'error', 'stale', 'event', to_jsonb(e)); end if;
    if e.kind = 'launch_cards' then return jsonb_build_object('ok', false, 'error', 'locked', 'errors', jsonb_build_array('the launch event is set in settings.launch_event_cards')); end if;
    if e.status in ('ended', 'cancelled') then return jsonb_build_object('ok', false, 'error', 'locked', 'errors', jsonb_build_array(format('an event that is %s cannot change', e.status))); end if;
    if e.status = 'scheduled' and (c.key is distinct from e.key or c.kind is distinct from e.kind) then
      return jsonb_build_object('ok', false, 'error', 'locked', 'errors', jsonb_build_array('the key and the kind change only in a draft'));
    end if;
    if e.status = 'live' and (c.key, c.kind, c.starts_at, c.audience, c.rewards, c.rules) is distinct from (e.key, e.kind, e.starts_at, e.audience, e.rewards, e.rules) then
      return jsonb_build_object('ok', false, 'error', 'locked', 'errors', jsonb_build_array('a live event changes only its title, description and end'));
    end if;
    if e.status = 'live' and c.ends_at is distinct from e.ends_at and c.ends_at <= now() then
      return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', jsonb_build_array('the end of a live event must be after now (use End now)'));
    end if;
  end if;
  if c.kind = 'launch_cards' then return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', jsonb_build_array('kind launch_cards is only the migrated launch event')); end if;
  v_errors := event_row_errors(c);
  if cardinality(v_errors) > 0 then return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', to_jsonb(v_errors)); end if;

  perform set_config('events.actor', p_actor, true);
  if v_id is null then
    insert into events (key, kind, title, description, status, starts_at, ends_at, audience, rewards, rules, created_by)
      values (c.key, c.kind, trim(c.title), c.description, 'draft', c.starts_at, c.ends_at, c.audience, c.rewards, c.rules, p_actor)
      returning * into c;
  else
    update events set key = c.key, kind = c.kind, title = trim(c.title), description = c.description, starts_at = c.starts_at, ends_at = c.ends_at,
                      audience = c.audience, rewards = c.rewards, rules = c.rules
     where id = v_id returning * into c;
  end if;
  perform set_config('events.actor', '', true);
  perform admin_log_action(p_actor, case when v_id is null then 'event_create' else 'event_edit' end, 'event', c.id::text,
    case when v_id is null then null else to_jsonb(e) end, to_jsonb(c), p_reason, 'studio');
  return jsonb_build_object('ok', true, 'event', to_jsonb(c));
end $function$;
-- @grants public.admin_event_save(jsonb, timestamp with time zone, text, text)
grant execute on function public.admin_event_save(jsonb, timestamp with time zone, text, text) to postgres;
grant execute on function public.admin_event_save(jsonb, timestamp with time zone, text, text) to service_role;
