-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_hunt(bigint)
-- md5: b56759ee96acf343cb4cb2ef038a1e23   (md5(replace(pg_get_functiondef('public.admin_hunt(bigint)'::regprocedure), chr(13), '')))
-- owner: supabase_admin
CREATE OR REPLACE FUNCTION public.admin_hunt(p_hunt bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare h hunts; v jsonb;
begin
  select * into h from hunts where id = p_hunt;
  if not found then return jsonb_build_object('found', false, 'hunt', p_hunt); end if;
  with m as (select player_id, sum(damage) dmg from hunt_hits where hunt_id = p_hunt group by 1),
  rk as (select m.*, row_number() over (order by dmg desc, player_id) rk from m),
  tot as (select coalesce(sum(dmg), 0) d, count(*) n from m),
  rec as (select * from hunt_damage_reconcile(p_hunt))
  select jsonb_build_object('found', true,
    'hunt', to_jsonb(h),
    'hp_dealt', h.hp_max - h.hp_remaining,
    'fighters', (select n from tot), 'damage', (select d from tot),
    'attacks', (select count(*) from hunt_combat_log where hunt_id = p_hunt),
    'supports', (select count(*) from combat_actions where mode = 'hunt' and ref_id = p_hunt and kind = 'support'),
    'squads', (select count(*) from hunt_squads where hunt_id = p_hunt),
    'by_day', (select coalesce(jsonb_agg(jsonb_build_object('day', d, 'fighters', f, 'damage', s) order by d), '[]')
                 from (select hit_date d, count(distinct player_id) f, sum(damage) s from hunt_hits where hunt_id = p_hunt group by 1) x),
    'rank_buckets', (select coalesce(jsonb_agg(jsonb_build_object('ranks', b, 'members', n, 'damage', s,
                        'share', case when (select d from tot) > 0 then round(s::numeric / (select d from tot), 4) end) order by o), '[]')
                       from (select case when rk = 1 then '1' when rk <= 3 then '2-3' when rk <= 10 then '4-10' when rk <= 25 then '11-25' else '26+' end b,
                                    min(rk) o, count(*) n, sum(dmg) s from rk group by 1) x),
    'damage_buckets', (select coalesce(jsonb_agg(jsonb_build_object('damage_from', lo, 'members', n, 'damage', s) order by lo), '[]')
                         from (select case when dmg < 1000 then 0 when dmg < 5000 then 1000 when dmg < 20000 then 5000 when dmg < 50000 then 20000 else 50000 end lo,
                                      count(*) n, sum(dmg) s from m group by 1) x),
    'top_share', case when (select d from tot) > 0 then round((select max(dmg) from m)::numeric / (select d from tot), 4) end,
    'top3_share', case when (select d from tot) > 0 then round((select coalesce(sum(dmg), 0) from rk where rk <= 3)::numeric / (select d from tot), 4) end,
    'prizes', jsonb_build_object('members', (select count(distinct player_id) from pack_ledger where reason = 'hunt_reward' and ref_kind = 'hunt' and ref_id = p_hunt::text),
                                 'packs', (select coalesce(sum(amount), 0) from pack_ledger where reason = 'hunt_reward' and ref_kind = 'hunt' and ref_id = p_hunt::text)),
    'reconcile', jsonb_build_object('members', (select count(*) from rec), 'members_unexplained', (select count(*) from rec where unexplained <> 0),
        'hits', (select coalesce(sum(hits), 0) from rec), 'logged', (select coalesce(sum(logged), 0) from rec), 'smite', (select coalesce(sum(smite), 0) from rec),
        'crasher', (select coalesce(sum(crasher), 0) from rec), 'adjusted', (select coalesce(sum(adjusted), 0) from rec),
        'unexplained', (select coalesce(sum(unexplained), 0) from rec), 'ok', not exists (select 1 from rec where unexplained <> 0)))
  into v;
  return v;
end $function$;
-- @grants public.admin_hunt(bigint)
grant execute on function public.admin_hunt(bigint) to postgres;
grant execute on function public.admin_hunt(bigint) to service_role;
grant execute on function public.admin_hunt(bigint) to supabase_admin;
