-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_event(bigint)
-- md5: 9d112e729dfdd6188e76bfc210686d19   (md5(replace(pg_get_functiondef('public.admin_event(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_event(p_id bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select case when e.id is null then jsonb_build_object('found', false) else jsonb_build_object('found', true,
    'event', to_jsonb(e),
    'editable', case when e.kind = 'launch_cards' then 'none' when e.status in ('draft', 'scheduled') then 'all' when e.status = 'live' then 'text_and_end' else 'none' end,
    'payouts', (select coalesce(jsonb_agg(to_jsonb(p) - 'event_id' order by p.paid_at, p.period), '[]') from event_payouts p where p.event_id = e.id),
    'claims', (select jsonb_build_object('gifts', count(*), 'claimed', count(g.claimed_at), 'members', count(distinct g.player_id),
                 'packs', coalesce(sum(g.amount) filter (where g.kind <> 'card'), 0), 'packs_claimed', coalesce(sum(g.amount) filter (where g.kind <> 'card' and g.claimed_at is not null), 0),
                 'shards', coalesce(sum(g.shards), 0), 'shards_claimed', coalesce(sum(g.shards) filter (where g.claimed_at is not null), 0),
                 'cards', count(*) filter (where g.kind = 'card'), 'cards_claimed', count(g.claimed_at) filter (where g.kind = 'card'))
                 from gift_claims g where g.event_id = e.id),
    'cards', (select coalesce(jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name, 'rarity', c.rarity) order by c.id), '[]') from cards c
               where c.event_id = e.id or c.id in (select (e.rewards->'per_member'->>'card_id')::bigint
                                                    union select (t->>'card_id')::bigint from jsonb_array_elements(coalesce(e.rewards->'ranks', '[]')) t)),
    'log', (select coalesce(jsonb_agg(to_jsonb(l) - 'event_id' order by l.id desc), '[]') from (select * from event_log where event_id = e.id order by id desc limit 100) l)) end
  from (select 1) one left join events e on e.id = p_id;
$function$;
-- @grants public.admin_event(bigint)
grant execute on function public.admin_event(bigint) to postgres;
grant execute on function public.admin_event(bigint) to service_role;
