-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_log_action(text, text, text, text, jsonb, jsonb, text, text, bigint)
-- md5: 94ae7d1d3639703623fe35ca92e3ba70   (md5(replace(pg_get_functiondef('public.admin_log_action(text, text, text, text, jsonb, jsonb, text, text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_log_action(p_actor text, p_action text, p_target_kind text, p_target_id text, p_before jsonb, p_after jsonb, p_reason text, p_source text DEFAULT 'studio'::text, p_undo_of bigint DEFAULT NULL::bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_id bigint;
begin
  insert into admin_actions (actor, action, target_kind, target_id, before, after, reason, source, undo_of)
    values (p_actor, p_action, p_target_kind, p_target_id, p_before, p_after, p_reason, coalesce(p_source, 'studio'), p_undo_of)
    returning id into v_id;
  return v_id;
end $function$;
-- @grants public.admin_log_action(text, text, text, text, jsonb, jsonb, text, text, bigint)
grant execute on function public.admin_log_action(text, text, text, text, jsonb, jsonb, text, text, bigint) to postgres;
grant execute on function public.admin_log_action(text, text, text, text, jsonb, jsonb, text, text, bigint) to service_role;
