-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_stale(text, jsonb, jsonb)
-- md5: a4754080fb016e9079b5e7246a63b7ca   (md5(replace(pg_get_functiondef('public.admin_stale(text, jsonb, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_stale(p_what text, p_now jsonb, p_expected jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  raise exception using errcode = 'LP409',
    message = format('admin: %s changed (now %s, expected %s). Preview the change again.', p_what, coalesce(p_now::text, 'nothing'), coalesce(p_expected::text, 'nothing'));
end $function$;
-- @grants public.admin_stale(text, jsonb, jsonb)
grant execute on function public.admin_stale(text, jsonb, jsonb) to postgres;
grant execute on function public.admin_stale(text, jsonb, jsonb) to service_role;
