-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_write_begin(text, text)
-- md5: 2ceb9f3859d59d7ebf53c89072b494ad   (md5(replace(pg_get_functiondef('public.admin_write_begin(text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_write_begin(p_actor text, p_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if p_actor is null or length(btrim(p_actor)) = 0 then
    raise exception using errcode = 'LP400', message = 'admin: the actor is required';
  end if;
  if p_reason is null or length(btrim(p_reason)) < 3 or length(p_reason) > 500 then
    raise exception using errcode = 'LP400', message = 'admin: a reason of 3 to 500 characters is required';
  end if;
  perform set_config('balance.by', p_actor, true);
end $function$;
-- @grants public.admin_write_begin(text, text)
grant execute on function public.admin_write_begin(text, text) to postgres;
grant execute on function public.admin_write_begin(text, text) to service_role;
