-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_feed(text[], timestamp with time zone, integer, text)
-- md5: 72be60a92ad9ec952ed5094cce12aa1e   (md5(replace(pg_get_functiondef('public.admin_feed(text[], timestamp with time zone, integer, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_feed(p_kinds text[] DEFAULT NULL::text[], p_before timestamp with time zone DEFAULT NULL::timestamp with time zone, p_limit integer DEFAULT 50, p_before_key text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  v_lim int := least(greatest(coalesce(p_limit, 50), 1), 200);
  v_all text[] := admin_feed_kinds();
  v_k text[] := case when p_kinds is null or cardinality(p_kinds) = 0 then admin_feed_kinds() else p_kinds end;
  v_bad text[];
  v jsonb;
begin
  select array_agg(k order by k) into v_bad from unnest(v_k) k where not k = any (v_all);
  if v_bad is not null then raise exception 'admin_feed: unknown kind % (see admin_feed_kinds)', array_to_string(v_bad, ', '); end if;
  with ev(at, key, kind, text, player_id, other_id, actor, amount, ref) as (
    select a.at, 'admin:' || a.id, 'admin', 'Admin ' || a.action || coalesce(' on ' || a.target_kind || coalesce(' ' || a.target_id, ''), '') || coalesce(': ' || nullif(a.reason, ''), ''),
           case when a.target_kind in ('player', 'member') then a.target_id end, null::text, a.actor || ' (' || a.source || ')', null::numeric, 'admin_action:' || a.id
      from admin_actions a where 'admin' = any (v_k)
    union all
    select s.changed_at, 'settings:' || s.id, 'settings', 'Setting ' || s.key || ' ' || s.op, null, null, s.changed_by, null, 'settings_log:' || s.id
      from settings_log s where 'settings' = any (v_k)
    union all
    select b.changed_at, 'balance:' || b.id, 'balance', 'Balance ' || b.key || ' ' || b.op, null, null, b.changed_by, null, 'balance_log:' || b.id
      from balance_log b where 'balance' = any (v_k)
    union all
    select p.created_at, 'member_new:' || p.id, 'member', 'New member', p.id, null, null, null, null from players p where 'member' = any (v_k)
    union all
    select p.left_guild_at, 'member_left:' || p.id, 'member', 'Left the Discord server', p.id, null, null, null, null
      from players p where 'member' = any (v_k) and p.left_guild_at is not null
    union all
    -- a big pull: a Secret Rare or rarer from a pack (rarity_rank 2 or more)
    select c.created_at, 'pull:' || c.id, 'pull', 'Pulled ' || initcap(replace(k.rarity::text, '_', ' ')) || ': ' || k.name, c.player_id, null, null, null, 'card:' || k.id
      from card_ledger c join cards k on k.id = c.card_id
     where 'pull' = any (v_k) and c.reason = 'pack' and c.amount > 0 and rarity_rank(k.rarity::text) >= 2
    union all
    select t.created_at, 'trade:' || t.id, 'trade', 'Trade (' || t.kind || '): ' || cardinality(t.from_cards) || ' for ' || cardinality(t.to_cards) || ' cards',
           t.from_id, t.to_id, null, null, coalesce('trade_offer:' || t.offer_id, 'auction:' || t.auction_id)
      from card_trades t where 'trade' = any (v_k)
    union all
    select u.created_at, 'auction:' || u.id, 'auction', 'Auction started: ' || coalesce(k.name, 'card ' || u.card_id), u.seller_id, null, null, null, 'auction:' || u.id
      from auctions u left join cards k on k.id = u.card_id where 'auction' = any (v_k)
    union all
    select u.settled_at, 'auction_end:' || u.id, 'auction', 'Auction ' || u.status || ': ' || coalesce(k.name, 'card ' || u.card_id), u.seller_id,
           (select b.bidder_id from auction_bids b where b.id = u.accepted_bid_id), null, null, 'auction:' || u.id
      from auctions u left join cards k on k.id = u.card_id where 'auction' = any (v_k) and u.settled_at is not null
    union all
    select h.opens_at, 'hunt_open:' || h.id, 'hunt', 'Boss spawned: ' || h.name || ' (' || h.tier || ')', null, null, null, h.hp_max, 'hunt:' || h.id
      from hunts h where 'hunt' = any (v_k) and h.opens_at <= now()
    union all
    select h.defeated_at, 'hunt_kill:' || h.id, 'hunt', 'Boss defeated: ' || h.name, null, null, null, null, 'hunt:' || h.id
      from hunts h where 'hunt' = any (v_k) and h.defeated_at is not null
    union all
    select h.settled_at, 'hunt_end:' || h.id, 'hunt', 'Hunt settled: ' || h.name || ' (' || h.status || ')', null, null, null, null, 'hunt:' || h.id
      from hunts h where 'hunt' = any (v_k) and h.settled_at is not null
    union all
    select r.ended_at, 'run_clear:' || r.id, 'dungeon', initcap(r.mode) || ' cleared (floor ' || r.floor || ')', r.player_id, null, null, r.shards, 'dungeon_run:' || r.id
      from dungeon_runs r where 'dungeon' = any (v_k) and r.ended_by = 'cleared' and r.ended_at is not null
    union all
    select p.paid_at, 'board:' || p.mode || ':' || p.period, 'dungeon',
           case when p.mode = 'daily' then 'Dungeon' else 'Gauntlet' end || ' board paid (' || p.period || '), winners: ' || jsonb_array_length(p.winners),
           null, null, null, null, 'dungeon_payout:' || p.mode || ':' || p.period
      from dungeon_payouts p where 'dungeon' = any (v_k)
    union all
    select e.created_at, 'play:' || e.id, 'effect', 'Played ' || e.primitive || ' (' || e.kind || '): ' || e.outcome, e.player_id,
           case when e.target_id <> e.player_id then e.target_id end, null, e.amount, 'card_play:' || e.id
      from card_plays e where 'effect' = any (v_k)
    union all
    select r.created_at, 'report:' || r.id, 'report', 'Report: ' || r.kind || coalesce(' (issue ' || r.issue_number || ')', ''), r.player_id, r.target_id, null, null,
           'player_report:' || r.id
      from player_reports r where 'report' = any (v_k)
  ),
  page as (
    select * from ev
     where ev.at is not null and (p_before is null or ev.at < p_before or (ev.at = p_before and p_before_key is not null and ev.key < p_before_key))
     order by ev.at desc, ev.key desc
     limit v_lim)
  select jsonb_build_object(
    'kinds', to_jsonb(v_k),
    'rows', coalesce((select jsonb_agg(jsonb_build_object('at', pg.at, 'key', pg.key, 'kind', pg.kind, 'text', pg.text,
        'player_id', pg.player_id, 'username', (select p.username from players p where p.id = pg.player_id),
        'other_id', pg.other_id, 'other_name', (select p.username from players p where p.id = pg.other_id),
        'actor', pg.actor, 'amount', pg.amount, 'ref', pg.ref) order by pg.at desc, pg.key desc) from page pg), '[]'),
    'next', (select jsonb_build_object('before', at, 'before_key', key) from (select * from page order by at, key limit 1) l
              where (select count(*) from page) = v_lim))
  into v;
  return v;
end $function$;
-- @grants public.admin_feed(text[], timestamp with time zone, integer, text)
grant execute on function public.admin_feed(text[], timestamp with time zone, integer, text) to postgres;
grant execute on function public.admin_feed(text[], timestamp with time zone, integer, text) to service_role;
