-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_member_shards(text, text, integer, integer, text, bigint)
-- md5: ce4440de3da54a878020993a1865417d   (md5(replace(pg_get_functiondef('public.admin_member_shards(text, text, integer, integer, text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_member_shards(p_actor text, p_player text, p_amount integer, p_before integer, p_reason text, p_undo_of bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_bal int; v_new int; v_id bigint;
begin
  perform admin_write_begin(p_actor, p_reason);
  if p_amount is null or p_amount = 0 or abs(p_amount) > 1000000 then
    raise exception using errcode = 'LP400', message = 'admin: the Shards change must be a whole number from -1000000 to 1000000, not 0';
  end if;
  select shard_balance into v_bal from players where id = p_player for update;
  if not found then raise exception using errcode = 'LP400', message = 'admin: no member with this id'; end if;
  if v_bal is distinct from p_before then perform admin_stale('the Shards balance', to_jsonb(v_bal), to_jsonb(p_before)); end if;
  if v_bal + p_amount < 0 then raise exception using errcode = 'LP400', message = format('admin: the member has %s Shards; the balance cannot go below 0', v_bal); end if;
  v_id := admin_log_action(p_actor, 'member_shards', 'player', p_player, jsonb_build_object('shards', v_bal),
    jsonb_build_object('shards', v_bal + p_amount, 'amount', p_amount), p_reason, 'studio', p_undo_of);
  v_new := grant_shards(p_player, p_amount, 'admin', 'admin_action', v_id::text);
  if v_new is distinct from v_bal + p_amount then raise exception 'admin: grant_shards returned % (expected %)', v_new, v_bal + p_amount; end if;
  return jsonb_build_object('action_id', v_id, 'player', p_player, 'before', v_bal, 'after', v_new, 'amount', p_amount);
end $function$;
-- @grants public.admin_member_shards(text, text, integer, integer, text, bigint)
grant execute on function public.admin_member_shards(text, text, integer, integer, text, bigint) to postgres;
grant execute on function public.admin_member_shards(text, text, integer, integer, text, bigint) to service_role;
