-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_hunts(integer, integer)
-- md5: 2b1df9d47c6c9a4e63658824d9d22c3b   (md5(replace(pg_get_functiondef('public.admin_hunts(integer, integer)'::regprocedure), chr(13), '')))
-- owner: supabase_admin
CREATE OR REPLACE FUNCTION public.admin_hunts(p_limit integer DEFAULT 20, p_offset integer DEFAULT 0)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with h as (select * from hunts order by id desc limit least(greatest(coalesce(p_limit, 20), 1), 100) offset greatest(coalesce(p_offset, 0), 0))
  select jsonb_build_object('total', (select count(*) from hunts), 'rows', coalesce(jsonb_agg(jsonb_build_object(
      'id', h.id, 'name', h.name, 'tier', h.tier, 'status', h.status, 'hp_max', h.hp_max, 'hp_remaining', h.hp_remaining,
      'opens_at', h.opens_at, 'closes_at', h.closes_at, 'defeated_at', h.defeated_at, 'settled_at', h.settled_at,
      'fighters', (select count(distinct player_id) from hunt_hits x where x.hunt_id = h.id),
      'damage', (select coalesce(sum(damage), 0) from hunt_hits x where x.hunt_id = h.id),
      'attacks', (select count(*) from hunt_combat_log x where x.hunt_id = h.id),
      'prize_packs', (select coalesce(sum(amount), 0) from pack_ledger l where l.reason = 'hunt_reward' and l.ref_kind = 'hunt' and l.ref_id = h.id::text)) order by h.id desc), '[]'))
  from h;
$function$;
-- @grants public.admin_hunts(integer, integer)
grant execute on function public.admin_hunts(integer, integer) to postgres;
grant execute on function public.admin_hunts(integer, integer) to service_role;
grant execute on function public.admin_hunts(integer, integer) to supabase_admin;
