-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_member_timeline(text, timestamp with time zone, integer, text)
-- md5: 54583380534b9a2d21752513d73b5546   (md5(replace(pg_get_functiondef('public.admin_member_timeline(text, timestamp with time zone, integer, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_member_timeline(p_player text, p_before timestamp with time zone DEFAULT NULL::timestamp with time zone, p_limit integer DEFAULT 50, p_before_key text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with ev(at, key, kind, text, amount, ref) as (
    select p.created_at, 'joined:' || p.id, 'joined', 'Joined (first seen by the bot, the Activity or a gift)', null::numeric, null::text
      from players p where p.id = p_player
    union all
    select min(l.created_at), 'pack:' || min(l.id), 'pack', l.reason || case when count(*) > 1 then ' (' || count(*) || ' rows)' else '' end, sum(l.amount),
           l.ref_kind || ':' || l.ref_id
      from pack_ledger l where l.player_id = p_player group by l.reason, l.ref_kind, l.ref_id, l.created_at
    union all
    select min(c.created_at), 'card:' || min(c.id), 'card', c.reason || ': ' || string_agg(distinct k.rarity::text, ', ') || ' (' || count(*) || ' cards)', sum(c.amount),
           c.ref_kind || ':' || c.ref_id
      from card_ledger c join cards k on k.id = c.card_id where c.player_id = p_player group by c.reason, c.ref_kind, c.ref_id, c.created_at
    union all
    select s.created_at, 'shard:' || s.id, 'shard', s.reason, s.amount, s.ref_kind || ':' || s.ref_id from shard_ledger s where s.player_id = p_player
    union all
    select d.created_at, 'daily:' || d.day || ':' || d.task, 'daily', 'Daily ' || d.task || ' claimed', d.amount, 'daily_claim:' || d.day || ':' || d.task
      from daily_claims d where d.player_id = p_player
    union all
    select g.created_at, 'gift_in:' || g.id, 'gift', 'Gift in the bell: ' || g.title || case when g.from_id is not null then ' (from a member)' else '' end,
           case when g.kind = 'card' then 1 else g.amount end, 'gift:' || g.id
      from gift_claims g where g.player_id = p_player
    union all
    select g.claimed_at, 'gift_claim:' || g.id, 'gift_claim', 'Gift claimed: ' || g.title, case when g.kind = 'card' then 1 else g.amount end, 'gift:' || g.id
      from gift_claims g where g.player_id = p_player and g.claimed_at is not null
    union all
    select max(h.ts), 'hunt:' || h.hunt_id || ':' || game_day(h.ts), 'hunt', 'Hunt ' || h.hunt_id || ': ' || count(*) || ' attacks', sum(h.damage), 'hunt:' || h.hunt_id
      from hunt_combat_log h where h.player_id = p_player group by h.hunt_id, game_day(h.ts)
    union all
    select a.created_at, 'combat:' || a.id, 'combat', a.kind || ' ' || coalesce(a.effect, '') || ' (' || a.mode || ' ' || a.ref_id || ')',
           (a.result->>'value')::numeric, a.mode || ':' || a.ref_id
      from combat_actions a where a.player_id = p_player
    union all
    select s.locked_at, 'squad:' || s.hunt_id || ':' || s.hit_date, 'squad', 'Hunt squad locked: ' || cardinality(s.card_ids) || ' cards', null, 'hunt:' || s.hunt_id
      from hunt_squads s where s.player_id = p_player
    union all
    select j.created_at, 'hunt_adj:' || j.id, 'hunt_adjustment', 'Hunt damage changed by an admin: ' || j.reason, j.damage, 'hunt:' || j.hunt_id
      from hunt_adjustments j where j.player_id = p_player
    union all
    select r.started_at, 'run:' || r.id, 'dungeon', initcap(r.mode) || ' run started', null, 'dungeon_run:' || r.id from dungeon_runs r where r.player_id = p_player
    union all
    select r.ended_at, 'run_end:' || r.id, 'dungeon_over', initcap(r.mode) || ' run ended (' || coalesce(r.ended_by, '?') || ', floor ' || r.floor || ', room ' || r.room || ')', r.shards,
           'dungeon_run:' || r.id
      from dungeon_runs r where r.player_id = p_player and r.ended_at is not null
    union all
    select e.created_at, 'play:' || e.id, 'effect_sent', 'Played ' || e.primitive || ' (' || e.kind || ') on ' || case when e.target_id = e.player_id then 'self' else 'a member' end || ': ' || e.outcome,
           e.amount, 'card_play:' || e.id
      from card_plays e where e.player_id = p_player
    union all
    select e.created_at, 'played_on:' || e.id, 'effect_received', 'Got ' || e.primitive || ' (' || e.kind || '): ' || e.outcome, e.amount, 'card_play:' || e.id
      from card_plays e where e.target_id = p_player and e.player_id <> p_player
    union all
    select o.created_at, 'offer:' || o.id, 'trade', case when o.from_id = p_player then 'Trade offer made' else 'Trade offer received' end, null, 'trade_offer:' || o.id
      from trade_offers o where o.from_id = p_player or o.to_id = p_player
    union all
    select o.countered_at, 'offer_counter:' || o.id, 'trade', 'Trade offer countered', null, 'trade_offer:' || o.id
      from trade_offers o where (o.from_id = p_player or o.to_id = p_player) and o.countered_at is not null
    union all
    select o.resolved_at, 'offer_end:' || o.id, 'trade', 'Trade offer ' || o.status, null, 'trade_offer:' || o.id
      from trade_offers o where (o.from_id = p_player or o.to_id = p_player) and o.resolved_at is not null
    union all
    select l.created_at, 'listing:' || l.id, 'trade', 'Card listed in the Trading Hall', null, 'trade_listing:' || l.id from trade_listings l where l.player_id = p_player
    union all
    select u.created_at, 'auction:' || u.id, 'auction', 'Auction started', null, 'auction:' || u.id from auctions u where u.seller_id = p_player
    union all
    select u.settled_at, 'auction_end:' || u.id, 'auction', 'Auction ' || u.status, null, 'auction:' || u.id from auctions u where u.seller_id = p_player and u.settled_at is not null
    union all
    select b.created_at, 'bid:' || b.id, 'auction', 'Bid placed (' || cardinality(b.cards) || ' cards), now ' || b.status, null, 'auction:' || b.auction_id
      from auction_bids b where b.bidder_id = p_player
    union all
    select s.created_at, 'shop:' || s.id, 'shop', 'Shop: ' || s.kind || case when s.qty > 1 then ' x' || s.qty else '' end, -s.price, 'shop_purchase:' || s.id
      from shop_purchases s where s.player_id = p_player
    union all
    select a.claimed_at, 'ach:' || a.key, 'achievement', 'Achievement claimed: ' || a.key, a.packs, 'achievement:' || a.key from achievement_claims a where a.player_id = p_player
    union all
    select r.created_at, 'report:' || r.id, 'report', 'Report sent: ' || r.kind, null, 'player_report:' || r.id from player_reports r where r.player_id = p_player
    union all
    select n.created_at, 'note:' || n.id, 'note', 'Bell note: ' || n.kind, null, 'notification:' || n.id from notifications n where n.player_id = p_player
    union all
    select game_day_start(d.activity_date), 'chat:' || d.activity_date, 'chat', 'Chat messages that day', d.message_count, null
      from daily_activity d where d.player_id = p_player and d.message_count > 0
    union all
    select game_day_start(v.day), 'voice:' || v.day, 'voice', 'Voice minutes that day', v.minutes, null from voice_minutes v where v.player_id = p_player and v.minutes > 0
  ),
  page as (
    select * from ev
     where p_before is null or ev.at < p_before or (ev.at = p_before and p_before_key is not null and ev.key < p_before_key)
     order by ev.at desc, ev.key desc
     limit least(greatest(coalesce(p_limit, 50), 1), 200))
  select jsonb_build_object(
    'player', p_player,
    'rows', coalesce((select jsonb_agg(jsonb_build_object('at', at, 'key', key, 'kind', kind, 'text', text, 'amount', amount, 'ref', ref) order by at desc, key desc) from page), '[]'),
    'next', (select jsonb_build_object('before', at, 'before_key', key) from (select * from page order by at, key limit 1) l
              where (select count(*) from page) = least(greatest(coalesce(p_limit, 50), 1), 200)));
$function$;
-- @grants public.admin_member_timeline(text, timestamp with time zone, integer, text)
grant execute on function public.admin_member_timeline(text, timestamp with time zone, integer, text) to postgres;
grant execute on function public.admin_member_timeline(text, timestamp with time zone, integer, text) to service_role;
