-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_feed_kinds()
-- md5: f7615ce97ece711d644d449666867785   (md5(replace(pg_get_functiondef('public.admin_feed_kinds()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_feed_kinds()
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select array['admin', 'settings', 'balance', 'member', 'pull', 'trade', 'auction', 'hunt', 'dungeon', 'effect', 'report']::text[];
$function$;
-- @grants public.admin_feed_kinds()
grant execute on function public.admin_feed_kinds() to postgres;
grant execute on function public.admin_feed_kinds() to service_role;
