-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_economy(date, date, text)
-- md5: ad117d79a4626d25ae0075541eb09b4e   (md5(replace(pg_get_functiondef('public.admin_economy(date, date, text)'::regprocedure), chr(13), '')))
-- owner: supabase_admin
CREATE OR REPLACE FUNCTION public.admin_economy(p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date, p_bucket text DEFAULT 'day'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  pr jsonb := admin_period(p_from, p_to, 30);
  d0 date := (pr->>'from')::date; d1 date := (pr->>'to')::date;
  t0 timestamptz := (pr->>'t0')::timestamptz; t1 timestamptz := (pr->>'t1')::timestamptz;
  v jsonb;
begin
  if p_bucket not in ('day', 'week') then raise exception 'admin_economy: p_bucket must be day or week, not %', p_bucket; end if;
  with
  rows_all as (
    select 'pack' as ledger, l.created_at, l.reason, l.amount from pack_ledger l where l.created_at >= t0 and l.created_at < t1
    union all select 'card', c.created_at, c.reason, c.amount from card_ledger c where c.created_at >= t0 and c.created_at < t1
    union all select 'shard', s.created_at, s.reason, s.amount from shard_ledger s where s.created_at >= t0 and s.created_at < t1),
  bk as (select ledger, case when p_bucket = 'week' then date_trunc('week', game_day(created_at))::date else game_day(created_at) end as t, reason, amount from rows_all),
  buckets as (select distinct case when p_bucket = 'week' then date_trunc('week', x)::date else x::date end as t
                from generate_series(d0, d1, interval '1 day') x),
  by_reason as (select ledger, t, reason, count(*) n, coalesce(sum(amount) filter (where amount > 0), 0) i, coalesce(-sum(amount) filter (where amount < 0), 0) o
                  from bk group by 1, 2, 3),
  net as (select b.t, l.ledger,
                 coalesce((select sum(amount) from bk where bk.ledger = l.ledger and bk.t = b.t), 0) as net,
                 coalesce((select sum(amount) from bk where bk.ledger = l.ledger and bk.t = b.t and amount > 0 and reason not in ('gift_received')), 0) as earned,
                 coalesce((select -sum(amount) from bk where bk.ledger = l.ledger and bk.t = b.t and amount < 0 and reason not in ('gift_sent')), 0) as used
            from buckets b cross join (values ('pack'), ('card'), ('shard')) l(ledger)),
  base as (select (select coalesce(sum(amount), 0) from pack_ledger where created_at < t0) as pack,
                  (select coalesce(sum(amount), 0) from card_ledger where created_at < t0) as card,
                  (select coalesce(sum(amount), 0) from shard_ledger where created_at < t0) as shard)
  select jsonb_build_object(
    'period', pr - 't0' - 't1', 'bucket', p_bucket,
    'series', jsonb_build_object(
      'pack', (select coalesce(jsonb_agg(jsonb_build_object('t', t, 'reason', reason, 'rows', n, 'in', i, 'out', o) order by t, reason), '[]') from by_reason where ledger = 'pack'),
      'card', (select coalesce(jsonb_agg(jsonb_build_object('t', t, 'reason', reason, 'rows', n, 'in', i, 'out', o) order by t, reason), '[]') from by_reason where ledger = 'card'),
      'shard', (select coalesce(jsonb_agg(jsonb_build_object('t', t, 'reason', reason, 'rows', n, 'in', i, 'out', o) order by t, reason), '[]') from by_reason where ledger = 'shard')),
    'supply', (select coalesce(jsonb_agg(jsonb_build_object('t', s.t, 'packs_held', s.packs, 'copies_held', s.copies, 'shards_held', s.shards) order by s.t), '[]')
                 from (select n.t,
                              (select pack from base) + (select coalesce(sum(n2.net), 0) from net n2 where n2.ledger = 'pack' and n2.t <= n.t) as packs,
                              (select card from base) + (select coalesce(sum(n2.net), 0) from net n2 where n2.ledger = 'card' and n2.t <= n.t) as copies,
                              (select shard from base) + (select coalesce(sum(n2.net), 0) from net n2 where n2.ledger = 'shard' and n2.t <= n.t) as shards
                         from (select distinct t from net) n) s),
    'ratios', (select coalesce(jsonb_agg(jsonb_build_object('t', p.t,
                   'packs_earned', p.earned, 'packs_opened', p.used, 'open_earn', case when p.earned > 0 then round(p.used::numeric / p.earned, 4) end,
                   'shards_earned', s.earned, 'shards_spent', s.used, 'spend_earn', case when s.earned > 0 then round(s.used::numeric / s.earned, 4) end) order by p.t), '[]')
                 from net p join net s on s.t = p.t and s.ledger = 'shard' where p.ledger = 'pack'))
  into v;
  return v;
end $function$;
-- @grants public.admin_economy(date, date, text)
grant execute on function public.admin_economy(date, date, text) to postgres;
grant execute on function public.admin_economy(date, date, text) to service_role;
grant execute on function public.admin_economy(date, date, text) to supabase_admin;
