-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_event_cancel(bigint, timestamp with time zone, text, text)
-- md5: e70d48be7a1fd71231e41fc10d605a4a   (md5(replace(pg_get_functiondef('public.admin_event_cancel(bigint, timestamp with time zone, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_event_cancel(p_id bigint, p_expected_updated_at timestamp with time zone, p_actor text, p_reason text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  select admin_event_status(p_id, p_expected_updated_at, p_actor, 'cancelled', p_reason);
$function$;
-- @grants public.admin_event_cancel(bigint, timestamp with time zone, text, text)
grant execute on function public.admin_event_cancel(bigint, timestamp with time zone, text, text) to postgres;
grant execute on function public.admin_event_cancel(bigint, timestamp with time zone, text, text) to service_role;
