-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_pulls_since()
-- md5: 4be159406a2b348327193c4ba48bc3c6   (md5(replace(pg_get_functiondef('public.admin_pulls_since()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_pulls_since()
 RETURNS timestamp with time zone
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select min(applied_at) from schema_migrations where file = 'card_ledger.sql';
$function$;
-- @grants public.admin_pulls_since()
grant execute on function public.admin_pulls_since() to postgres;
grant execute on function public.admin_pulls_since() to service_role;
