-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_event_schedule(bigint, timestamp with time zone, text, boolean)
-- md5: 2e04548fa717b63635ffb0ebd4d28514   (md5(replace(pg_get_functiondef('public.admin_event_schedule(bigint, timestamp with time zone, text, boolean)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_event_schedule(p_id bigint, p_expected_updated_at timestamp with time zone, p_actor text, p_on boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  select admin_event_status(p_id, p_expected_updated_at, p_actor, case when p_on then 'scheduled' else 'draft' end, null);
$function$;
-- @grants public.admin_event_schedule(bigint, timestamp with time zone, text, boolean)
grant execute on function public.admin_event_schedule(bigint, timestamp with time zone, text, boolean) to postgres;
grant execute on function public.admin_event_schedule(bigint, timestamp with time zone, text, boolean) to service_role;
