-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_health()
-- md5: 0869fe0233d1562e3696d3fc46350cb2   (md5(replace(pg_get_functiondef('public.admin_health()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_health()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_cron jsonb := null; v jsonb;
begin
  if to_regclass('cron.job') is not null and to_regclass('cron.job_run_details') is not null then
    execute $q$
      select coalesce(jsonb_agg(jsonb_build_object('job', j.jobname, 'schedule', j.schedule, 'active', j.active, 'last_status', r.status,
               'last_start', r.start_time, 'last_end', r.end_time, 'last_message', left(r.return_message, 160),
               'failed_7d', (select count(*) from cron.job_run_details f where f.jobid = j.jobid and f.status = 'failed' and f.start_time > now() - interval '7 days'))
             order by j.jobname), '[]')
        from cron.job j left join lateral (select * from cron.job_run_details d where d.jobid = j.jobid order by d.start_time desc limit 1) r on true $q$
      into v_cron;
  end if;
  select jsonb_build_object(
    'at', now(),
    'reconcile', jsonb_build_object(
        'pack', pack_ledger_reconcile() - 'mismatched_rows', 'card', card_ledger_reconcile() - 'mismatched_rows',
        'shard', shard_ledger_reconcile() - 'mismatched_rows' - 'mismatched_runs'),
    'reconcile_detail_counts', jsonb_build_object(
        'pack_mismatched_rows', jsonb_array_length(coalesce(pack_ledger_reconcile()->'mismatched_rows', '[]')),
        'shard_mismatched_rows', jsonb_array_length(coalesce(shard_ledger_reconcile()->'mismatched_rows', '[]'))),
    'hunts', (select coalesce(jsonb_agg(x order by (x->>'hunt')::bigint desc), '[]') from (
        select jsonb_build_object('hunt', h.id, 'status', h.status,
          'members', (select count(*) from hunt_damage_reconcile(h.id)),
          'members_unexplained', (select count(*) from hunt_damage_reconcile(h.id) r where r.unexplained <> 0),
          'unexplained', (select coalesce(sum(r.unexplained), 0) from hunt_damage_reconcile(h.id) r)) x
          from (select * from hunts order by id desc limit 3) h) y),
    'refs_missing', jsonb_build_object(
        'pack_gift', (select count(*) from pack_ledger l where l.ref_kind = 'gift' and not exists (select 1 from gift_claims g where g.id::text = l.ref_id)),
        'pack_shop', (select count(*) from pack_ledger l where l.ref_kind = 'shop_purchase' and not exists (select 1 from shop_purchases s where s.id::text = l.ref_id)),
        'pack_hunt', (select count(*) from pack_ledger l where l.ref_kind = 'hunt' and not exists (select 1 from hunts h where h.id::text = l.ref_id)),
        'pack_daily', (select count(*) from pack_ledger l where l.ref_kind = 'daily_claim' and not exists
                         (select 1 from daily_claims d where d.player_id = l.player_id and d.day::text || ':' || d.task = l.ref_id)),
        'card_trade', (select count(*) from card_ledger c where c.ref_kind = 'trade_offer' and not exists (select 1 from trade_offers o where o.id::text = c.ref_id)),
        'card_auction', (select count(*) from card_ledger c where c.ref_kind = 'auction' and not exists (select 1 from auctions a where a.id::text = c.ref_id)),
        'card_gift', (select count(*) from card_ledger c where c.ref_kind = 'gift' and not exists (select 1 from gift_claims g where g.id::text = c.ref_id)),
        'card_run', (select count(*) from card_ledger c where c.ref_kind = 'dungeon_run' and not exists (select 1 from dungeon_runs r where r.id::text = c.ref_id)),
        'shard_run', (select count(*) from shard_ledger s where s.ref_kind = 'run' and not exists (select 1 from dungeon_runs r where r.id::text = s.ref_id)),
        'shard_shop', (select count(*) from shard_ledger s where s.ref_kind = 'shop_purchase' and not exists (select 1 from shop_purchases p where p.id::text = s.ref_id)),
        'shard_gift', (select count(*) from shard_ledger s where s.ref_kind = 'gift' and not exists (select 1 from gift_claims g where g.id::text = s.ref_id))),
    'rows_without_ref', jsonb_build_object(
        'pack', (select count(*) from pack_ledger where ref_kind is null or ref_id is null),
        'card', (select count(*) from card_ledger where ref_kind is null or ref_id is null),
        'shard', (select count(*) from shard_ledger where ref_kind is null or ref_id is null)),
    'queues', jsonb_build_object(
        'hunt_events_unposted', (select count(*) from hunt_events where posted_at is null and kind <> 'attack'),
        'hunt_events_oldest_unposted', (select min(created_at) from hunt_events where posted_at is null and kind <> 'attack'),
        'reports_unsynced', (select count(*) from player_reports where synced_at is null),
        'discord_effects_pending', (select count(*) from discord_effects where status = 'pending'),
        'discord_effects_failed_7d', (select count(*) from discord_effects where status = 'failed' and updated_at > now() - interval '7 days'),
        'card_plays_unposted_1h', (select count(*) from card_plays where posted_at is null and created_at < now() - interval '1 hour' and created_at > now() - interval '7 days')),
    'cron', v_cron,
    'database_bytes', pg_database_size(current_database()),
    'tables', (select coalesce(jsonb_agg(jsonb_build_object('table', relname, 'bytes', b, 'rows_estimate', n) order by b desc), '[]')
                 from (select c.relname, pg_total_relation_size(c.oid) b, greatest(c.reltuples, 0)::bigint n from pg_class c
                        where c.relnamespace = 'public'::regnamespace and c.relkind = 'r' order by 2 desc limit 25) t),
    'migrations_last', (select coalesce(jsonb_agg(jsonb_build_object('file', file, 'applied_at', applied_at) order by id desc), '[]')
                          from (select * from schema_migrations order by id desc limit 10) m),
    'balance_last', (select coalesce(jsonb_agg(jsonb_build_object('key', key, 'op', op, 'at', changed_at, 'by', changed_by) order by id desc), '[]')
                       from (select * from balance_log order by id desc limit 10) b))
  into v;
  return v;
end $function$;
-- @grants public.admin_health()
grant execute on function public.admin_health() to postgres;
grant execute on function public.admin_health() to service_role;
