-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_cards(date, date, text, integer, integer, text)
-- md5: c4af5566907ccc367b1a3e8371fd2443   (md5(replace(pg_get_functiondef('public.admin_cards(date, date, text, integer, integer, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_cards(p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date, p_sort text DEFAULT 'copies'::text, p_limit integer DEFAULT 50, p_offset integer DEFAULT 0, p_search text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  pr jsonb := admin_period(p_from, p_to, 30);
  d0 date := (pr->>'from')::date; d1 date := (pr->>'to')::date;
  t0 timestamptz := (pr->>'t0')::timestamptz; t1 timestamptz := (pr->>'t1')::timestamptz;
  v_lim int := least(greatest(coalesce(p_limit, 50), 1), 200);
  v_off int := greatest(coalesce(p_offset, 0), 0);
  v_sort text := coalesce(nullif(p_sort, ''), 'copies');
  v_q text := nullif(trim(coalesce(p_search, '')), '');
  v_like text := '%' || replace(replace(replace(coalesce(v_q, ''), '\', '\\'), '%', '\%'), '_', '\_') || '%';
  v jsonb;
begin
  if v_sort not in ('copies', 'owners', 'pulls', 'trades', 'attacks', 'damage', 'plays', 'id') then
    raise exception 'admin_cards: unknown sort % (copies, owners, pulls, trades, attacks, damage, plays, id)', p_sort;
  end if;
  with
  own as (select card_id, sum(quantity) copies, count(*) owners, sum(ascension) stars from player_cards group by 1),
  pul as (select card_id, sum(amount) n from card_ledger where reason = 'pack' and amount > 0 and created_at >= t0 and created_at < t1 group by 1),
  trd as (select x card_id, count(*) n from card_trades t, unnest(t.from_cards || t.to_cards) x where t.created_at >= t0 and t.created_at < t1 group by 1),
  atk as (select card_id, count(*) n, sum(damage) dmg from hunt_combat_log where ts >= t0 and ts < t1 group by 1),
  hit as (select h.card_id, sum(h.damage) dmg, sum(h.damage) filter (where u.status = 'defeated') dmg_won from hunt_hits h join hunts u on u.id = h.hunt_id
           where h.hit_date between d0 and d1 group by 1),
  tot as (select coalesce(sum(damage), 0) d from hunt_hits where hit_date between d0 and d1),
  sup as (select card_id, count(*) n from combat_actions where mode = 'hunt' and kind = 'support' and created_at >= t0 and created_at < t1 group by 1),
  ply as (select card_id, count(*) n from card_plays where created_at >= t0 and created_at < t1 group by 1),
  r as (
    select k.id, k.name, k.rarity::text rarity, k.subject_id, s.type, k.season, k.in_draw_pool, k.tradeable,
           coalesce(own.copies, 0) copies, coalesce(own.owners, 0) owners, coalesce(own.stars, 0) stars, coalesce(pul.n, 0) pulls,
           coalesce(trd.n, 0) trades, coalesce(atk.n, 0) attacks, coalesce(hit.dmg, 0) damage, coalesce(hit.dmg_won, 0) damage_won,
           case when (select d from tot) > 0 then round(coalesce(hit.dmg, 0)::numeric / (select d from tot), 5) else 0 end damage_share,
           coalesce(sup.n, 0) supports, coalesce(ply.n, 0) plays
      from cards k join subjects s on s.id = k.subject_id
      left join own on own.card_id = k.id left join pul on pul.card_id = k.id left join trd on trd.card_id = k.id
      left join atk on atk.card_id = k.id left join hit on hit.card_id = k.id left join sup on sup.card_id = k.id left join ply on ply.card_id = k.id
     where v_q is null or k.name ilike v_like or k.id::text = v_q),
  o as (select r.*, row_number() over (order by case v_sort when 'copies' then copies when 'owners' then owners when 'pulls' then pulls when 'trades' then trades
                       when 'attacks' then attacks when 'damage' then damage when 'plays' then plays + supports else 0 end desc, id) rn from r)
  select jsonb_build_object('period', pr - 't0' - 't1', 'total', (select count(*) from o), 'limit', v_lim, 'offset', v_off, 'sort', v_sort, 'search', v_q,
    'hunt_damage_total', (select d from tot),
    'rows', coalesce((select jsonb_agg(to_jsonb(o) - 'rn' order by o.rn) from o where o.rn > v_off and o.rn <= v_off + v_lim), '[]'))
  into v;
  return v;
end $function$;
-- @grants public.admin_cards(date, date, text, integer, integer, text)
grant execute on function public.admin_cards(date, date, text, integer, integer, text) to postgres;
grant execute on function public.admin_cards(date, date, text, integer, integer, text) to service_role;
