-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_card(bigint)
-- md5: 389b27006e56cdf5f40986bc48e6bb36   (md5(replace(pg_get_functiondef('public.admin_card(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_card(p_card bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare k cards; v jsonb;
begin
  select * into k from cards where id = p_card;
  if not found then return jsonb_build_object('found', false, 'card', p_card); end if;
  with ca as (select a.mode, a.kind, a.card_id, a.target_card, a.result from combat_actions a
               where a.mode in ('dungeon', 'gauntlet') and (a.card_id = p_card or a.target_card = p_card))
  select jsonb_build_object('found', true,
    'card', jsonb_build_object('id', k.id, 'name', k.name, 'rarity', k.rarity::text, 'source', k.source::text, 'subject_id', k.subject_id,
        'subject', (select s.name from subjects s where s.id = k.subject_id), 'type', (select s.type from subjects s where s.id = k.subject_id),
        'season', k.season, 'event', k.event, 'in_draw_pool', k.in_draw_pool, 'tradeable', k.tradeable, 'image_url', k.image_url, 'created_at', k.created_at),
    'owners', (select count(*) from player_cards where card_id = p_card and quantity > 0),
    'copies', (select coalesce(sum(quantity), 0) from player_cards where card_id = p_card),
    'stars', (select coalesce(sum(ascension), 0) from player_cards where card_id = p_card),
    'by_star', (select coalesce(jsonb_agg(jsonb_build_object('stars', a, 'owners', o, 'copies', c) order by a), '[]')
                  from (select ascension a, count(*) o, sum(quantity) c from player_cards where card_id = p_card group by 1) x),
    'with_stat_points', (select count(*) from player_cards where card_id = p_card and stat_points <> '{}'::jsonb),
    'top_owners', (select coalesce(jsonb_agg(jsonb_build_object('player_id', x.player_id, 'username', x.username, 'copies', x.quantity, 'stars', x.ascension)
                                 order by x.ascension desc, x.quantity desc, x.player_id), '[]')
                     from (select pc.player_id, p.username, pc.quantity, pc.ascension from player_cards pc join players p on p.id = pc.player_id
                            where pc.card_id = p_card order by pc.ascension desc, pc.quantity desc, pc.player_id limit 10) x),
    'pulls', jsonb_build_object(
        'total', (select coalesce(sum(amount), 0) from card_ledger where card_id = p_card and reason = 'pack' and amount > 0),
        'first', (select min(created_at) from card_ledger where card_id = p_card and reason = 'pack' and amount > 0),
        'last', (select max(created_at) from card_ledger where card_id = p_card and reason = 'pack' and amount > 0),
        'by_week', (select coalesce(jsonb_agg(jsonb_build_object('week', w, 'pulls', n) order by w), '[]')
                      from (select date_trunc('week', game_day(created_at))::date w, sum(amount) n from card_ledger
                             where card_id = p_card and reason = 'pack' and amount > 0 group by 1) x)),
    'in_by_reason', (select coalesce(jsonb_agg(jsonb_build_object('reason', reason, 'copies', s) order by reason), '[]')
                       from (select reason, sum(amount) s from card_ledger where card_id = p_card and amount > 0 group by 1) x),
    'out_by_reason', (select coalesce(jsonb_agg(jsonb_build_object('reason', reason, 'copies', s) order by reason), '[]')
                        from (select reason, -sum(amount) s from card_ledger where card_id = p_card and amount < 0 group by 1) x),
    'trading', jsonb_build_object(
        'swaps', (select count(*) from card_trades t where p_card = any (t.from_cards || t.to_cards)),
        'offers_by_status', (select coalesce(jsonb_object_agg(status, n), '{}') from (select status, count(*) n from trade_offers
                               where offer_card_id = p_card or request_card_id = p_card group by 1) x),
        'listings', (select count(*) from trade_listings where card_id = p_card),
        'listings_open', (select count(*) from trade_listings where card_id = p_card and status = 'open'),
        'auctions', (select count(*) from auctions where card_id = p_card),
        'auctions_sold', (select count(*) from auctions where card_id = p_card and status = 'sold'),
        'wishlisted_now', (select count(*) from wishlists where card_id = p_card),
        'top_want_now', (select count(*) from wishlists where card_id = p_card and top),
        'wishlist_adds', (select count(*) from wishlist_log where card_id = p_card and op in ('add', 'replace'))),
    'hunt', jsonb_build_object(
        'hunts', (select count(distinct hunt_id) from hunt_hits where card_id = p_card),
        'damage', (select coalesce(sum(damage), 0) from hunt_hits where card_id = p_card),
        'attacks', (select count(*) from hunt_combat_log where card_id = p_card),
        'supports', (select count(*) from combat_actions where mode = 'hunt' and kind = 'support' and card_id = p_card),
        'squads', (select count(*) from hunt_squads where p_card = any (card_ids))),
    'dungeon', (select coalesce(jsonb_agg(jsonb_build_object('mode', m.mode,
                    'runs', (select count(*) from dungeon_runs r where r.mode = m.run_mode and p_card = any (r.squad)),
                    'attacks', (select count(*) from ca where ca.mode = m.mode and ca.kind = 'attack' and ca.card_id = p_card),
                    'damage', (select coalesce(sum((ca.result->>'value')::numeric), 0) from ca where ca.mode = m.mode and ca.card_id = p_card
                                 and ca.kind in ('attack', 'support') and ca.result->>'side' = 'foe' and ca.result->>'dir' = 'dmg'),
                    'supports', (select count(*) from ca where ca.mode = m.mode and ca.kind = 'support' and ca.card_id = p_card),
                    'healed', (select coalesce(sum((ca.result->>'value')::numeric), 0) from ca where ca.mode = m.mode and ca.card_id = p_card
                                 and ca.result->>'side' = 'card' and ca.result->>'dir' = 'heal'),
                    'taken', (select coalesce(sum((ca.result->>'value')::numeric), 0) from ca where ca.mode = m.mode and ca.target_card = p_card
                                and ca.result->>'side' = 'card' and ca.result->>'dir' = 'dmg'),
                    'downs', (select count(*) from ca where ca.mode = m.mode and ca.target_card = p_card and ca.result->>'side' = 'card'
                                and ca.result->>'dir' = 'dmg' and (ca.result->>'hp_after')::numeric = 0 and (ca.result->>'value')::numeric > 0)) order by m.mode), '[]')
                  from (values ('dungeon', 'daily'), ('gauntlet', 'gauntlet')) m(mode, run_mode)),
    'plays', jsonb_build_object(
        'total', (select count(*) from card_plays where card_id = p_card),
        'by_primitive', (select coalesce(jsonb_agg(jsonb_build_object('primitive', primitive, 'kind', kind, 'plays', n, 'applied', a, 'blocked', b, 'refunded', r)
                                   order by n desc, primitive), '[]')
                           from (select primitive, kind, count(*) n, count(*) filter (where outcome = 'applied') a, count(*) filter (where outcome = 'blocked') b,
                                        count(*) filter (where outcome = 'refunded') r from card_plays where card_id = p_card group by 1, 2) x)))
  into v;
  return v;
end $function$;
-- @grants public.admin_card(bigint)
grant execute on function public.admin_card(bigint) to postgres;
grant execute on function public.admin_card(bigint) to service_role;
