-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_dungeon(date, date)
-- md5: 7ad7d6a7bef1e60916e85f4c16135299   (md5(replace(pg_get_functiondef('public.admin_dungeon(date, date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_dungeon(p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  pr jsonb := admin_period(p_from, p_to, 30);
  d0 date := (pr->>'from')::date; d1 date := (pr->>'to')::date;
  t0 timestamptz := (pr->>'t0')::timestamptz; t1 timestamptz := (pr->>'t1')::timestamptz;
  -- The combat log began with dungeon_combat_log.sql: an older run has no combat_actions rows and is not reconciled.
  v_log timestamptz := coalesce((select min(applied_at) from schema_migrations where file = 'dungeon_combat_log.sql'), 'infinity');
  v jsonb;
begin
  with
  runs as (select * from dungeon_runs r where r.day between d0 and d1),
  ca as (select a.* from combat_actions a where a.mode in ('dungeon', 'gauntlet') and a.created_at >= t0 and a.created_at < t1),
  -- A kill: a dungeon_log attack or support whose result holds the kill state; the foe is the target slot of that state.
  kills as (
    select r.mode, f->>'key' as key, coalesce(f->>'kind', 'fight') as kind
      from runs r join dungeon_log l on l.run_id = r.id
      cross join lateral (select l.result->'kill'->'state'->'foes'->(coalesce(l.action->>'target', l.action->>'target_foe'))::int as f) x
     where jsonb_typeof(l.result->'kill') = 'object' and coalesce(l.action->>'target', l.action->>'target_foe') ~ '^[0-9]+$'),
  downs as (
    select r.mode, count(*) n from runs r, jsonb_each(case when jsonb_typeof(r.state->'cards') = 'object' then r.state->'cards' else '{}' end) c
     where r.status = 'over' and (c.value->>'down')::boolean is true group by 1),
  rec as (select r.id, r.mode, (select count(*) from dungeon_damage_reconcile(r.id) d where d.unexplained <> 0) rows_bad,
                 (select coalesce(sum(abs(d.unexplained)), 0) from dungeon_damage_reconcile(r.id) d) hp_bad
            from runs r where r.started_at >= v_log),
  cards_dmg as (
    select coalesce(a.card_id, a.target_card) card_id, a.mode,
           count(*) filter (where a.kind = 'attack' and a.card_id is not null) attacks,
           coalesce(sum((a.result->>'value')::numeric) filter (where a.card_id is not null and a.kind in ('attack', 'support') and a.result->>'side' = 'foe' and a.result->>'dir' = 'dmg'), 0) damage,
           count(*) filter (where a.card_id is not null and a.kind in ('attack', 'support') and a.result->>'side' = 'foe' and a.result->>'dir' = 'dmg'
                              and (a.result->>'hp_after')::numeric = 0 and (a.result->>'value')::numeric > 0) foes_down,
           count(*) filter (where a.kind = 'attack' and (a.result->>'crit')::boolean is true) crits,
           count(*) filter (where a.kind = 'support' and a.card_id is not null) supports,
           coalesce(sum((a.result->>'value')::numeric) filter (where a.card_id is not null and a.result->>'side' = 'card' and a.result->>'dir' = 'heal'), 0) healed,
           coalesce(sum((a.result->>'value')::numeric) filter (where a.card_id is null and a.result->>'side' = 'card' and a.result->>'dir' = 'dmg'), 0) taken,
           count(*) filter (where a.card_id is null and a.result->>'side' = 'card' and a.result->>'dir' = 'dmg'
                              and (a.result->>'hp_after')::numeric = 0 and (a.result->>'value')::numeric > 0) downs
      from (select a.mode, a.kind, a.card_id, null::bigint target_card, a.result from ca a where a.card_id is not null
            union all
            -- the damage a card took: the row of the foe (or the poison, the thorns) that hit it, counted on the target card
            select a.mode, a.kind, null, a.target_card, a.result from ca a where a.target_card is not null and a.result->>'side' = 'card') a
     group by 1, 2),
  cd as (select c.card_id, sum(c.attacks) attacks, sum(c.damage) damage, sum(c.damage) filter (where c.mode = 'dungeon') damage_dungeon,
                sum(c.damage) filter (where c.mode = 'gauntlet') damage_gauntlet, sum(c.foes_down) foes_down, sum(c.crits) crits, sum(c.supports) supports,
                sum(c.healed) healed, sum(c.taken) taken, sum(c.downs) downs
           from cards_dmg c group by 1),
  pay as (select * from dungeon_payouts p where p.paid_at >= t0 and p.paid_at < t1)
  select jsonb_build_object(
    'period', pr - 't0' - 't1',
    'by_mode', (select coalesce(jsonb_agg(jsonb_build_object('mode', mode, 'runs', n, 'members', m, 'cleared', c, 'fell', f, 'retreat', rt, 'abandoned', ab, 'active', act,
                    'shards', s, 'cards', cs, 'best_floor', bf, 'avg_floor', af, 'avg_rooms', ar, 'avg_turns', avg_t) order by mode), '[]')
                  from (select r.mode, count(*) n, count(distinct r.player_id) m, count(*) filter (where r.ended_by = 'cleared') c,
                               count(*) filter (where r.ended_by = 'fell') f, count(*) filter (where r.ended_by = 'retreat') rt,
                               count(*) filter (where r.ended_by = 'abandoned') ab, count(*) filter (where r.status = 'active') act,
                               sum(r.shards) s, sum(cardinality(r.cards)) cs, max(r.floor) bf, round(avg(r.floor), 2) af,
                               round(avg((r.floor - 1) * 5 + r.room), 2) ar, round(avg(r.turns), 2) avg_t from runs r group by 1) x),
    'by_day', (select coalesce(jsonb_agg(jsonb_build_object('day', day, 'mode', mode, 'runs', n, 'members', m, 'cleared', c, 'fell', f, 'shards', s) order by day, mode), '[]')
                 from (select r.day, r.mode, count(*) n, count(distinct r.player_id) m, count(*) filter (where r.ended_by = 'cleared') c,
                              count(*) filter (where r.ended_by = 'fell') f, sum(r.shards) s from runs r group by 1, 2) x),
    -- floors and rooms reached: where each run stands (active) or ended
    'reached', (select coalesce(jsonb_agg(jsonb_build_object('mode', mode, 'floor', floor, 'room', room, 'runs', n, 'fell', f) order by mode, floor, room), '[]')
                  from (select r.mode, r.floor, r.room, count(*) n, count(*) filter (where r.ended_by = 'fell') f from runs r group by 1, 2, 3) x),
    'deaths', jsonb_build_object(
        'runs_fell', (select count(*) from runs where ended_by = 'fell'),
        'cards_down_at_end', (select coalesce(jsonb_object_agg(mode, n), '{}') from downs),
        'card_downs_logged', (select count(*) from ca where ca.result->>'side' = 'card' and ca.result->>'dir' = 'dmg'
                                and (ca.result->>'hp_after')::numeric = 0 and (ca.result->>'value')::numeric > 0)),
    'kills', (select coalesce(jsonb_agg(jsonb_build_object('key', key, 'name', name, 'kills', n, 'daily', dl, 'gauntlet', gt, 'by_kind', bk) order by n desc, key), '[]')
                from (select k.key, (select m.name from dungeon_monsters m where m.key = k.key) name, count(*) n,
                             count(*) filter (where k.mode = 'daily') dl, count(*) filter (where k.mode = 'gauntlet') gt,
                             (select jsonb_object_agg(kind, c) from (select k2.kind, count(*) c from kills k2 where k2.key is not distinct from k.key group by 1) z) bk
                        from kills k group by k.key) x),
    'kills_total', (select count(*) from kills),
    'paid', jsonb_build_object(
        'shards_by_source', (select coalesce(jsonb_agg(jsonb_build_object('mode', mode, 'source', src, 'shards', s, 'rows', n) order by mode, src), '[]')
                               from (select case when l.ref_kind = 'dungeon_payout' then split_part(l.ref_id, ':', 1) else coalesce(r.mode, 'no_run') end mode,
                                            l.ref_kind src, sum(l.amount) s, count(*) n
                                       from shard_ledger l left join dungeon_runs r on l.ref_kind <> 'dungeon_payout' and r.id::text = l.ref_id
                                      where l.reason = 'dungeon' and l.created_at >= t0 and l.created_at < t1 group by 1, 2) x),
        'shards', (select coalesce(sum(amount), 0) from shard_ledger where reason = 'dungeon' and created_at >= t0 and created_at < t1),
        'cards_by_rarity', (select coalesce(jsonb_agg(jsonb_build_object('reason', reason, 'rarity', rarity, 'copies', s) order by reason, rarity_rank(rarity), rarity), '[]')
                              from (select c.reason, k.rarity::text rarity, sum(c.amount) s from card_ledger c join cards k on k.id = c.card_id
                                     where c.reason in ('dungeon_loot', 'dungeon_prize') and c.amount > 0 and c.created_at >= t0 and c.created_at < t1 group by 1, 2) x),
        'cards', (select coalesce(sum(amount), 0) from card_ledger where reason in ('dungeon_loot', 'dungeon_prize') and amount > 0 and created_at >= t0 and created_at < t1),
        'packs', (select coalesce(sum(amount), 0) from pack_ledger where reason = 'dungeon_prize' and created_at >= t0 and created_at < t1),
        'boards', (select coalesce(jsonb_agg(jsonb_build_object('mode', p.mode, 'period', p.period, 'paid_at', p.paid_at, 'winners', jsonb_array_length(p.winners),
                        'shards', (select coalesce(sum((w->>'shards')::int), 0) from jsonb_array_elements(p.winners) w),
                        'packs', (select coalesce(sum((w->>'packs')::int), 0) from jsonb_array_elements(p.winners) w),
                        'cards', (select coalesce(sum(jsonb_array_length(coalesce(w->'cards', '[]'))), 0) from jsonb_array_elements(p.winners) w)) order by p.paid_at, p.mode), '[]')
                     from pay p)),
    'gauntlet_weeks', (select coalesce(jsonb_agg(jsonb_build_object('week', g.week, 'name', g.name, 'theme', g.theme,
                           'squad', (select coalesce(jsonb_agg(jsonb_build_object('id', k.id, 'name', k.name, 'rarity', k.rarity::text) order by o), '[]')
                                       from unnest(g.squad) with ordinality u(cid, o) left join cards k on k.id = u.cid),
                           'runs', (select count(*) from dungeon_runs r where r.mode = 'gauntlet' and r.day between g.week and g.week + 6),
                           'members', (select count(distinct player_id) from dungeon_runs r where r.mode = 'gauntlet' and r.day between g.week and g.week + 6),
                           'cleared', (select count(*) from dungeon_runs r where r.mode = 'gauntlet' and r.day between g.week and g.week + 6 and r.ended_by = 'cleared'),
                           'best', (select jsonb_build_object('floor', r.floor, 'room', r.room, 'turns', r.turns) from dungeon_runs r
                                     where r.mode = 'gauntlet' and r.day between g.week and g.week + 6 order by r.floor desc, r.room desc, r.turns, r.id limit 1),
                           'paid', exists (select 1 from dungeon_payouts p where p.mode = 'gauntlet' and p.period = g.week)) order by g.week desc), '[]')
                         from gauntlet_weeks g where g.week <= d1 and g.week + 6 >= d0),
    'card_damage', (select coalesce(jsonb_agg(jsonb_build_object('card_id', cd.card_id, 'name', k.name, 'rarity', k.rarity::text, 'attacks', cd.attacks,
                        'damage', cd.damage, 'damage_dungeon', coalesce(cd.damage_dungeon, 0), 'damage_gauntlet', coalesce(cd.damage_gauntlet, 0),
                        'foes_down', cd.foes_down, 'crits', cd.crits, 'supports', cd.supports, 'healed', cd.healed, 'taken', cd.taken, 'downs', cd.downs)
                        order by cd.damage desc, cd.card_id), '[]')
                      from (select * from cd order by damage desc, card_id limit 100) cd left join cards k on k.id = cd.card_id),
    'combat_rows', (select count(*) from ca),
    'reconcile', jsonb_build_object(
        'log_from', case when v_log = 'infinity' then null else v_log end,
        'runs_checked', (select count(*) from rec),
        'runs_ok', (select count(*) from rec where rows_bad = 0),
        'runs_before_log', (select count(*) from runs where started_at < v_log),
        'rows_unexplained', (select coalesce(sum(rows_bad), 0) from rec),
        'hp_unexplained', (select coalesce(sum(hp_bad), 0) from rec),
        'ok', not exists (select 1 from rec where rows_bad <> 0),
        'bad_runs', (select coalesce(jsonb_agg(jsonb_build_object('run', id, 'mode', mode, 'rows', rows_bad, 'hp', hp_bad) order by id desc), '[]')
                       from (select * from rec where rows_bad <> 0 order by id desc limit 20) x)))
  into v;
  return v;
end $function$;
-- @grants public.admin_dungeon(date, date)
grant execute on function public.admin_dungeon(date, date) to postgres;
grant execute on function public.admin_dungeon(date, date) to service_role;
