-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_timeline_kinds()
-- md5: b26ed97672a6167b47e6fb43b67ccf0f   (md5(replace(pg_get_functiondef('public.admin_timeline_kinds()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_timeline_kinds()
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select array['joined', 'guild', 'visit', 'tutorial', 'profile', 'pack', 'card', 'shard', 'daily', 'gift', 'gift_claim', 'hunt', 'combat',
    'squad', 'hunt_adjustment', 'dungeon', 'dungeon_over', 'dungeon_combat', 'effect_sent', 'effect_received', 'trade', 'wishlist', 'auction',
    'shop', 'stat_points', 'achievement', 'report', 'report_about', 'note', 'note_read', 'admin', 'chat', 'voice']::text[];
$function$;
-- @grants public.admin_timeline_kinds()
grant execute on function public.admin_timeline_kinds() to postgres;
grant execute on function public.admin_timeline_kinds() to service_role;
