-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_is_member_list(text, text[], jsonb)
-- md5: 0812f459e9c990919acffafe696cd8e4   (md5(replace(pg_get_functiondef('public.admin_is_member_list(text, text[], jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_is_member_list(p_key text, p_path text[], p_value jsonb)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_typeof(p_value) = 'array'
     and ((p_key = 'discord_immune' and coalesce(cardinality(p_path), 0) = 0)
          or p_path[cardinality(p_path)] = 'users'
          or (jsonb_array_length(p_value) > 0
              and not exists (select 1 from jsonb_array_elements(p_value) e where jsonb_typeof(e) <> 'string' or e #>> '{}' !~ '^\d{17,20}$')));
$function$;
-- @grants public.admin_is_member_list(text, text[], jsonb)
grant execute on function public.admin_is_member_list(text, text[], jsonb) to postgres;
grant execute on function public.admin_is_member_list(text, text[], jsonb) to service_role;
