-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_events()
-- md5: ae146162b62f2334bef613b0c9625c96   (md5(replace(pg_get_functiondef('public.admin_events()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_events()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object('now', now(), 'rows', coalesce(jsonb_agg(x.j order by x.ord, x.starts_at desc, x.id desc), '[]'))
    from (select e.id, e.starts_at, case e.status when 'live' then 0 when 'scheduled' then 1 when 'draft' then 2 else 3 end as ord,
                 jsonb_build_object('id', e.id, 'key', e.key, 'kind', e.kind, 'title', e.title, 'status', e.status, 'starts_at', e.starts_at,
                   'ends_at', e.ends_at, 'ended_at', e.ended_at, 'updated_at', e.updated_at, 'created_by', e.created_by,
                   'gifts', (select count(*) from gift_claims g where g.event_id = e.id),
                   'claimed', (select count(*) from gift_claims g where g.event_id = e.id and g.claimed_at is not null),
                   'members', (select count(distinct g.player_id) from gift_claims g where g.event_id = e.id)) as j
            from events e) x;
$function$;
-- @grants public.admin_events()
grant execute on function public.admin_events() to postgres;
grant execute on function public.admin_events() to service_role;
