-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_member(text)
-- md5: 783d8a33876809f484e1e2e91e7a4713   (md5(replace(pg_get_functiondef('public.admin_member(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_member(p_player text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare p players; v_first date; v_out jsonb; v_pw bigint; v_rank bigint; v_of bigint;
begin
  select * into p from players where id = p_player;
  if not found then return jsonb_build_object('found', false, 'player', p_player); end if;
  v_first := game_day(p.created_at);
  -- The power rank: 1 + the members with more power (collection_power_all, the leaderboard numbers); null with no power.
  select coalesce(max(w.power) filter (where w.player_id = p_player), 0), count(*) filter (where w.power > 0) into v_pw, v_of from collection_power_all() w;
  if v_pw > 0 then select 1 + count(*) into v_rank from collection_power_all() w where w.power > v_pw; end if;
  with act as (select * from admin_active_days(v_first, game_day()) a where a.player_id = p_player)
  select jsonb_build_object(
    'found', true,
    'profile', jsonb_build_object('id', p.id, 'username', p.username, 'joined', p.created_at, 'has_avatar', p.avatar is not null, 'title', p.title, 'frame', p.frame,
        'spotlight', p.spotlight, 'notify_prefs', p.notify_prefs, 'muted', coalesce(p.notify_prefs->>'all' = 'false', false), 'tutorial', p.tutorial,
        'first_pack_ping_at', p.first_pack_ping_at, 'stat_reset_week', p.stat_reset_week,
        'discord_immune', exists (select 1 from settings s where s.key = 'discord_immune' and jsonb_typeof(s.value) = 'array' and s.value ? p.id),
        -- The Discord CDN picture, the same URL as the Activity server (/api/avatar: a 32-hex hash, a_ for an animated one).
        'avatar_url', case when p.avatar ~ '^(a_)?[0-9a-f]{32}$' then 'https://cdn.discordapp.com/avatars/' || p.id || '/' || p.avatar || '.png?size=128' end,
        'guild_joined_at', p.guild_joined_at, 'left_guild_at', p.left_guild_at,
        'in_guild', case when p.guild_joined_at is null and p.left_guild_at is null then null else p.left_guild_at is null or p.left_guild_at < p.guild_joined_at end),
    'app', jsonb_build_object(
        'visits', (select count(*) from app_sessions where player_id = p_player),
        'last_visit', (select max(last_seen_at) from app_sessions where player_id = p_player),
        'views', (select count(*) from page_views where player_id = p_player),
        'views_by_screen', (select coalesce(jsonb_object_agg(view, n), '{}') from (select view, count(*) n from page_views where player_id = p_player group by 1) x),
        'tutorial_steps', (select count(*) from tutorial_steps where player_id = p_player),
        'notes', (select count(*) from notifications where player_id = p_player),
        'notes_unread', (select count(*) from notifications where player_id = p_player and not read),
        'profile_changes', (select count(*) from profile_log where player_id = p_player and field not like 'tutorial%'),
        'wishlist_changes', (select count(*) from wishlist_log where player_id = p_player),
        'admin_actions', (select count(*) from admin_actions where target_id = p_player and coalesce(target_kind, 'player') in ('player', 'member'))),
    'activity', jsonb_build_object(
        'first_active', (select min(day) from act where game), 'last_active', (select max(day) from act where game),
        'active_days', (select count(distinct day) from act where game),
        'active_days_7', (select count(distinct day) from act where game and day > game_day() - 7),
        'active_days_30', (select count(distinct day) from act where game and day > game_day() - 30),
        'chat_days', (select count(distinct day) from act where source = 'chat'), 'voice_days', (select count(distinct day) from act where source = 'voice'),
        'by_source', (select coalesce(jsonb_object_agg(source, n), '{}') from (select source, count(distinct day) n from act group by 1) x)),
    'balances', jsonb_build_object('packs', p.pack_balance, 'shards', p.shard_balance,
        'pack_ledger_sum', (select coalesce(sum(amount), 0) from pack_ledger where player_id = p_player),
        'shard_ledger_sum', (select coalesce(sum(amount), 0) from shard_ledger where player_id = p_player),
        'gifts_waiting', (select count(*) from gift_claims where player_id = p_player and claimed_at is null),
        'gift_packs_waiting', (select coalesce(sum(amount), 0) from gift_claims where player_id = p_player and claimed_at is null and kind <> 'card'),
        'gift_shards_waiting', (select coalesce(sum(shards), 0) from gift_claims where player_id = p_player and claimed_at is null),
        'packs_earned', (select coalesce(sum(amount), 0) from pack_ledger where player_id = p_player and amount > 0),
        'packs_opened', (select coalesce(-sum(amount), 0) from pack_ledger where player_id = p_player and reason = 'opened'),
        'shards_earned', (select coalesce(sum(amount), 0) from shard_ledger where player_id = p_player and amount > 0),
        'shards_spent', (select coalesce(-sum(amount), 0) from shard_ledger where player_id = p_player and amount < 0)),
    'collection', jsonb_build_object(
        'power', my_collection_power(p_player),
        'power_rank', v_rank, 'power_rank_of', v_of,
        'copies', (select coalesce(sum(quantity), 0) from player_cards where player_id = p_player),
        'unique_cards', (select count(*) from player_cards where player_id = p_player),
        'stars', (select coalesce(sum(ascension), 0) from player_cards where player_id = p_player),
        'by_rarity', (select coalesce(jsonb_agg(jsonb_build_object('rarity', r, 'unique', u, 'copies', c) order by rarity_rank(r), r), '[]')
                        from (select k.rarity::text r, count(*) u, sum(pc.quantity) c from player_cards pc join cards k on k.id = pc.card_id
                               where pc.player_id = p_player group by 1) x),
        'by_season', (select coalesce(jsonb_agg(jsonb_build_object('season', s, 'unique', u, 'of', t) order by s), '[]')
                        from (select coalesce(k.season, '(none)') s, count(pc.card_id) u, count(*) t from cards k
                                left join player_cards pc on pc.card_id = k.id and pc.player_id = p_player group by 1) x),
        'pulls', (select coalesce(sum(amount), 0) from card_ledger where player_id = p_player and reason = 'pack' and amount > 0),
        'pulls_since', admin_pulls_since(),
        'pulls_rare_plus', (select coalesce(sum(c.amount), 0) from card_ledger c join cards k on k.id = c.card_id
                              where c.player_id = p_player and c.reason = 'pack' and c.amount > 0 and k.rarity::text <> 'normal')),
    'stat_points', jsonb_build_object(
        'cards_with_points', (select count(*) from player_cards where player_id = p_player and stat_points <> '{}'::jsonb),
        'points_spent', (select coalesce(sum(v::numeric), 0) from player_cards pc, jsonb_each_text(case when jsonb_typeof(pc.stat_points) = 'object' then pc.stat_points else '{}' end) e(k, v)
                           where pc.player_id = p_player and v ~ '^-?[0-9]+(\.[0-9]+)?$'),
        'by_stat', (select coalesce(jsonb_object_agg(k, s), '{}') from (select k, sum(v::numeric) s from player_cards pc, jsonb_each_text(case when jsonb_typeof(pc.stat_points) = 'object' then pc.stat_points else '{}' end) e(k, v)
                      where pc.player_id = p_player and v ~ '^-?[0-9]+(\.[0-9]+)?$' group by 1) x)),
    'achievements', jsonb_build_object(
        'claims', (select count(*) from achievement_claims where player_id = p_player),
        'packs', (select coalesce(sum(packs), 0) from achievement_claims where player_id = p_player),
        'shards', (select coalesce(sum(shards), 0) from achievement_claims where player_id = p_player),
        'titles', (select coalesce(jsonb_agg(distinct title), '[]') from achievement_claims where player_id = p_player and title is not null),
        'frames', (select coalesce(jsonb_agg(distinct frame), '[]') from achievement_claims where player_id = p_player and frame is not null),
        'last', (select coalesce(jsonb_agg(jsonb_build_object('key', key, 'at', claimed_at) order by claimed_at desc), '[]')
                   from (select key, claimed_at from achievement_claims where player_id = p_player order by claimed_at desc, key limit 10) x)),
    'effects_now', (select coalesce(jsonb_agg(jsonb_build_object('id', e.id, 'primitive', e.primitive, 'amount', e.amount, 'starts_at', e.starts_at,
                        'expires_at', e.expires_at, 'uses', e.options->'uses', 'from', e.options->>'sender_id') order by e.id), '[]')
                      from player_effects e where e.player_id = p_player and e.consumed_at is null and (e.expires_at is null or e.expires_at > now())),
    'discord_effects_now', (select coalesce(jsonb_agg(jsonb_build_object('id', d.id, 'primitive', d.primitive, 'status', d.status, 'revert_at', d.revert_at) order by d.id), '[]')
                              from discord_effects d where d.target_id = p_player and d.status in ('pending', 'active')),
    'effect_plays', jsonb_build_object(
        'sent', (select count(*) from card_plays where player_id = p_player),
        'received', (select count(*) from card_plays where target_id = p_player and player_id <> p_player),
        'cooldowns_now', (select count(*) from card_effect_cooldowns where player_id = p_player and ready_at > now())),
    'hunt', jsonb_build_object(
        'hunts', (select count(distinct hunt_id) from hunt_hits where player_id = p_player),
        'damage', (select coalesce(sum(damage), 0) from hunt_hits where player_id = p_player),
        'attacks', (select count(*) from hunt_combat_log where player_id = p_player),
        'supports', (select count(*) from combat_actions where player_id = p_player and mode = 'hunt' and kind = 'support'),
        'prize_packs', (select coalesce(sum(amount), 0) from pack_ledger where player_id = p_player and reason = 'hunt_reward')),
    'dungeon', (select coalesce(jsonb_agg(jsonb_build_object('mode', mode, 'runs', n, 'best_floor', f, 'shards', s) order by mode), '[]')
                  from (select mode, count(*) n, max(floor) f, sum(shards) s from dungeon_runs where player_id = p_player group by 1) x),
    'trading', jsonb_build_object(
        'swaps', (select count(*) from card_trades where from_id = p_player or to_id = p_player),
        'open_offers', (select coalesce(jsonb_agg(jsonb_build_object('id', o.id, 'status', o.status, 'side', case when o.from_id = p_player then 'made' else 'received' end,
                            'offer_card', o.offer_card_id, 'request_card', o.request_card_id, 'created_at', o.created_at) order by o.id), '[]')
                          from trade_offers o where (o.from_id = p_player or o.to_id = p_player) and o.status in ('pending', 'countered')),
        'open_listings', (select coalesce(jsonb_agg(jsonb_build_object('id', l.id, 'card', l.card_id, 'created_at', l.created_at) order by l.id), '[]')
                            from trade_listings l where l.player_id = p_player and l.status = 'open'),
        'live_auctions', (select coalesce(jsonb_agg(jsonb_build_object('id', a.id, 'card', a.card_id, 'status', a.status, 'ends_at', a.ends_at) order by a.id), '[]')
                            from auctions a where a.seller_id = p_player and a.status in ('live', 'accepted')),
        'open_bids', (select coalesce(jsonb_agg(jsonb_build_object('id', b.id, 'auction', b.auction_id, 'status', b.status, 'cards', b.cards) order by b.id), '[]')
                        from auction_bids b where b.bidder_id = p_player and b.status in ('open', 'accepted')),
        'wishlist', (select coalesce(jsonb_agg(jsonb_build_object('slot', w.slot, 'card', w.card_id, 'top', w.top) order by w.slot), '[]')
                       from wishlists w where w.player_id = p_player)),
    'reports', jsonb_build_object(
        'by', (select coalesce(jsonb_agg(jsonb_build_object('id', r.id, 'kind', r.kind, 'at', r.created_at, 'issue', r.issue_number, 'text', left(r.body, 200)) order by r.id desc), '[]')
                 from (select * from player_reports where player_id = p_player order by id desc limit 20) r),
        'by_count', (select count(*) from player_reports where player_id = p_player),
        'against', (select coalesce(jsonb_agg(jsonb_build_object('id', r.id, 'kind', r.kind, 'at', r.created_at, 'by', r.player_id, 'issue', r.issue_number, 'text', left(r.body, 200)) order by r.id desc), '[]')
                      from (select * from player_reports where target_id = p_player and player_id <> p_player order by id desc limit 20) r),
        'against_count', (select count(*) from player_reports where target_id = p_player and player_id <> p_player)))
  into v_out;
  return v_out;
end $function$;
-- @grants public.admin_member(text)
grant execute on function public.admin_member(text) to postgres;
grant execute on function public.admin_member(text) to service_role;
