-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_growth(date, date)
-- md5: 6b34d487627ac86da17d533cd5a35e83   (md5(replace(pg_get_functiondef('public.admin_growth(date, date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_growth(p_from date DEFAULT NULL::date, p_to date DEFAULT NULL::date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  pr jsonb := admin_period(p_from, p_to, 28);
  d0 date := (pr->>'from')::date; d1 date := (pr->>'to')::date;
  t0 timestamptz := (pr->>'t0')::timestamptz; t1 timestamptz := (pr->>'t1')::timestamptz;
  n int := (pr->>'days')::int;
  v jsonb;
begin
  with
  joined as (select p.id, game_day(p.created_at) jd from players p where p.created_at >= t0 and p.created_at < t1),
  act as (select distinct a.player_id, a.day, a.source from admin_active_days(d0 - n, d1) a where a.game),
  ad as (select distinct player_id, day from act),
  -- retention by join week
  cw as (select date_trunc('week', jd)::date w, id from joined),
  cs as (select w, count(*) size from cw group by w),
  cohorts as (
    select cs.w, cs.size,
           (select coalesce(jsonb_agg(jsonb_build_object('week', z.k, 'active', z.a, 'share', round(z.a::numeric / cs.size, 4)) order by z.k), '[]')
              from (select k, (select count(distinct c2.id) from cw c2 join ad on ad.player_id = c2.id
                                 and ad.day >= cs.w + 7 * k and ad.day < cs.w + 7 * k + 7 where c2.w = cs.w) a
                      from generate_series(0, 8) k where cs.w + 7 * k + 6 <= d1) z) as weeks
      from cs),
  dn as (select x.nd, count(*) filter (where j.jd + x.nd <= d1) eligible,
                count(*) filter (where j.jd + x.nd <= d1 and exists (select 1 from ad where ad.player_id = j.id and ad.day = j.jd + x.nd)) kept
           from joined j cross join (values (1), (7), (30)) x(nd) group by x.nd),
  -- the funnel of the members who joined in the period (each step any time up to the period end)
  f as (
    select j.id, j.jd,
      exists (select 1 from gift_claims g where g.player_id = j.id and g.kind = 'new_player' and g.claimed_at < t1) welcome,
      (select min(l.created_at) from pack_ledger l where l.player_id = j.id and l.reason = 'opened' and l.created_at < t1) first_open,
      exists (select 1 from hunt_combat_log h where h.player_id = j.id and h.ts < t1)
        or exists (select 1 from combat_actions a where a.player_id = j.id and a.kind = 'support' and a.created_at < t1)
        or exists (select 1 from dungeon_runs r where r.player_id = j.id and r.started_at < t1) fought,
      exists (select 1 from trade_offers o where (o.from_id = j.id and o.created_at < t1) or (o.to_id = j.id and o.countered_at < t1))
        or exists (select 1 from trade_listings l where l.player_id = j.id and l.created_at < t1)
        or exists (select 1 from auctions u where u.seller_id = j.id and u.created_at < t1)
        or exists (select 1 from auction_bids b where b.bidder_id = j.id and b.created_at < t1)
        or exists (select 1 from card_trades t where (t.from_id = j.id or t.to_id = j.id) and t.created_at < t1) traded,
      j.jd + 13 <= d1 week2_eligible,
      exists (select 1 from ad where ad.player_id = j.id and ad.day between j.jd + 7 and j.jd + 13) week2
    from joined j),
  prev as (select distinct player_id from ad where day between d0 - n and d0 - 1),
  cur as (select distinct player_id from ad where day between d0 and d1),
  feat as (select case source when 'pack_open' then 'packs' when 'hunt' then 'hunt' when 'dungeon' then 'dungeon' when 'gauntlet' then 'gauntlet'
                    when 'trade' then 'trades' when 'auction' then 'auctions' when 'effect' then 'effects' when 'daily' then 'dailies'
                    when 'achievement' then 'achievements' when 'shop' then 'shop' when 'gift_claim' then 'gifts' else null end f, player_id
             from act where day between d0 and d1)
  select jsonb_build_object(
    'period', pr - 't0' - 't1',
    'new_by_day', (select coalesce(jsonb_agg(jsonb_build_object('day', x::date, 'new', (select count(*) from joined where jd = x::date)) order by x), '[]')
                     from generate_series(d0, d1, interval '1 day') x),
    'new_by_week', (select coalesce(jsonb_agg(jsonb_build_object('week', w, 'new', c) order by w), '[]') from (select w, count(*) c from cw group by 1) x),
    'cohorts', (select coalesce(jsonb_agg(jsonb_build_object('week', w, 'size', size, 'weeks', weeks) order by w), '[]') from cohorts),
    'retention', (select coalesce(jsonb_object_agg('d' || nd, jsonb_build_object('eligible', eligible, 'kept', kept,
                     'share', case when eligible > 0 then round(kept::numeric / eligible, 4) end)), '{}') from dn),
    'funnel', jsonb_build_object(
        'joined', (select count(*) from f),
        'claimed_welcome', (select count(*) from f where welcome),
        'opened_first_pack', (select count(*) from f where first_open is not null),
        'first_fight', (select count(*) from f where fought),
        'first_trade', (select count(*) from f where traded),
        'week2_eligible', (select count(*) from f where week2_eligible),
        'active_week2', (select count(*) from f where week2_eligible and week2),
        'median_hours_to_first_open', (select round((percentile_cont(0.5) within group (order by extract(epoch from first_open - p.created_at) / 3600))::numeric, 2)
                                         from f join players p on p.id = f.id where first_open is not null)),
    'churn', jsonb_build_object(
        'previous_period', jsonb_build_object('from', d0 - n, 'to', d0 - 1),
        'active_previous', (select count(*) from prev), 'active_now', (select count(*) from cur),
        'kept', (select count(*) from prev where player_id in (select player_id from cur)),
        'churned', (select count(*) from prev where player_id not in (select player_id from cur)),
        'churn_rate', case when (select count(*) from prev) > 0 then round((select count(*) from prev where player_id not in (select player_id from cur))::numeric / (select count(*) from prev), 4) end,
        'new_active', (select count(*) from cur where player_id in (select id from joined)),
        'returned', (select count(*) from cur where player_id not in (select player_id from prev) and player_id not in (select id from joined))),
    'feature_reach', jsonb_build_object('active', (select count(*) from cur),
        'features', (select coalesce(jsonb_agg(jsonb_build_object('feature', f, 'members', m,
                       'share', case when (select count(*) from cur) > 0 then round(m::numeric / (select count(*) from cur), 4) end) order by f), '[]')
                       from (select f, count(distinct player_id) m from feat where f is not null group by 1) x)))
  into v;
  return v;
end $function$;
-- @grants public.admin_growth(date, date)
grant execute on function public.admin_growth(date, date) to postgres;
grant execute on function public.admin_growth(date, date) to service_role;
