-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_member_card(text, text, bigint, integer, integer, text, bigint)
-- md5: 212116094b9cfd5aa6f75b4c41db5cc5   (md5(replace(pg_get_functiondef('public.admin_member_card(text, text, bigint, integer, integer, text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_member_card(p_actor text, p_player text, p_card bigint, p_amount integer, p_before integer, p_reason text, p_undo_of bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_q int; v_asc int; v_new int; v_id bigint;
begin
  perform admin_write_begin(p_actor, p_reason);
  if p_amount is null or p_amount = 0 or abs(p_amount) > 100 then
    raise exception using errcode = 'LP400', message = 'admin: the copy change must be a whole number from -100 to 100, not 0';
  end if;
  perform 1 from players where id = p_player for update;
  if not found then raise exception using errcode = 'LP400', message = 'admin: no member with this id'; end if;
  if not exists (select 1 from cards where id = p_card) then raise exception using errcode = 'LP400', message = 'admin: no card with this id'; end if;
  select quantity, ascension into v_q, v_asc from player_cards where player_id = p_player and card_id = p_card for update;
  v_q := coalesce(v_q, 0);
  if v_q is distinct from p_before then perform admin_stale('the copies of this card', to_jsonb(v_q), to_jsonb(p_before)); end if;
  if p_amount < 0 then
    if v_q + p_amount < 0 then raise exception using errcode = 'LP400', message = format('admin: the member has %s copies of this card', v_q); end if;
    if free_copies(p_player, p_card) < -p_amount then
      raise exception using errcode = 'LP400', message = 'admin: these copies are held by a trade offer, an auction or a bid';
    end if;
    if v_q + p_amount = 0 and coalesce(v_asc, 0) > 0 then
      raise exception using errcode = 'LP400', message = 'admin: the last copy has stars; removing it would lose the stars and the stat points';
    end if;
  end if;
  v_id := admin_log_action(p_actor, 'member_card', 'player', p_player, jsonb_build_object('card', p_card, 'copies', v_q),
    jsonb_build_object('card', p_card, 'copies', v_q + p_amount, 'amount', p_amount), p_reason, 'studio', p_undo_of);
  v_new := card_move(p_player, p_card, p_amount, 'admin', 'admin_action', v_id::text, 'admin');
  if v_new is distinct from v_q + p_amount then raise exception 'admin: card_move returned % (expected %)', v_new, v_q + p_amount; end if;
  return jsonb_build_object('action_id', v_id, 'player', p_player, 'card', p_card, 'before', v_q, 'after', v_new, 'amount', p_amount);
end $function$;
-- @grants public.admin_member_card(text, text, bigint, integer, integer, text, bigint)
grant execute on function public.admin_member_card(text, text, bigint, integer, integer, text, bigint) to postgres;
grant execute on function public.admin_member_card(text, text, bigint, integer, integer, text, bigint) to service_role;
