-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_report(text, jsonb)
-- md5: 7eff42a358ccd1dcf79e2db507ebd3dc   (md5(replace(pg_get_functiondef('public.admin_report(text, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_report(p_key text, p_params jsonb DEFAULT '{}'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  cat jsonb := (select e from jsonb_array_elements(admin_report_catalog()) e where e->>'key' = p_key);
  prm jsonb; lim int; v_days int; rows jsonb; v_hunt bigint; v_first date := coalesce((select game_day(min(created_at)) from players), game_day());
  rates jsonb := coalesce(balance_get('pulls')->'rates', '{}'::jsonb); p_rare numeric;
begin
  if cat is null then raise exception 'admin_report: unknown report % (see admin_report_catalog)', p_key; end if;
  prm := (cat->'params') || coalesce(p_params, '{}'::jsonb);
  lim := least(greatest(coalesce((prm->>'limit')::int, 100), 1), 1000);
  v_days := least(greatest(coalesce((prm->>'days')::int, 7), 1), 731);

  if p_key = 'top_power' then
    select coalesce(jsonb_agg(x order by (x->>'rank')::int), '[]') into rows from (
      select jsonb_build_object('rank', row_number() over (order by w.power desc, w.player_id), 'player_id', w.player_id, 'username', p.username, 'power', w.power,
               'copies', (select coalesce(sum(quantity), 0) from player_cards c where c.player_id = w.player_id),
               'unique_cards', (select count(*) from player_cards c where c.player_id = w.player_id)) x
        from collection_power_all() w join players p on p.id = w.player_id order by w.power desc, w.player_id limit lim) y;

  elsif p_key = 'inactive' then
    with la as (select player_id, max(day) last_active from admin_active_days(v_first, game_day()) where game group by 1)
    select coalesce(jsonb_agg(jsonb_build_object('player_id', p.id, 'username', p.username, 'joined', game_day(p.created_at), 'last_active', la.last_active,
             'days_since', game_day() - la.last_active, 'packs', p.pack_balance, 'shards', p.shard_balance) order by la.last_active desc, p.id), '[]') into rows
      from (select * from la where la.last_active <= game_day() - v_days order by la.last_active desc, la.player_id limit lim) la join players p on p.id = la.player_id;

  elsif p_key = 'packs_unopened' then
    with la as (select player_id, max(day) last_active from admin_active_days(v_first, game_day()) where game group by 1),
    g as (select player_id, sum(amount) n from gift_claims where claimed_at is null and kind <> 'card' group by 1),
    lo as (select player_id, max(created_at) t from pack_ledger where reason = 'opened' group by 1),
    r as (select p.id, p.username, p.pack_balance, coalesce(g.n, 0) gw, lo.t, la.last_active from players p
            left join g on g.player_id = p.id left join lo on lo.player_id = p.id left join la on la.player_id = p.id
           where p.pack_balance + coalesce(g.n, 0) >= coalesce((prm->>'min')::int, 1)
           order by p.pack_balance + coalesce(g.n, 0) desc, p.id limit lim)
    select coalesce(jsonb_agg(jsonb_build_object('player_id', id, 'username', username, 'packs', pack_balance, 'gift_packs_waiting', gw, 'last_open', t,
             'last_active', last_active) order by pack_balance + gw desc, id), '[]') into rows from r;

  elsif p_key = 'pull_luck' then
    p_rare := 1 - coalesce((rates->>'normal')::numeric, 1);
    with x as (select c.player_id, sum(c.amount) n, sum(c.amount) filter (where k.rarity::text <> 'normal') rp
                 from card_ledger c join cards k on k.id = c.card_id where c.reason = 'pack' and c.amount > 0 group by 1
                having sum(c.amount) >= coalesce((prm->>'min_pulls')::int, 25)),
    r as (select x.*, coalesce(x.rp, 0) rare, x.n * p_rare ex,
                 case when p_rare > 0 and p_rare < 1 then (coalesce(x.rp, 0) - x.n * p_rare) / sqrt(x.n * p_rare * (1 - p_rare)) end z from x)
    select coalesce(jsonb_agg(jsonb_build_object('player_id', r.player_id, 'username', p.username, 'pulls', r.n, 'rare_plus', r.rare,
             'expected_rare_plus', round(r.ex, 2), 'ratio', case when r.ex > 0 then round(r.rare / r.ex, 3) end, 'z', round(r.z, 2)) order by r.z desc nulls last, r.player_id), '[]')
      into rows from (select * from r order by z desc nulls last, player_id limit lim) r join players p on p.id = r.player_id;

  elsif p_key = 'shard_sinks' then
    v_days := least(greatest(coalesce((prm->>'days')::int, 30), 1), 731);
    with l as (select * from shard_ledger where created_at >= game_day_start(game_day() - v_days + 1)),
    s as (select * from shop_purchases where created_at >= game_day_start(game_day() - v_days + 1)),
    u as (select case when amount > 0 then 'in' else 'out' end dir, reason, null::text detail, abs(sum(amount)) shards, count(*) n, count(distinct player_id) m from l group by 1, 2
          union all
          select 'out', 'shop', kind, sum(price), count(*), count(distinct player_id) from s group by kind)
    select coalesce(jsonb_agg(jsonb_build_object('direction', dir, 'reason', reason, 'detail', detail, 'shards', shards, 'rows', n, 'members', m)
             order by dir, shards desc, reason, detail nulls first), '[]') into rows from u;

  elsif p_key = 'effect_usage' then
    v_days := least(greatest(coalesce((prm->>'days')::int, 30), 1), 731);
    select coalesce(jsonb_agg(jsonb_build_object('primitive', primitive, 'kind', kind, 'plays', n, 'senders', s, 'targets', t, 'applied', a, 'blocked', b,
             'reflected', rf, 'refunded', rd) order by n desc, primitive), '[]') into rows
      from (select primitive, kind, count(*) n, count(distinct player_id) s, count(distinct target_id) t,
                   count(*) filter (where outcome = 'applied') a, count(*) filter (where outcome = 'blocked') b,
                   count(*) filter (where outcome = 'reflected') rf, count(*) filter (where outcome = 'refunded') rd
              from card_plays where created_at >= game_day_start(game_day() - v_days + 1) group by 1, 2) x;

  elsif p_key = 'unclaimed_gifts' then
    select coalesce(jsonb_agg(jsonb_build_object('kind', k, 'reason', reason, 'waiting', n, 'members', m, 'packs', p, 'shards', s, 'oldest', o)
             order by n desc, k, reason), '[]') into rows
      from (select kind k, reason, count(*) n, count(distinct player_id) m,
                   sum(amount) filter (where kind <> 'card') p, sum(shards) s, min(created_at) o
              from gift_claims where claimed_at is null group by 1, 2) x;

  elsif p_key = 'hunt_board' then
    v_hunt := coalesce((prm->>'hunt')::bigint, (select max(id) from hunts));
    with m as (select player_id, sum(damage) dmg from hunt_hits where hunt_id = v_hunt group by 1),
    t as (select coalesce(sum(dmg), 0) d from m),
    pz as (select player_id, sum(amount) n from pack_ledger where reason = 'hunt_reward' and ref_kind = 'hunt' and ref_id = v_hunt::text group by 1),
    r as (select m.*, row_number() over (order by dmg desc, player_id) rk from m)
    select coalesce(jsonb_agg(jsonb_build_object('rank', r.rk, 'player_id', r.player_id, 'username', p.username, 'damage', r.dmg,
             'share', case when (select d from t) > 0 then round(r.dmg::numeric / (select d from t), 4) end, 'prize_packs', coalesce(pz.n, 0)) order by r.rk), '[]')
      into rows from r join players p on p.id = r.player_id left join pz on pz.player_id = r.player_id where r.rk <= lim;
    prm := prm || jsonb_build_object('hunt', v_hunt);
  else
    raise exception 'admin_report: % is in the catalog but has no query', p_key;
  end if;

  return jsonb_build_object('key', p_key, 'title', cat->>'title', 'params', prm, 'columns', cat->'columns', 'rows', rows,
    'row_count', jsonb_array_length(rows), 'limit', lim)
    || case when p_key = 'pull_luck' then jsonb_build_object('since', admin_pulls_since()) else '{}'::jsonb end;
end $function$;
-- @grants public.admin_report(text, jsonb)
grant execute on function public.admin_report(text, jsonb) to postgres;
grant execute on function public.admin_report(text, jsonb) to service_role;
