-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.admin_event_status(bigint, timestamp with time zone, text, text, text)
-- md5: fa82e7489104f1a4d3fc820a8a63b724   (md5(replace(pg_get_functiondef('public.admin_event_status(bigint, timestamp with time zone, text, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.admin_event_status(p_id bigint, p_expected_updated_at timestamp with time zone, p_actor text, p_to text, p_reason text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare e events; c events; v_errors text[];
begin
  if coalesce(trim(p_actor), '') = '' then raise exception 'admin_event_status: the actor is required'; end if;
  select * into e from events where id = p_id for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
  if e.updated_at is distinct from p_expected_updated_at then return jsonb_build_object('ok', false, 'error', 'stale', 'event', to_jsonb(e)); end if;
  if e.kind = 'launch_cards' then return jsonb_build_object('ok', false, 'error', 'locked', 'errors', jsonb_build_array('the launch event is set in settings.launch_event_cards')); end if;
  if not ((p_to = 'scheduled' and e.status = 'draft') or (p_to = 'draft' and e.status = 'scheduled') or (p_to = 'cancelled' and e.status in ('draft', 'scheduled', 'live'))) then
    return jsonb_build_object('ok', false, 'error', 'bad_status', 'errors', jsonb_build_array(format('%s cannot become %s', e.status, p_to)));
  end if;
  if p_to = 'scheduled' then
    v_errors := event_row_errors(e);
    if e.ends_at <= now() then v_errors := v_errors || 'the end is in the past'::text; end if;
    if cardinality(v_errors) > 0 then return jsonb_build_object('ok', false, 'error', 'invalid', 'errors', to_jsonb(v_errors)); end if;
  end if;
  perform set_config('events.actor', p_actor, true);
  update events set status = p_to, ended_at = case when p_to = 'cancelled' then now() end where id = p_id returning * into c;
  perform set_config('events.actor', '', true);
  perform admin_log_action(p_actor, case p_to when 'scheduled' then 'event_schedule' when 'draft' then 'event_unschedule' else 'event_cancel' end,
    'event', p_id::text, jsonb_build_object('status', e.status), jsonb_build_object('status', c.status), p_reason, 'studio');
  return jsonb_build_object('ok', true, 'event', to_jsonb(c));
end $function$;
-- @grants public.admin_event_status(bigint, timestamp with time zone, text, text, text)
grant execute on function public.admin_event_status(bigint, timestamp with time zone, text, text, text) to postgres;
grant execute on function public.admin_event_status(bigint, timestamp with time zone, text, text, text) to service_role;
