-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.adventure_gate(text)
-- md5: 0311d5c23868cd2cc8d8bf69b4b76e36   (md5(replace(pg_get_functiondef('public.adventure_gate(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.adventure_gate(p_player text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'ok', g.open = 0 and a.n >= g.need,
    'gifts_open', g.open, 'gifts_total', g.total,
    'attackers', a.n, 'need', g.need)
  from (select count(*) filter (where claimed_at is null)::int open, count(*)::int total,
               coalesce((select (value->>'attackers')::int from settings where key = 'adventure_gate'), 8) need
          from gift_claims where player_id = p_player and kind in ('new_player', 'launch_day')) g,
       (select count(*)::int n from player_cards pc join cards c on c.id = pc.card_id join subjects s on s.id = c.subject_id
          where pc.player_id = p_player and pc.quantity > 0 and s.type in ('Character', 'Creature')) a;
$function$;
-- @grants public.adventure_gate(text)
grant execute on function public.adventure_gate(text) to postgres;
grant execute on function public.adventure_gate(text) to service_role;
