-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ascend_cost(text, integer)
-- md5: 4ea15d528c581a742b9e3fba7beb3d1b   (md5(replace(pg_get_functiondef('public.ascend_cost(text, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ascend_cost(p_rarity text, p_ascension integer)
 RETURNS integer
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select case when coalesce(p_ascension, 0) >= 5 then null else
    coalesce((balance_get('ascend_cost')->p_rarity->>coalesce(p_ascension, 0))::int,
             (balance_get('ascend_cost')->'normal'->>coalesce(p_ascension, 0))::int) end;
$function$;
-- @grants public.ascend_cost(text, integer)
grant execute on function public.ascend_cost(text, integer) to postgres;
grant execute on function public.ascend_cost(text, integer) to service_role;
