-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.balance_log_write()
-- md5: 9f34dd25e5f5a949e776d52ab60279fb   (md5(replace(pg_get_functiondef('public.balance_log_write()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.balance_log_write()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if tg_op = 'UPDATE' and old.value = new.value and old.note = new.note then return new; end if;
  insert into balance_log (key, op, old_value, new_value, changed_by)
    values (new.key, lower(tg_op), case when tg_op = 'UPDATE' then old.value end, new.value, balance_who());
  return new;
end $function$;
-- @grants public.balance_log_write()
grant execute on function public.balance_log_write() to postgres;
grant execute on function public.balance_log_write() to service_role;
