-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.balance_num(text, text[])
-- md5: e4849cbdda72f397d7e1e4314ae87106   (md5(replace(pg_get_functiondef('public.balance_num(text, text[])'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.balance_num(p_key text, VARIADIC p_path text[])
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare v numeric;
begin
  v := (balance_get(p_key) #>> p_path)::numeric;
  if v is null then raise exception 'balance: no number at %.%', p_key, array_to_string(p_path, '.'); end if;
  return v;
end $function$;
-- @grants public.balance_num(text, text[])
grant execute on function public.balance_num(text, text[]) to postgres;
grant execute on function public.balance_num(text, text[]) to service_role;
