-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.balance_leaves(jsonb)
-- md5: 520df5b00c9bf35fb81540115ea5f2c7   (md5(replace(pg_get_functiondef('public.balance_leaves(jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.balance_leaves(p jsonb)
 RETURNS TABLE(path text[], typ text, num numeric)
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  with recursive t(path, v) as (
    select '{}'::text[], p
    union all
    select t.path || e.k, e.v from t
      cross join lateral (
        select k, v from jsonb_each(case when jsonb_typeof(t.v) = 'object' then t.v else '{}'::jsonb end) x(k, v)
        union all
        select (o - 1)::text, v from jsonb_array_elements(case when jsonb_typeof(t.v) = 'array' then t.v else '[]'::jsonb end)
          with ordinality y(v, o)) e
  )
  select path, jsonb_typeof(v), case when jsonb_typeof(v) = 'number' then (v #>> '{}')::numeric end
    from t where jsonb_typeof(v) not in ('object', 'array') or v in ('{}'::jsonb, '[]'::jsonb);
$function$;
-- @grants public.balance_leaves(jsonb)
grant execute on function public.balance_leaves(jsonb) to postgres;
grant execute on function public.balance_leaves(jsonb) to service_role;
