-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.balance_check_boss_counters()
-- md5: 236432d4abba607c637c385977326fe3   (md5(replace(pg_get_functiondef('public.balance_check_boss_counters()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.balance_check_boss_counters()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_bad text;
begin
  if new.key = 'boss_counters' then
    -- Every leaf is a number (the move names and texts are content: settings.hunt_boss_moves).
    select string_agg(array_to_string(l.path, '.'), ', ') into v_bad from balance_leaves(new.value) l
     where l.typ <> 'number' and not (l.typ = 'object' and l.path in (array['boss_share'], array['weights']));   -- an empty map: {}
    if v_bad is not null then raise exception 'balance boss_counters: % must be a number', v_bad; end if;
    -- A share of the turns, a share of an effect, a curse and a kept share are 0 to 1.
    select string_agg(array_to_string(l.path, '.'), ', ') into v_bad from balance_leaves(new.value) l
     where l.num > 1 and (l.path[1] in ('share', 'boss_share')
        or (l.path[1] = 'moves' and l.path[3] in ('heal', 'shield', 'empower', 'expose', 'smite', 'share', 'keep', 'curse', 'back')));
    if v_bad is not null then raise exception 'balance boss_counters: % must be from 0 to 1', v_bad; end if;
    -- Rounds, waits, plays, cards and hits are whole numbers; a hit count and a play count are at least 1.
    select string_agg(array_to_string(l.path, '.'), ', ') into v_bad from balance_leaves(new.value) l
     where l.path[1] = 'moves' and l.path[3] in ('rounds', 'wait', 'plays', 'cards', 'hits')
       and (l.num % 1 <> 0 or (l.path[3] in ('plays', 'hits') and l.num < 1));
    if v_bad is not null then raise exception 'balance boss_counters: % must be a whole number (plays and hits at least 1)', v_bad; end if;
    -- A hit size and a multiplier are above 0 (0 would make a move do nothing: change the pool instead).
    select string_agg(array_to_string(l.path, '.'), ', ') into v_bad from balance_leaves(new.value) l
     where l.path[1] = 'moves' and (l.path[3] like '%\_x' or l.path[3] in ('x', 'times', 'enrage')) and l.num <= 0;
    if v_bad is not null then raise exception 'balance boss_counters: % must be above 0', v_bad; end if;
    if (select sum(l.num) from balance_leaves(new.value) l where l.path[1] = 'weights') <= 0 then
      raise exception 'balance boss_counters: the weights must add up to more than 0';
    end if;
  elsif new.key = 'boss_passives' then
    -- The counter passives: a share of a support (_x), a share of a curse and a chance are 0 to 1.
    select string_agg(k, ', ') into v_bad from unnest(array['plague_x', 'shatterer_x', 'dispeller_x', 'juggernaut_x', 'juggernaut_stun_fail', 'plague_cleanse']) k
     where new.value ? k and (jsonb_typeof(new.value->k) <> 'number' or (new.value->>k)::numeric > 1);
    if v_bad is not null then raise exception 'balance boss_passives: % must be a number from 0 to 1', v_bad; end if;
  end if;
  return new;
end $function$;
-- @grants public.balance_check_boss_counters()
grant execute on function public.balance_check_boss_counters() to postgres;
grant execute on function public.balance_check_boss_counters() to service_role;
