-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_stats_for(text)
-- md5: 00caf8bea00b2a7754b3c3470c3d7fd4   (md5(replace(pg_get_functiondef('public.card_stats_for(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_stats_for(p_player text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object('on', coalesce((stat_cfg()->>'enabled')::boolean, false),
    'reset_week', (select stat_reset_week from players where id = p_player),
    'week', to_char(now() at time zone 'America/Denver', 'IYYY-IW'),
    'cards', coalesce((select jsonb_object_agg(pc.card_id::text,
        card_combat(c.rarity::text, pc.ascension, s.cp_mod, pc.stat_points) || jsonb_build_object('points', pc.stat_points))
      from player_cards pc join cards c on c.id = pc.card_id left join subjects s on s.id = c.subject_id
      where pc.player_id = p_player and (pc.ascension > 0 or pc.stat_points <> '{}'::jsonb)), '{}'::jsonb));
$function$;
-- @grants public.card_stats_for(text)
grant execute on function public.card_stats_for(text) to postgres;
grant execute on function public.card_stats_for(text) to service_role;
