-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_trades_from_offer()
-- md5: 0a3fca1e6986d3d3f49ff7f1fbf25c10   (md5(replace(pg_get_functiondef('public.card_trades_from_offer()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_trades_from_offer()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  insert into card_trades (kind, from_id, to_id, from_cards, to_cards, offer_id, created_at)
  values ('offer', new.from_id, new.to_id, array[new.offer_card_id],
          case when new.request_card_id is null then '{}'::bigint[] else array[new.request_card_id] end,
          new.id, coalesce(new.resolved_at, now()))
  on conflict do nothing;
  return null;
end $function$;
-- @grants public.card_trades_from_offer()
grant execute on function public.card_trades_from_offer() to postgres;
grant execute on function public.card_trades_from_offer() to service_role;
