-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_effect_active(text, text)
-- md5: fb2414b73434f856cc4d30eee9bd508b   (md5(replace(pg_get_functiondef('public.card_effect_active(text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_effect_active(p_player text, p_primitive text)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from player_effects
                  where player_id = p_player and primitive = p_primitive and consumed_at is null
                    and (expires_at is null or expires_at > now())
                    and not (options ? 'arm_s' and created_at <= now() - interval '7 days'))   -- effects_outside.sql
      or exists (select 1 from discord_effects
                  where target_id = p_player and primitive = p_primitive
                    and status in ('pending', 'active') and (revert_at is null or revert_at > now()));
$function$;
-- @grants public.card_effect_active(text, text)
grant execute on function public.card_effect_active(text, text) to postgres;
grant execute on function public.card_effect_active(text, text) to service_role;
