-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_trades_from_auction()
-- md5: aecbb9c0c85f6f75b3bb4fa3d605a978   (md5(replace(pg_get_functiondef('public.card_trades_from_auction()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_trades_from_auction()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  insert into card_trades (kind, from_id, to_id, from_cards, to_cards, auction_id, created_at)
  select 'auction', new.seller_id, b.bidder_id, array[new.card_id], b.cards, new.id, coalesce(new.settled_at, now())
    from auction_bids b where b.id = new.accepted_bid_id
  on conflict do nothing;
  return null;
end $function$;
-- @grants public.card_trades_from_auction()
grant execute on function public.card_trades_from_auction() to postgres;
grant execute on function public.card_trades_from_auction() to service_role;
