-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_element(text[])
-- md5: c831ce53c14c64d5e97d3c8143f1c647   (md5(replace(pg_get_functiondef('public.card_element(text[])'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_element(p_tags text[])
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $function$
  select a.element from unnest(coalesce(p_tags, '{}'::text[])) t
    join public.element_aliases() a on a.alias = lower(trim(regexp_replace(t, '^trait:', '', 'i')))
   order by a.ord limit 1;
$function$;
-- @grants public.card_element(text[])
grant execute on function public.card_element(text[]) to postgres;
grant execute on function public.card_element(text[]) to service_role;
