-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_ledger_reconcile()
-- md5: 9573ff19fe2970766a44448e6547d612   (md5(replace(pg_get_functiondef('public.card_ledger_reconcile()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_ledger_reconcile()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with l as (
    select player_id, card_id, sum(amount)::bigint as ledger from card_ledger group by player_id, card_id
  ), s as (
    select coalesce(pc.player_id, l.player_id) as player_id, coalesce(pc.card_id, l.card_id) as card_id,
           coalesce(pc.quantity, 0)::bigint as quantity, coalesce(l.ledger, 0) as ledger
      from player_cards pc full join l on l.player_id = pc.player_id and l.card_id = pc.card_id
  ), x as (
    select (select count(distinct player_id) from s) as players,
           (select count(*) from s where s.ledger <> s.quantity) as mismatched,
           (select count(distinct player_id) from s where s.ledger <> s.quantity) as players_mismatched,
           (select coalesce(sum(abs(s.ledger - s.quantity)), 0) from s) as copies_gap,
           (select coalesce(jsonb_agg(jsonb_build_object('player_id', s.player_id, 'card_id', s.card_id, 'quantity', s.quantity, 'ledger', s.ledger)), '[]'::jsonb)
              from s where s.ledger <> s.quantity) as mismatched_rows,
           (select count(*) from card_ledger) as rows,
           (select count(*) from card_ledger where ref_kind = 'tx') as rows_tx_ref,
           coalesce((select convalidated from pg_constraint where conname = 'card_ledger_reason_check' and conrelid = 'public.card_ledger'::regclass), false) as reason_check,
           coalesce((select convalidated from pg_constraint where conname = 'player_cards_quantity_check' and conrelid = 'public.player_cards'::regclass), false) as quantity_check
  )
  select jsonb_build_object('ok', x.mismatched = 0 and x.rows_tx_ref = 0 and x.reason_check and x.quantity_check,
    'players', x.players, 'mismatched', x.mismatched, 'players_mismatched', x.players_mismatched, 'copies_gap', x.copies_gap,
    'rows', x.rows, 'rows_tx_ref', x.rows_tx_ref, 'reason_check', x.reason_check, 'quantity_check', x.quantity_check,
    'mismatched_rows', x.mismatched_rows)
    from x;
$function$;
-- @grants public.card_ledger_reconcile()
grant execute on function public.card_ledger_reconcile() to postgres;
grant execute on function public.card_ledger_reconcile() to service_role;
