-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.cards_set_rules()
-- md5: e76e88d7933fd027ab24239cf21d3ec5   (md5(replace(pg_get_functiondef('public.cards_set_rules()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.cards_set_rules()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_n int;
begin
  if tg_op = 'INSERT' and new.set_id is null then
    select min(id), count(*) into new.set_id, v_n from card_sets where season = season_number(new.season);
    if v_n <> 1 then
      raise exception 'cards: the season % has % sets (send set_id)', coalesce(new.season, 'null'), v_n using errcode = 'check_violation';
    end if;
  end if;
  new.season := coalesce((select 'Season ' || season from card_sets where id = new.set_id), new.season);
  if tg_op = 'INSERT' or new.set_id is distinct from old.set_id then
    update card_sets set last_number = last_number + 1 where id = new.set_id returning last_number into new.set_number;
  elsif new.set_number is distinct from old.set_number then
    raise exception 'cards: the set number of card % is fixed (% -> %)', old.id, old.set_number, new.set_number using errcode = 'check_violation';
  end if;
  return new;
end $function$;
-- @grants public.cards_set_rules()
grant execute on function public.cards_set_rules() to postgres;
grant execute on function public.cards_set_rules() to service_role;
