-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.cards_event_rules()
-- md5: f6a519020b8c3bb94c840168a5b42965   (md5(replace(pg_get_functiondef('public.cards_event_rules()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.cards_event_rules()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if new.rarity::text in ('event', 'promo') then
    new.tradeable := false;      -- trades and gifts refuse a card with tradeable = false
    new.in_draw_pool := false;   -- never in a pack
  end if;
  return new;
end $function$;
-- @grants public.cards_event_rules()
grant execute on function public.cards_event_rules() to postgres;
grant execute on function public.cards_event_rules() to service_role;
