-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.card_combat(text, integer, numeric, jsonb)
-- md5: f7b151cfedfd8f0a595404e327f80d33   (md5(replace(pg_get_functiondef('public.card_combat(text, integer, numeric, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.card_combat(p_rarity text, p_asc integer, p_mod numeric, p_pts jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare
  c jsonb := stat_cfg();
  a int := greatest(0, least(5, coalesce(p_asc, 0)));
  pts jsonb := coalesce(p_pts, '{}'::jsonb);
  v_x numeric; v_cp int; v_spent int;
begin
  v_x := card_cp_exact(p_rarity, a, p_mod);
  if not coalesce((c->>'enabled')::boolean, false) then
    v_cp := round(v_x)::int;
    return jsonb_build_object('on', false, 'cp', v_cp, 'hp', card_max_hp(v_cp), 'crit', 0,
      'potency', 1, 'haste', 1, 'free', 0);
  end if;
  v_spent := stat_pt(pts, 'attack') + stat_pt(pts, 'vitality') + stat_pt(pts, 'precision')
           + stat_pt(pts, 'potency') + stat_pt(pts, 'haste');
  v_cp := round(v_x * (1 + (c->>'attack')::numeric * stat_pt(pts, 'attack')))::int;
  return jsonb_build_object('on', true, 'cp', v_cp,
    'hp', round(card_max_hp(v_cp) * (1 + (c->>'vitality')::numeric * stat_pt(pts, 'vitality')))::int,
    'crit', (c->>'precision')::numeric * stat_pt(pts, 'precision'),
    'potency', 1 + (c->>'potency')::numeric * stat_pt(pts, 'potency'),
    'haste', greatest((c->>'haste_floor')::numeric, 1 - (c->>'haste')::numeric * stat_pt(pts, 'haste')),
    'free', greatest(0, (c->>'per_star')::int * a - v_spent));
end $function$;
-- @grants public.card_combat(text, integer, numeric, jsonb)
grant execute on function public.card_combat(text, integer, numeric, jsonb) to postgres;
grant execute on function public.card_combat(text, integer, numeric, jsonb) to service_role;
