-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.claim_achievement(text, text, integer, text, text)
-- md5: 34f4be6488a0d45577e2745381e41f11   (md5(replace(pg_get_functiondef('public.claim_achievement(text, text, integer, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.claim_achievement(p_player text, p_key text, p_packs integer DEFAULT NULL::integer, p_title text DEFAULT NULL::text, p_frame text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare inserted int; bal int; r jsonb; v_packs int;
begin
  -- The reward is balance achievement_rewards.badges (balance_economy.sql). p_packs, p_title and p_frame are no
  -- longer read: an older Activity still sends them.
  r := balance_get('achievement_rewards')->'badges'->p_key;
  if r is null then return jsonb_build_object('ok', false, 'error', 'unknown'); end if;
  v_packs := coalesce((r->>'packs')::int, 0);
  -- The tracks replace these keys (achievement_tracks.sql): never paid again once they are on.
  if ach_tracks_on(p_player) and exists (select 1 from achievement_switch_map where old_key = p_key) then
    return jsonb_build_object('ok', false, 'error', 'retired'); end if;
  insert into achievement_claims (player_id, key, packs, title, frame)
    values (p_player, p_key, v_packs, r->>'title', r->>'frame')
    on conflict (player_id, key) do nothing;
  get diagnostics inserted = row_count;
  if inserted = 0 then return jsonb_build_object('ok', false, 'error', 'claimed'); end if;
  if v_packs > 0 then
    bal := grant_packs(p_player, v_packs, 'achievement', null, 'achievement', p_key);
    if bal is null then raise exception 'unknown player %', p_player; end if; -- rolls the claim back
  end if;
  return jsonb_build_object('ok', true, 'balance', bal, 'packs', v_packs, 'title', r->>'title', 'frame', r->>'frame');
end; $function$;
-- @grants public.claim_achievement(text, text, integer, text, text)
grant execute on function public.claim_achievement(text, text, integer, text, text) to postgres;
grant execute on function public.claim_achievement(text, text, integer, text, text) to service_role;
