-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.claim_gift(text, bigint)
-- md5: 3492a584dd9a8a56a934ce91b8374c4d   (md5(replace(pg_get_functiondef('public.claim_gift(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.claim_gift(p_player text, p_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare g gift_claims; bal int; sbal int;
begin
  select * into g from gift_claims where id = p_id and player_id = p_player for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
  if g.claimed_at is not null then return jsonb_build_object('ok', false, 'error', 'claimed'); end if;
  update gift_claims set claimed_at = now() where id = p_id;
  if g.kind = 'card' then
    -- A card gift (launch_event_cards.sql): the card goes to the collection.
    perform add_card_to_player(p_player, g.card_id, 'gift'); -- the same path as a trade
    return jsonb_build_object('ok', true, 'packs', 0, 'card_id', g.card_id, 'title', g.title);
  end if;
  if g.amount > 0 then bal := grant_packs(p_player, g.amount, g.reason, g.from_id, 'gift', g.id::text); end if;
  if g.shards > 0 then sbal := grant_shards(p_player, g.shards, 'event', 'gift', g.id::text); end if;
  return jsonb_build_object('ok', true, 'packs', g.amount, 'shards', g.shards, 'title', g.title,
    'balance', coalesce(bal, (select pack_balance from players where id = p_player)), 'shard_balance', sbal);
end $function$;
-- @grants public.claim_gift(text, bigint)
grant execute on function public.claim_gift(text, bigint) to postgres;
grant execute on function public.claim_gift(text, bigint) to service_role;
