-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.close_hunt(bigint)
-- md5: 5bf4f772b8b4888653f9b17da96197da   (md5(replace(pg_get_functiondef('public.close_hunt(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.close_hunt(p_hunt bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_name text; v_settle jsonb;
begin
  update hunts set status = 'expired' where id = p_hunt and status = 'active' returning name into v_name;
  if v_name is null then return jsonb_build_object('ok', true, 'note', 'not_active', 'hunt', p_hunt); end if;
  v_settle := settle_hunt(p_hunt);
  insert into hunt_events (hunt_id, kind, payload)
    values (p_hunt, 'expired', jsonb_build_object('name', v_name, 'settle', v_settle,
      'top', (select jsonb_agg(jsonb_build_object('player_id', player_id, 'damage', damage))
              from (select player_id, sum(damage) as damage from hunt_hits where hunt_id = p_hunt
                    group by player_id order by sum(damage) desc limit 3) t)));
  return jsonb_build_object('ok', true, 'closed', p_hunt, 'settled', v_settle);
end $function$;
-- @grants public.close_hunt(bigint)
grant execute on function public.close_hunt(bigint) to postgres;
grant execute on function public.close_hunt(bigint) to service_role;
