-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.close_auction(text, bigint)
-- md5: 7c5468d6ff6262eba449ae6421bb2951   (md5(replace(pg_get_functiondef('public.close_auction(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.close_auction(p_seller text, p_auction bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare a auctions;
begin
  select * into a from auctions where id = p_auction for update;
  if not found or a.seller_id <> p_seller then return jsonb_build_object('ok', false, 'error', 'not_seller'); end if;
  if a.status not in ('live', 'accepted') then return jsonb_build_object('ok', false, 'error', 'not_live'); end if;
  perform return_bids(a.id);
  update auctions set status = 'closed', settled_at = now(), notice_dirty = true where id = a.id;
  return jsonb_build_object('ok', true);
end $function$;
-- @grants public.close_auction(text, bigint)
grant execute on function public.close_auction(text, bigint) to postgres;
grant execute on function public.close_auction(text, bigint) to service_role;
