-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_enemy_mult(numeric, integer, numeric, integer, integer, boolean, numeric, boolean)
-- md5: 527cc7dac6375958062a973f44324878   (md5(replace(pg_get_functiondef('public.combat_enemy_mult(numeric, integer, numeric, integer, integer, boolean, numeric, boolean)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_enemy_mult(p_enrage numeric, p_enr_until integer, p_weaken numeric, p_wk_until integer, p_round integer, p_volatile boolean, p_lost numeric, p_frenzied boolean)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare v_bmult numeric := 1;
begin
  if p_enr_until >= p_round and p_enrage > 0 then v_bmult := v_bmult * p_enrage; end if;
  if p_wk_until  >= p_round and p_weaken > 0 then v_bmult := v_bmult * (1 - p_weaken); end if;
  if p_volatile then v_bmult := v_bmult * public.balance_num('boss_passives', 'volatile_x'); end if;                       -- volatile
  if p_lost >= public.balance_num('boss_moves', 'rage_at') then v_bmult := v_bmult * public.balance_num('boss_moves', 'rage_x'); end if;                     -- below 50% HP: rage
  if p_frenzied then v_bmult := v_bmult * (1 + public.balance_num('boss_passives', 'frenzied_per_10pct') * floor(p_lost * 10)); end if;
  return v_bmult;
end $function$;
-- @grants public.combat_enemy_mult(numeric, integer, numeric, integer, integer, boolean, numeric, boolean)
grant execute on function public.combat_enemy_mult(numeric, integer, numeric, integer, integer, boolean, numeric, boolean) to postgres;
grant execute on function public.combat_enemy_mult(numeric, integer, numeric, integer, integer, boolean, numeric, boolean) to service_role;
