-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_pool_act(numeric, numeric, integer, integer, numeric, integer, jsonb, boolean)
-- md5: ea274af685c81c435bb3c5f715d5c6b6   (md5(replace(pg_get_functiondef('public.combat_pool_act(numeric, numeric, integer, integer, numeric, integer, jsonb, boolean)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_pool_act(p_atk numeric, p_bmult numeric, p_round integer, p_stun_until integer, p_lost numeric, p_max integer, p_pool jsonb, p_charge boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_total numeric; v_r numeric; m jsonb; v_kind text := 'strike'; v_name text := 'Strike'; v_dmg int := 0; v_area numeric := 0;
  v_heal int := 0; v_hits int := 1; v_dot int := 0; v_guard int := 0;
  roll numeric := (public.balance_num('combat', 'roll_min') + random() * public.balance_num('combat', 'roll_span'));
  m2 jsonb := public.balance_get('pool_moves'); v_cyc int := (m2->>'cycle')::int;   -- balance_table.sql
begin
  if p_stun_until >= p_round then return jsonb_build_object('action', 'stunned', 'move', 'Stunned', 'dmg', 0, 'area', 0, 'heal', 0, 'hits', 0, 'dot', 0, 'guard', 0); end if;
  if p_charge and p_round % v_cyc = v_cyc - 1 then return jsonb_build_object('action', 'charging', 'move', 'Charging', 'dmg', 0, 'area', 0, 'heal', 0, 'hits', 0, 'dot', 0, 'guard', 0); end if;
  if p_charge and p_round % v_cyc = 0 then
    return jsonb_build_object('action', 'cataclysm', 'move', 'Cataclysm', 'dmg', greatest(1, round(p_atk * (m2->>'cataclysm_x')::numeric * roll * p_bmult)), 'area', (m2->>'cataclysm_area')::numeric, 'heal', 0, 'hits', 1, 'dot', 0, 'guard', 0);
  end if;
  select sum(coalesce((e->>'w')::numeric, 1)) into v_total from jsonb_array_elements(coalesce(p_pool, '[]')) e;
  if coalesce(v_total, 0) > 0 then
    v_r := random() * v_total;
    for m in select e from jsonb_array_elements(p_pool) e loop
      v_r := v_r - coalesce((m->>'w')::numeric, 1);
      if v_r <= 0 then v_kind := m->>'kind'; v_name := m->>'name'; exit; end if;
    end loop;
  end if;
  case v_kind
    when 'heavy' then v_dmg := greatest(1, round(p_atk * (m2->>'heavy_x')::numeric * roll * p_bmult));
    when 'flurry' then v_dmg := 2 * greatest(1, round(p_atk * (m2->>'flurry_x')::numeric * roll * p_bmult)); v_hits := 2;
    when 'slam' then v_dmg := greatest(1, round(p_atk * (m2->>'slam_x')::numeric * roll * p_bmult)); v_area := (m2->>'slam_x')::numeric;
    when 'drain' then v_dmg := greatest(1, round(p_atk * (m2->>'drain_x')::numeric * roll * p_bmult)); v_heal := greatest(1, round(p_max * (m2->>'drain_heal')::numeric));
    when 'stun' then v_dmg := greatest(1, round(p_atk * (m2->>'stun_x')::numeric * roll * p_bmult));
    when 'poison' then v_dmg := greatest(1, round(p_atk * (m2->>'poison_x')::numeric * roll * p_bmult)); v_dot := greatest(1, round(p_atk * (m2->>'poison_dot')::numeric * p_bmult));
    when 'regenerate' then v_heal := greatest(1, round(p_max * (case when p_lost >= public.balance_num('boss_moves', 'rage_at') then (m2->>'regenerate_heal_rage')::numeric else (m2->>'regenerate_heal')::numeric end))); v_hits := 0;
    when 'guard' then v_guard := greatest(1, round(p_max * (m2->>'guard')::numeric)); v_hits := 0;
    when 'enrage' then v_hits := 0;
    when 'curse' then v_hits := 0;
    else v_kind := 'strike'; v_dmg := greatest(1, round(p_atk * roll * p_bmult));
  end case;
  return jsonb_build_object('action', v_kind, 'move', v_name, 'dmg', v_dmg, 'area', v_area, 'heal', v_heal, 'hits', v_hits, 'dot', v_dot, 'guard', v_guard);
end $function$;
-- @grants public.combat_pool_act(numeric, numeric, integer, integer, numeric, integer, jsonb, boolean)
grant execute on function public.combat_pool_act(numeric, numeric, integer, integer, numeric, integer, jsonb, boolean) to postgres;
grant execute on function public.combat_pool_act(numeric, numeric, integer, integer, numeric, integer, jsonb, boolean) to service_role;
