-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_absorb(integer, integer)
-- md5: ac898264b1c53715b9c83a87b1e5ee67   (md5(replace(pg_get_functiondef('public.combat_absorb(integer, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_absorb(p_shield integer, p_dmg integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
declare v_absorb int := least(p_shield, p_dmg);
begin
  return jsonb_build_object('shield', p_shield - v_absorb, 'dmg', p_dmg - v_absorb);
end $function$;
-- @grants public.combat_absorb(integer, integer)
grant execute on function public.combat_absorb(integer, integer) to postgres;
grant execute on function public.combat_absorb(integer, integer) to service_role;
