-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_lifesteal(integer, numeric, integer)
-- md5: 749c45aebf0f3492923243d215e87f10   (md5(replace(pg_get_functiondef('public.combat_lifesteal(integer, numeric, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_lifesteal(p_dmg integer, p_aamt numeric, p_maxhp integer)
 RETURNS integer
 LANGUAGE sql
 STABLE
AS $function$
  select greatest(1, least(round(p_dmg * p_aamt), round(p_maxhp * public.balance_num('combat', 'lifesteal_cap'))))::int;
$function$;
-- @grants public.combat_lifesteal(integer, numeric, integer)
grant execute on function public.combat_lifesteal(integer, numeric, integer) to postgres;
grant execute on function public.combat_lifesteal(integer, numeric, integer) to service_role;
