-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_regen(bigint)
-- md5: 057593d348484bbd0a095029db9c6f1b   (md5(replace(pg_get_functiondef('public.combat_regen(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_regen(p_share bigint)
 RETURNS integer
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$ select greatest(1, round(p_share * public.balance_num('boss_passives', 'regenerating_heal')))::int; $function$;
-- @grants public.combat_regen(bigint)
grant execute on function public.combat_regen(bigint) to postgres;
grant execute on function public.combat_regen(bigint) to service_role;
