-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_aff_scale(integer)
-- md5: 7a4054dd69923c816ea97d8bab829ab8   (md5(replace(pg_get_functiondef('public.combat_aff_scale(integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_aff_scale(p_count integer)
 RETURNS numeric
 LANGUAGE sql
 STABLE
AS $function$ select least(public.balance_num('support', 'affinity_cap'), 1 + public.balance_num('support', 'affinity_step') * coalesce(p_count, 0)); $function$;
-- @grants public.combat_aff_scale(integer)
grant execute on function public.combat_aff_scale(integer) to postgres;
grant execute on function public.combat_aff_scale(integer) to service_role;
