-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_weak(jsonb, jsonb, text, text, text, text[], integer)
-- md5: 98c1aad65e30464beb60d98c4aa6e538   (md5(replace(pg_get_functiondef('public.combat_weak(jsonb, jsonb, text, text, text, text[], integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_weak(p_weak jsonb, p_resist jsonb, p_type text, p_rarity text, p_season text, p_tags text[], p_stack integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare v_wm int; v_rm int; v_wmult numeric;
begin
  select count(*) into v_wm from jsonb_array_elements(coalesce(p_weak, '[]'::jsonb)) w
    where (w->>'kind' = 'type'   and w->>'value' = p_type)
       or (w->>'kind' = 'rarity' and w->>'value' = p_rarity)
       or (w->>'kind' = 'season' and w->>'value' = p_season)
       or (w->>'kind' = 'tag'    and w->>'value' = any(p_tags));
  select count(*) into v_rm from jsonb_array_elements(coalesce(p_resist, '[]'::jsonb)) w
    where (w->>'kind' = 'type'   and w->>'value' = p_type)
       or (w->>'kind' = 'rarity' and w->>'value' = p_rarity)
       or (w->>'kind' = 'season' and w->>'value' = p_season)
       or (w->>'kind' = 'tag'    and w->>'value' = any(p_tags));
  v_wmult := 1
    + (1 - power(public.balance_num('combat', 'weak_step'), v_wm)) * (case when p_stack <= public.balance_num('combat', 'weak_stack_free') then 1 else power(public.balance_num('combat', 'weak_step'), p_stack - public.balance_num('combat', 'weak_stack_free')) end)
    - public.balance_num('combat', 'resist_step') * (1 - power(public.balance_num('combat', 'resist_decay'), v_rm));
  v_wmult := greatest(public.balance_num('combat', 'weak_min'), least(public.balance_num('combat', 'weak_max'), v_wmult));
  return jsonb_build_object('wm', v_wm, 'rm', v_rm, 'mult', v_wmult);
end $function$;
-- @grants public.combat_weak(jsonb, jsonb, text, text, text, text[], integer)
grant execute on function public.combat_weak(jsonb, jsonb, text, text, text, text[], integer) to postgres;
grant execute on function public.combat_weak(jsonb, jsonb, text, text, text, text[], integer) to service_role;
