-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_area_roll(numeric, numeric, numeric)
-- md5: 3bc160e59acb12ee213d174c96b7dcbb   (md5(replace(pg_get_functiondef('public.combat_area_roll(numeric, numeric, numeric)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_area_roll(p_atk numeric, p_area numeric, p_bmult numeric)
 RETURNS integer
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  select greatest(1, round(p_atk * p_area * (public.balance_num('combat', 'roll_min') + random() * public.balance_num('combat', 'roll_span')) * p_bmult))::int;
$function$;
-- @grants public.combat_area_roll(numeric, numeric, numeric)
grant execute on function public.combat_area_roll(numeric, numeric, numeric) to postgres;
grant execute on function public.combat_area_roll(numeric, numeric, numeric) to service_role;
