-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_thorns(integer)
-- md5: 8772b4f3c97adecc1b715bb33f9421e1   (md5(replace(pg_get_functiondef('public.combat_thorns(integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_thorns(p_dmg integer)
 RETURNS integer
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$ select greatest(1, round(p_dmg * public.balance_num('boss_passives', 'thorns')))::int; $function$;
-- @grants public.combat_thorns(integer)
grant execute on function public.combat_thorns(integer) to postgres;
grant execute on function public.combat_thorns(integer) to service_role;
