-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_stun_immune(integer, integer)
-- md5: b26ab5f7ae16903480af205f114b237f   (md5(replace(pg_get_functiondef('public.combat_stun_immune(integer, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_stun_immune(p_stun_until integer, p_round integer)
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select coalesce(p_stun_until, 0) > 0 and p_round < p_stun_until + public.balance_num('support', 'stun_immune_rounds');
$function$;
-- @grants public.combat_stun_immune(integer, integer)
grant execute on function public.combat_stun_immune(integer, integer) to postgres;
grant execute on function public.combat_stun_immune(integer, integer) to service_role;
