-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.combat_burn(numeric)
-- md5: 6ff4ba80af69a1490911ee69c8964972   (md5(replace(pg_get_functiondef('public.combat_burn(numeric)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.combat_burn(p_atk numeric)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if random() < public.balance_num('boss_passives', 'flaming_chance') then return greatest(1, round(p_atk * public.balance_num('boss_passives', 'flaming_x') * (public.balance_num('combat', 'roll_min') + random() * public.balance_num('combat', 'roll_span'))))::int; end if;
  return 0;
end $function$;
-- @grants public.combat_burn(numeric)
grant execute on function public.combat_burn(numeric) to postgres;
grant execute on function public.combat_burn(numeric) to service_role;
