-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.confirm_bid(text, bigint)
-- md5: 6ac442cd582125b90b0a0de03b03b009   (md5(replace(pg_get_functiondef('public.confirm_bid(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.confirm_bid(p_bidder text, p_auction bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare a auctions; b auction_bids; x bigint;
begin
  select * into a from auctions where id = p_auction for update;
  if not found or a.status <> 'accepted' then return jsonb_build_object('ok', false, 'error', 'not_accepted'); end if;
  select * into b from auction_bids where id = a.accepted_bid_id for update;
  if b.bidder_id <> p_bidder or b.status <> 'accepted' then return jsonb_build_object('ok', false, 'error', 'not_your_bid'); end if;
  begin
    if card_move(a.seller_id, a.card_id, -1, 'auction', 'auction', a.id::text) is null then raise exception 'gone'; end if;
    foreach x in array b.cards loop
      if card_move(p_bidder, x, -1, 'auction', 'auction', a.id::text) is null then raise exception 'gone'; end if;
      perform card_move(a.seller_id, x, 1, 'auction', 'auction', a.id::text, 'auction');
    end loop;
    perform card_move(p_bidder, a.card_id, 1, 'auction', 'auction', a.id::text, 'auction');
  exception when others then
    return jsonb_build_object('ok', false, 'error', 'cards_gone');
  end;
  update auction_bids set status = 'won', updated_at = now() where id = b.id;
  perform return_bids(a.id, b.id);
  update auctions set status = 'sold', settled_at = now(), notice_dirty = true where id = a.id;
  return jsonb_build_object('ok', true, 'seller', a.seller_id, 'card_id', a.card_id, 'cards', b.cards);
end $function$;
-- @grants public.confirm_bid(text, bigint)
grant execute on function public.confirm_bid(text, bigint) to postgres;
grant execute on function public.confirm_bid(text, bigint) to service_role;
