-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.convert_dupes(text, bigint, integer)
-- md5: c1afa328d3a94dba53074edc0b040832   (md5(replace(pg_get_functiondef('public.convert_dupes(text, bigint, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.convert_dupes(p_player text, p_card bigint, p_count integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := shard_cfg(); v_rar text; v_val int; v_max int; v_new int; v_row bigint;
begin
  if not coalesce((cfg->>'enabled')::boolean, false) then return jsonb_build_object('ok', false, 'error', 'disabled'); end if;
  if p_count is null or p_count < 1 then return jsonb_build_object('ok', false, 'error', 'bad_count'); end if;
  perform 1 from players where id = p_player for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'no_player'); end if;
  select c.rarity::text into v_rar from player_cards pc join cards c on c.id = pc.card_id
   where pc.player_id = p_player and pc.card_id = p_card and pc.quantity > 0 for update of pc;
  if not found then return jsonb_build_object('ok', false, 'error', 'not_owned'); end if;
  v_val := (cfg->'dupe_values'->>v_rar)::int;
  if v_val is null or v_val <= 0 then return jsonb_build_object('ok', false, 'error', 'no_value'); end if;
  v_max := convertible_copies(p_player, p_card);
  if p_count > v_max then return jsonb_build_object('ok', false, 'error', 'too_many', 'max', v_max); end if;
  v_new := grant_shards(p_player, p_count * v_val, 'dupes', 'card', p_card::text);
  -- The copies leave with a ref to the Shards row they paid for (the copies are recorded, not rebuilt
  -- from the Shards with today's dupe value).
  select id into v_row from shard_ledger
   where player_id = p_player and reason = 'dupes' and ref_kind = 'card' and ref_id = p_card::text and created_at = now()
   order by id desc limit 1;
  perform card_move(p_player, p_card, -p_count, 'convert', 'shard_ledger', v_row::text);
  return jsonb_build_object('ok', true, 'converted', p_count, 'shards', p_count * v_val, 'balance', v_new,
    'quantity', (select quantity from player_cards where player_id = p_player and card_id = p_card));
end $function$;
-- @grants public.convert_dupes(text, bigint, integer)
grant execute on function public.convert_dupes(text, bigint, integer) to postgres;
grant execute on function public.convert_dupes(text, bigint, integer) to service_role;
