-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.counter_trade(bigint, text, bigint)
-- md5: 0f275c9568d128a509b1e89c8e8bfc35   (md5(replace(pg_get_functiondef('public.counter_trade(bigint, text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.counter_trade(p_offer_id bigint, p_actor text, p_card bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare t record; ro record; rr record;
begin
  select * into t from trade_offers where id = p_offer_id and status = 'pending' and request_card_id is null for update;
  if not found or t.to_id <> p_actor then return false; end if;
  if p_card = t.offer_card_id then return false; end if;
  select rarity::text as rarity into ro from cards where id = t.offer_card_id;
  select rarity::text as rarity, tradeable into rr from cards where id = p_card;
  if not found or not rr.tradeable or rr.rarity <> ro.rarity then return false; end if;
  if free_copies(p_actor, p_card) < 1 then return false; end if;
  update trade_offers set request_card_id = p_card, status = 'countered', countered_at = now() where id = p_offer_id;
  return true;
end; $function$;
-- @grants public.counter_trade(bigint, text, bigint)
grant execute on function public.counter_trade(bigint, text, bigint) to postgres;
grant execute on function public.counter_trade(bigint, text, bigint) to service_role;
