-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.daily_raid_board(timestamp with time zone)
-- md5: 3fde3247f874002a0e2ad6c83ec3e1cf   (md5(replace(pg_get_functiondef('public.daily_raid_board(timestamp with time zone)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.daily_raid_board(p_at timestamp with time zone DEFAULT now())
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare h hunts; d date := (p_at at time zone 'America/Denver')::date;
begin
  if not hunt_mt_slot('board', p_at) then return false; end if;
  select * into h from hunts where status = 'active' order by id desc limit 1;
  if not found then return false; end if;
  -- One a day: the event keeps its MT day.
  if exists (select 1 from hunt_events where hunt_id = h.id and kind = 'leaderboard' and payload->>'day' = d::text) then return false; end if;
  insert into hunt_events (hunt_id, kind, payload)
  values (h.id, 'leaderboard', jsonb_build_object('day', d, 'name', h.name, 'tier', h.tier, 'hp_remaining', h.hp_remaining, 'hp_max', h.hp_max,
    'closes_at', h.closes_at,
    'top', coalesce((select jsonb_agg(jsonb_build_object('player_id', l.player_id, 'username', l.username, 'damage', l.damage, 'avatar', p.avatar) order by l.damage desc)
                     from hunt_leaderboard(h.id, 10) l join players p on p.id = l.player_id), '[]'::jsonb)));
  return true;
end $function$;
-- @grants public.daily_raid_board(timestamp with time zone)
grant execute on function public.daily_raid_board(timestamp with time zone) to postgres;
grant execute on function public.daily_raid_board(timestamp with time zone) to service_role;
