-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_log_add(bigint, jsonb, jsonb)
-- md5: c5c43dd43b6ea4f027b8cb7e0b69fed9   (md5(replace(pg_get_functiondef('public.dungeon_log_add(bigint, jsonb, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_log_add(p_run bigint, p_action jsonb, p_result jsonb)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  insert into dungeon_log (run_id, n, action, result)
    values (p_run, coalesce((select max(n) from dungeon_log where run_id = p_run), 0) + 1, p_action, p_result);
$function$;
-- @grants public.dungeon_log_add(bigint, jsonb, jsonb)
grant execute on function public.dungeon_log_add(bigint, jsonb, jsonb) to postgres;
grant execute on function public.dungeon_log_add(bigint, jsonb, jsonb) to service_role;
