-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_card_of(text)
-- md5: 2a19d3471678cf52a3308d02cae8d870   (md5(replace(pg_get_functiondef('public.dungeon_card_of(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_card_of(p_rarity text)
 RETURNS bigint
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  select id from cards where rarity::text = p_rarity and source::text = 'draw' and in_draw_pool order by random() limit 1;
$function$;
-- @grants public.dungeon_card_of(text)
grant execute on function public.dungeon_card_of(text) to postgres;
grant execute on function public.dungeon_card_of(text) to service_role;
