-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_txt(jsonb)
-- md5: 1dcc4cbfdd6c1ca15442aef12b344124   (md5(replace(pg_get_functiondef('public.dungeon_txt(jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_txt(p jsonb)
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select coalesce(array(select jsonb_array_elements_text(coalesce(p, '[]'::jsonb))), '{}');
$function$;
-- @grants public.dungeon_txt(jsonb)
grant execute on function public.dungeon_txt(jsonb) to postgres;
grant execute on function public.dungeon_txt(jsonb) to service_role;
