-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_hp_event(text, text, bigint, bigint, integer, integer, text, text, integer, jsonb, jsonb)
-- md5: 87f926df42c0bde2f6ae75702d1ca848   (md5(replace(pg_get_functiondef('public.dungeon_hp_event(text, text, bigint, bigint, integer, integer, text, text, integer, jsonb, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_hp_event(p_kind text, p_effect text, p_card bigint, p_target_card bigint, p_target_foe integer, p_round integer, p_side text, p_dir text, p_value integer, p_target jsonb, p_extra jsonb)
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object('kind', p_kind, 'effect', p_effect, 'card', p_card, 'target_card', p_target_card, 'target_foe', p_target_foe,
    'round', p_round, 'result', jsonb_build_object('side', p_side, 'dir', p_dir, 'value', p_value,
      'hp_after', (p_target->>'hp')::int, 'max', (p_target->>'max')::int) || coalesce(p_extra, '{}'::jsonb));
$function$;
-- @grants public.dungeon_hp_event(text, text, bigint, bigint, integer, integer, text, text, integer, jsonb, jsonb)
grant execute on function public.dungeon_hp_event(text, text, bigint, bigint, integer, integer, text, text, integer, jsonb, jsonb) to postgres;
grant execute on function public.dungeon_hp_event(text, text, bigint, bigint, integer, integer, text, text, integer, jsonb, jsonb) to service_role;
