-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_settle_stale()
-- md5: 427240d67aa2e15e078f7d18db7ea414   (md5(replace(pg_get_functiondef('public.dungeon_settle_stale()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_settle_stale()
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare r record; n int := 0;
begin
  for r in select id from dungeon_runs where status = 'active' and day < dungeon_day() loop
    perform dungeon_settle(r.id, 'abandoned', false); n := n + 1;
  end loop;
  return n;
end $function$;
-- @grants public.dungeon_settle_stale()
grant execute on function public.dungeon_settle_stale() to postgres;
grant execute on function public.dungeon_settle_stale() to service_role;
