-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_offers(jsonb, integer)
-- md5: d3cf95a36e58db2081ac6a57e63e55a5   (md5(replace(pg_get_functiondef('public.dungeon_offers(jsonb, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_offers(p_state jsonb, p_floor integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare pool text[] := case when p_state->>'mode' = 'gauntlet' then array['heal','buff','ward','reset','revive']   -- the Gauntlet: no loot
    else array['heal','buff','shards','card','ward','reset','revive'] end; v jsonb := '[]'; k text; t int; n int := 0;
  amt numeric; tries int := 0;
  healed boolean := coalesce((p_state->>'heal_floor')::int, 0) = p_floor;
begin
  while n < 3 and tries < 40 loop
    tries := tries + 1;
    k := pool[1 + floor(random() * array_length(pool, 1))::int];
    continue when k = p_state->>'last_pick';
    continue when k in ('heal', 'revive') and healed;
    continue when exists (select 1 from jsonb_array_elements(v) o where o->>'kind' = k);
    t := dungeon_tier(random());
    -- The least tier of a reset / revive and the amounts by tier (1 to 5) are in balance dungeon_rewards.offers.
    continue when k in ('reset', 'revive') and t < balance_num('dungeon_rewards', 'offers', 'min_tier', k);
    continue when k = 'revive' and not exists (select 1 from jsonb_each(p_state->'cards') c where (c.value->>'down')::boolean);
    amt := case when k = 'shards' then balance_num('dungeon_rewards', 'offers', 'shards', (t - 1)::text) + balance_num('dungeon_rewards', 'offers', 'shards_per_floor') * p_floor
                when k in ('heal', 'buff', 'ward', 'revive') then balance_num('dungeon_rewards', 'offers', k, (t - 1)::text)
                else 0 end;
    v := v || jsonb_build_object('kind', k, 'tier', t, 'amount', amt,   -- a card rolls its rarity when picked; the offer shows the odds
      'odds', case when k = 'card' then dungeon_cfg()->'chest_rarity'->(t::text) end);
    n := n + 1;
  end loop;
  return v;
end $function$;
-- @grants public.dungeon_offers(jsonb, integer)
grant execute on function public.dungeon_offers(jsonb, integer) to postgres;
grant execute on function public.dungeon_offers(jsonb, integer) to service_role;
