-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_pick(jsonb, numeric)
-- md5: 03ebd66d9ddb038214715fdd7f2389bb   (md5(replace(pg_get_functiondef('public.dungeon_pick(jsonb, numeric)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_pick(p_weights jsonb, p_x numeric)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
declare v_total numeric; v_r numeric; k text; w numeric;
begin
  select sum(value::numeric) into v_total from jsonb_each_text(p_weights);
  v_r := p_x * v_total;
  for k, w in select key, value::numeric from jsonb_each_text(p_weights) order by key loop
    v_r := v_r - w;
    if v_r <= 0 then return k; end if;
  end loop;
  return k;
end $function$;
-- @grants public.dungeon_pick(jsonb, numeric)
grant execute on function public.dungeon_pick(jsonb, numeric) to postgres;
grant execute on function public.dungeon_pick(jsonb, numeric) to service_role;
