-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_day()
-- md5: 7db7cd2c2d987863d0ab460d4ee9ae1c   (md5(replace(pg_get_functiondef('public.dungeon_day()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_day()
 RETURNS date
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$ select public.game_day(); $function$;
-- @grants public.dungeon_day()
grant execute on function public.dungeon_day() to postgres;
grant execute on function public.dungeon_day() to service_role;
