-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_settle(bigint, text, boolean)
-- md5: 6c71965b6ec5f325566aeb9d65053a9e   (md5(replace(pg_get_functiondef('public.dungeon_settle(bigint, text, boolean)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_settle(p_run_id bigint, p_how text, p_with_pend boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare r dungeon_runs; v_sh int; v_cards jsonb; x jsonb;
begin
  select * into r from dungeon_runs where id = p_run_id for update;
  if r.status <> 'active' then return jsonb_build_object('shards', r.shards, 'cards', to_jsonb(r.cards)); end if;
  if r.mode = 'gauntlet' then r.state := r.state - 'bank' - 'pend'; end if;   -- the Gauntlet grants no loot
  v_sh := coalesce((r.state->'bank'->>'shards')::int, 0) + case when p_with_pend then coalesce((r.state->'pend'->>'shards')::int, 0) else 0 end;
  v_cards := coalesce(r.state->'bank'->'cards', '[]') || case when p_with_pend then coalesce(r.state->'pend'->'cards', '[]') else '[]'::jsonb end;
  if v_sh > 0 then perform grant_shards(r.player_id, v_sh, 'dungeon', 'run', r.id::text); end if;
  -- Each card with the ref of THIS run (shard_ledger_strict.sql): add_card_to_player found 'the newest active run that
  -- holds the card', the wrong run when a member has two active runs (a daily and a Gauntlet run, or a stale one).
  for x in select e from jsonb_array_elements(v_cards) e loop
    perform card_move(r.player_id, (x #>> '{}')::bigint, 1, 'dungeon_loot', 'dungeon_run', r.id::text, 'dungeon');
  end loop;
  update dungeon_runs set status = 'over', ended_by = p_how, ended_at = now(), shards = v_sh,
    cards = coalesce(array(select (e #>> '{}')::bigint from jsonb_array_elements(v_cards) e), '{}'),
    state = jsonb_set(state, '{phase}', '"over"') || jsonb_build_object('lost', case when p_with_pend then null else state->'pend' end)
  where id = r.id;
  return jsonb_build_object('shards', v_sh, 'cards', v_cards);
end $function$;
-- @grants public.dungeon_settle(bigint, text, boolean)
grant execute on function public.dungeon_settle(bigint, text, boolean) to postgres;
grant execute on function public.dungeon_settle(bigint, text, boolean) to service_role;
