-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_day()
-- md5: ceb95aca6a78dffb585e4b2124e2a124   (md5(replace(pg_get_functiondef('public.dungeon_day()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_day()
 RETURNS date
 LANGUAGE sql
 STABLE
AS $function$ select public.game_day(); $function$;
-- @grants public.dungeon_day()
grant execute on function public.dungeon_day() to postgres;
grant execute on function public.dungeon_day() to service_role;
