-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_generate(date)
-- md5: d10382ccff17aaf938267f62068490af   (md5(replace(pg_get_functiondef('public.dungeon_generate(date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_generate(p_day date)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := dungeon_cfg(); k text := coalesce(cfg->>'salt', 'lion') || '|' || p_day::text;
  v_floors jsonb := '[]'; v_rooms jsonb; v_type text; f int; r int; v_rule jsonb; v_name text; rk text;
  names text[] := array['The Sunken Crypt','The Ember Halls','Frostfang Caverns','The Rotting Grove','The Clockwork Depths','Shadowmere Keep','The Hollow Mines','Stormspire Tower'];
  w jsonb := balance_get('dungeon')->'room_weights';   -- balance dungeon.room_weights (balance_check_settings checks the shape)
begin
  if exists (select 1 from dungeon_days where day = p_day) then return (select to_jsonb(d) from dungeon_days d where day = p_day); end if;
  v_rule := dungeon_rules() -> (floor(dungeon_rand(k || '|rule') * jsonb_array_length(dungeon_rules())))::int;
  v_name := names[1 + floor(dungeon_rand(k || '|name') * array_length(names, 1))::int];
  for f in 1..balance_num('dungeon', 'floors')::int loop
    v_rooms := '[]';
    for r in 1..5 loop
      rk := k || '|' || f || '|' || r;
      v_type := case when r = 5 then 'guardian' when r = 1 then 'fight' else dungeon_pick(w, dungeon_rand(rk || '|t')) end;
      v_rooms := v_rooms || jsonb_build_object('type', v_type,
        'foes', case when v_type in ('fight', 'horde', 'elite', 'miniboss', 'guardian') then dungeon_room_foes(rk, f, r, v_type) else '[]'::jsonb end);
    end loop;
    v_floors := v_floors || jsonb_build_array(v_rooms);
  end loop;
  insert into dungeon_days (day, name, rule, floors) values (p_day, v_name, v_rule, v_floors) on conflict (day) do nothing;
  return (select to_jsonb(d) from dungeon_days d where day = p_day);
end $function$;
-- @grants public.dungeon_generate(date)
grant execute on function public.dungeon_generate(date) to postgres;
grant execute on function public.dungeon_generate(date) to service_role;
