-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_card_base(bigint)
-- md5: 308e136c5197419746ca0eef9cc5fad0   (md5(replace(pg_get_functiondef('public.dungeon_card_base(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_card_base(p_card bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object('id', c.id, 'name', c.name, 'type', s.type, 'rarity', c.rarity::text, 'season', c.season,
    'tags', coalesce(to_jsonb(s.tag_slugs), '[]'::jsonb), 'ability', s.ability,
    'cmb', card_combat(c.rarity::text, 0, s.cp_mod, '{}'::jsonb))
  from cards c join subjects s on s.id = c.subject_id where c.id = p_card;
$function$;
-- @grants public.dungeon_card_base(bigint)
grant execute on function public.dungeon_card_base(bigint) to postgres;
grant execute on function public.dungeon_card_base(bigint) to service_role;
