-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_card(text, bigint)
-- md5: 71ccd32ce017a6bddb7c8ea73a2fda34   (md5(replace(pg_get_functiondef('public.dungeon_card(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_card(p_player text, p_card bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object('id', c.id, 'name', c.name, 'type', s.type, 'rarity', c.rarity::text, 'season', c.season,
    'tags', coalesce(to_jsonb(s.tag_slugs), '[]'::jsonb), 'ability', s.ability,
    'cmb', card_combat(c.rarity::text, pc.ascension, s.cp_mod, pc.stat_points))
  from player_cards pc join cards c on c.id = pc.card_id join subjects s on s.id = c.subject_id
  where pc.player_id = p_player and pc.card_id = p_card and pc.quantity > 0;
$function$;
-- @grants public.dungeon_card(text, bigint)
grant execute on function public.dungeon_card(text, bigint) to postgres;
grant execute on function public.dungeon_card(text, bigint) to service_role;
