-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_rand(text)
-- md5: 7225e507132c6fccdc306b8922314983   (md5(replace(pg_get_functiondef('public.dungeon_rand(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_rand(p_key text)
 RETURNS numeric
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select (('x' || substr(md5(p_key), 1, 8))::bit(32)::bigint & 2147483647)::numeric / 2147483647;
$function$;
-- @grants public.dungeon_rand(text)
grant execute on function public.dungeon_rand(text) to postgres;
grant execute on function public.dungeon_rand(text) to service_role;
