-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_combat_log(dungeon_runs, jsonb)
-- md5: 517a1b325cf0631a747e14011abd85c6   (md5(replace(pg_get_functiondef('public.dungeon_combat_log(dungeon_runs, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_combat_log(p_run dungeon_runs, p_events jsonb)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  insert into combat_actions (mode, ref_id, player_id, card_id, kind, game_day, round, effect, amount, target_card, target_foe, result)
  select case when p_run.mode = 'gauntlet' then 'gauntlet' else 'dungeon' end, p_run.id, p_run.player_id, (x.e->>'card')::bigint, x.e->>'kind',
         p_run.day, (x.e->>'round')::int, x.e->>'effect', (x.e->>'amount')::numeric, (x.e->>'target_card')::bigint, (x.e->>'target_foe')::int,
         jsonb_build_object('floor', p_run.floor, 'room', p_run.room) || coalesce(x.e->'result', '{}'::jsonb)
    from jsonb_array_elements(coalesce(p_events, '[]'::jsonb)) with ordinality x(e, n)
   order by x.n;
$function$;
-- @grants public.dungeon_combat_log(dungeon_runs, jsonb)
grant execute on function public.dungeon_combat_log(dungeon_runs, jsonb) to postgres;
grant execute on function public.dungeon_combat_log(dungeon_runs, jsonb) to service_role;
