-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_drop_rarity(integer)
-- md5: 81c578307589df996abe4c339b8ad149   (md5(replace(pg_get_functiondef('public.dungeon_drop_rarity(integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_drop_rarity(p_floor integer)
 RETURNS text
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare t jsonb; x numeric := random();
begin
  select e into t from jsonb_array_elements(dungeon_cfg()->'loot') e where p_floor <= (e->>'to')::int order by (e->>'to')::int limit 1;
  return case when x < coalesce((t->>'secret_rare')::numeric, 0) then 'secret_rare'
              when x < coalesce((t->>'secret_rare')::numeric, 0) + coalesce((t->>'illustrated_rare')::numeric, 0) then 'illustrated_rare'
              else 'normal' end;
end $function$;
-- @grants public.dungeon_drop_rarity(integer)
grant execute on function public.dungeon_drop_rarity(integer) to postgres;
grant execute on function public.dungeon_drop_rarity(integer) to service_role;
