-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_loot(jsonb, integer, bigint)
-- md5: c38e5fa135740a51c895687b11e9f83c   (md5(replace(pg_get_functiondef('public.dungeon_loot(jsonb, integer, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_loot(p_state jsonb, p_shards integer, p_card bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare st jsonb := p_state; cap int := coalesce((dungeon_cfg()->>'run_shards_cap')::int, 300);
  have int := coalesce((p_state->'bank'->>'shards')::int, 0) + coalesce((p_state->'pend'->>'shards')::int, 0);
  add int := greatest(0, least(coalesce(p_shards, 0), cap - have));
begin
  st := jsonb_set(st, '{pend}', coalesce(st->'pend', '{"shards":0,"cards":[]}') || jsonb_build_object(
    'shards', coalesce((st->'pend'->>'shards')::int, 0) + add,
    'cards', coalesce(st->'pend'->'cards', '[]') || case when p_card is null then '[]'::jsonb else jsonb_build_array(p_card) end));
  return st;
end $function$;
-- @grants public.dungeon_loot(jsonb, integer, bigint)
grant execute on function public.dungeon_loot(jsonb, integer, bigint) to postgres;
grant execute on function public.dungeon_loot(jsonb, integer, bigint) to service_role;
