-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_rules()
-- md5: 15eaffffa2c3cb225b65c07cbfa5a9f3   (md5(replace(pg_get_functiondef('public.dungeon_rules()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_rules()
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select jsonb_build_array(
    jsonb_build_object('name', 'Creatures and Items only', 'note', 'Heroes, Spells and Memes stay home today.', 'types', jsonb_build_array('Creature', 'Item')),
    jsonb_build_object('name', 'Characters and Moments only', 'note', 'Only people and big moments today.', 'types', jsonb_build_array('Character', 'Moment')),
    jsonb_build_object('name', 'Characters and Places only', 'note', 'Bring your heroes and their home turf.', 'types', jsonb_build_array('Character', 'Place')),
    jsonb_build_object('name', 'No Gold today', 'note', 'Gold cards rest today.', 'no_rarity', jsonb_build_array('gold')),
    jsonb_build_object('name', 'Fire cards deal +25%', 'note', 'Bring the heat.', 'boost_tag', 'trait:fire', 'boost', 0.25),
    jsonb_build_object('name', 'Water cards deal +25%', 'note', 'Make a splash.', 'boost_tag', 'trait:water', 'boost', 0.25),
    jsonb_build_object('name', 'Shadow cards deal +25%', 'note', 'Lights out.', 'boost_tag', 'trait:shadow', 'boost', 0.25),
    jsonb_build_object('name', 'A budget of 9', 'note', 'Do more with less.', 'budget', 9),
    jsonb_build_object('name', 'Everything goes', 'note', 'Any card, the normal budget.'));
$function$;
-- @grants public.dungeon_rules()
grant execute on function public.dungeon_rules() to postgres;
grant execute on function public.dungeon_rules() to service_role;
