-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_hp_changes(jsonb, jsonb, text, integer, integer)
-- md5: 7c0c99c295f46da4806bfc87b063c8e9   (md5(replace(pg_get_functiondef('public.dungeon_hp_changes(jsonb, jsonb, text, integer, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_hp_changes(p_before jsonb, p_after jsonb, p_effect text, p_floor integer, p_room integer)
 RETURNS jsonb
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_agg(jsonb_build_object('kind', 'effect', 'effect', p_effect, 'target_card', a.key::bigint,
      'result', jsonb_build_object('side', 'card', 'dir', case when (a.value->>'hp')::int > (b.value->>'hp')::int then 'heal' else 'dmg' end,
        'value', abs((a.value->>'hp')::int - (b.value->>'hp')::int), 'hp_before', (b.value->>'hp')::int, 'hp_after', (a.value->>'hp')::int,
        'max', (a.value->>'max')::int, 'revived', coalesce((b.value->>'down')::boolean, false) and not coalesce((a.value->>'down')::boolean, false),
        'floor', p_floor, 'room', p_room))
      order by a.key::bigint), '[]'::jsonb)
    from jsonb_each(coalesce(p_after->'cards', '{}'::jsonb)) a join jsonb_each(coalesce(p_before->'cards', '{}'::jsonb)) b on b.key = a.key
   where (a.value->>'hp')::int is distinct from (b.value->>'hp')::int;
$function$;
-- @grants public.dungeon_hp_changes(jsonb, jsonb, text, integer, integer)
grant execute on function public.dungeon_hp_changes(jsonb, jsonb, text, integer, integer) to postgres;
grant execute on function public.dungeon_hp_changes(jsonb, jsonb, text, integer, integer) to service_role;
