-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_tier(double precision)
-- md5: b62e10111584d651cb4718f9d0488eef   (md5(replace(pg_get_functiondef('public.dungeon_tier(double precision)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_tier(p_x double precision)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare w jsonb := balance_get('dungeon_rewards')->'tier_weights'; v_total numeric := 0; v_r numeric; i int;   -- balance dungeon_rewards.tier_weights
begin
  if jsonb_typeof(w) is distinct from 'array' then raise exception 'balance: no array at dungeon_rewards.tier_weights'; end if;
  for i in 0..jsonb_array_length(w) - 1 loop v_total := v_total + (w->>i)::numeric; end loop;
  v_r := p_x * v_total;
  for i in 0..jsonb_array_length(w) - 1 loop
    v_r := v_r - (w->>i)::numeric;
    if v_r <= 0 then return i + 1; end if;
  end loop;
  return 1;
end $function$;
-- @grants public.dungeon_tier(double precision)
grant execute on function public.dungeon_tier(double precision) to postgres;
grant execute on function public.dungeon_tier(double precision) to service_role;
