-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_prize_tick()
-- md5: 5300f541d81b66010ff65074027e89fa   (md5(replace(pg_get_functiondef('public.dungeon_prize_tick()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_prize_tick()
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare pz jsonb := dungeon_prizes_cfg(); v_from date; d date; v jsonb := '[]'; x jsonb;
begin
  if not coalesce((pz->>'enabled')::boolean, false) then return jsonb_build_object('ok', false, 'error', 'disabled'); end if;
  v_from := coalesce((pz->>'from')::date, dungeon_day());
  for d in select g::date from generate_series(greatest(v_from, dungeon_day() - 7), dungeon_day() - 1, interval '1 day') g loop
    continue when exists (select 1 from dungeon_payouts where mode = 'daily' and period = d);
    x := dungeon_pay('daily', d); v := v || x;
  end loop;
  d := gauntlet_week(dungeon_day()) - 7;   -- the last finished week
  if d >= gauntlet_week(v_from) and not exists (select 1 from dungeon_payouts where mode = 'gauntlet' and period = d) then
    x := dungeon_pay('gauntlet', d); v := v || x;
  end if;
  return jsonb_build_object('ok', true, 'paid', v);
end $function$;
-- @grants public.dungeon_prize_tick()
grant execute on function public.dungeon_prize_tick() to postgres;
grant execute on function public.dungeon_prize_tick() to service_role;
