-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_cfg()
-- md5: 7bcbe6253212fddee36af721f2252508   (md5(replace(pg_get_functiondef('public.dungeon_cfg()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_cfg()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  -- settings.dungeon holds the flag and the seed salt only. Every number is in balance: dungeon (the fight and run rules,
  -- balance_settings_numbers.sql) and dungeon_rewards (Shards, loot, chest odds, room rewards).
  select coalesce((select value from settings where key = 'dungeon'), '{}'::jsonb) || balance_get('dungeon') || balance_get('dungeon_rewards');
$function$;
-- @grants public.dungeon_cfg()
grant execute on function public.dungeon_cfg() to postgres;
grant execute on function public.dungeon_cfg() to service_role;
