-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_chest_rarity(integer)
-- md5: ed9273ac7392b63094c7bc3fbeeefb90   (md5(replace(pg_get_functiondef('public.dungeon_chest_rarity(integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_chest_rarity(p_tier integer)
 RETURNS text
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare w jsonb := coalesce(dungeon_cfg()->'chest_rarity'->(least(5, greatest(1, p_tier)))::text, '[100,0,0]'); n numeric; i numeric; x numeric;
begin
  n := coalesce((w->>0)::numeric, 0); i := coalesce((w->>1)::numeric, 0); x := random() * greatest(n + i + coalesce((w->>2)::numeric, 0), 1);
  return case when x < n then 'normal' when x < n + i then 'illustrated_rare' else 'secret_rare' end;
end $function$;
-- @grants public.dungeon_chest_rarity(integer)
grant execute on function public.dungeon_chest_rarity(integer) to postgres;
grant execute on function public.dungeon_chest_rarity(integer) to service_role;
