-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_run_card(dungeon_runs, bigint)
-- md5: fad09e2678e28adc54ef1f6e62275273   (md5(replace(pg_get_functiondef('public.dungeon_run_card(dungeon_runs, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_run_card(p_run dungeon_runs, p_card bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select case when p_run.mode = 'gauntlet' then case when p_card = any(p_run.squad) then dungeon_card_base(p_card) end
              else dungeon_card(p_run.player_id, p_card) end;
$function$;
-- @grants public.dungeon_run_card(dungeon_runs, bigint)
grant execute on function public.dungeon_run_card(dungeon_runs, bigint) to postgres;
grant execute on function public.dungeon_run_card(dungeon_runs, bigint) to service_role;
