-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_run_floors(dungeon_runs)
-- md5: 5fceabe609be4c7fac3ab081fba8b38d   (md5(replace(pg_get_functiondef('public.dungeon_run_floors(dungeon_runs)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_run_floors(p_run dungeon_runs)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select case when p_run.mode = 'gauntlet' then (select floors from gauntlet_weeks where week = gauntlet_week(p_run.day))
              else (select floors from dungeon_days where day = p_run.day) end;
$function$;
-- @grants public.dungeon_run_floors(dungeon_runs)
grant execute on function public.dungeon_run_floors(dungeon_runs) to postgres;
grant execute on function public.dungeon_run_floors(dungeon_runs) to service_role;
