-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.dungeon_room_foes(text, integer, integer, text)
-- md5: 8a2604c9b155eb7b8c0aa1a38ebadbaa   (md5(replace(pg_get_functiondef('public.dungeon_room_foes(text, integer, integer, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.dungeon_room_foes(p_k text, p_floor integer, p_room integer, p_type text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare v jsonb := '[]'; n int; i int;
begin
  n := case p_type when 'fight' then 1 + floor(dungeon_rand(p_k || '|n') * 3)::int when 'horde' then 4 + floor(dungeon_rand(p_k || '|n') * 2)::int else 1 end;
  for i in 1..n loop
    v := v || dungeon_make_foe(p_k || '|' || i, p_floor, p_room, case p_type when 'fight' then 'fight' when 'horde' then 'horde' else p_type end);
  end loop;
  return v;
end $function$;
-- @grants public.dungeon_room_foes(text, integer, integer, text)
grant execute on function public.dungeon_room_foes(text, integer, integer, text) to postgres;
grant execute on function public.dungeon_room_foes(text, integer, integer, text) to service_role;
