-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.effect_preview_card(text, integer, jsonb, jsonb)
-- md5: 6f66966f0b6ff034e6d6d3c283fef9ab   (md5(replace(pg_get_functiondef('public.effect_preview_card(text, integer, jsonb, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.effect_preview_card(p_rarity text, p_asc integer, p_pts jsonb, p_effect jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare v_prim effect_primitives%rowtype; v_tiers jsonb; v_ascset jsonb; v_cmb jsonb; v_scale numeric;
  v_power numeric; v_cd numeric; v_pmul numeric; v_cmul numeric; v_amount numeric; v_dur int;
begin
  if p_effect is null or p_effect->>'primitive' is null then return null; end if;
  select * into v_prim from effect_primitives where primitive = p_effect->>'primitive';
  v_tiers := balance_get('effect_tiers');
  v_power := coalesce((v_tiers->p_rarity->>'power')::numeric, 1);
  v_cd    := coalesce((v_tiers->p_rarity->>'cd')::numeric, 1);
  v_ascset := balance_get('effect_ascension');
  v_cmb := card_combat(p_rarity, coalesce(p_asc, 0), 1, p_pts);
  if (v_cmb->>'on')::boolean then
    v_pmul := (v_cmb->>'potency')::numeric;
    v_cmul := (v_cmb->>'haste')::numeric;
  else
    v_pmul := 1 + coalesce((v_ascset->>'power_per_star')::numeric, 0) * coalesce(p_asc, 0);
    v_cmul := greatest((v_ascset->>'cd_floor')::numeric, 1 - coalesce((v_ascset->>'cd_per_star')::numeric, 0) * coalesce(p_asc, 0));
  end if;
  v_power := v_power * v_pmul;
  v_cd    := v_cd * v_cmul;
  v_scale := (balance_get('effect_cooldown_scale') #>> '{}')::numeric;
  v_cd    := v_cd * coalesce(v_scale, 1);
  v_amount := round((p_effect->'base'->>'amount')::numeric * v_power, 2);
  v_dur    := round((p_effect->'base'->>'duration_s')::numeric * v_power)::int;
  if v_prim.max_amount is not null then v_amount := least(v_amount, v_prim.max_amount); end if;
  if v_prim.max_duration_s is not null then v_dur := least(v_dur, v_prim.max_duration_s); end if;
  return jsonb_build_object('primitive', p_effect->>'primitive', 'kind', v_prim.kind, 'enabled', coalesce(v_prim.enabled, false),
    'amount', v_amount, 'duration_s', v_dur, 'cooldown_h', coalesce((p_effect->>'cooldown_h')::numeric, 24) * v_cd,
    'stats_on', coalesce((v_cmb->>'on')::boolean, false), 'potency', v_pmul, 'haste', v_cmul);
end $function$;
-- @grants public.effect_preview_card(text, integer, jsonb, jsonb)
grant execute on function public.effect_preview_card(text, integer, jsonb, jsonb) to postgres;
grant execute on function public.effect_preview_card(text, integer, jsonb, jsonb) to service_role;
