-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.effect_preview(text)
-- md5: 922d531f6fb1ff85da5599107d22f9b9   (md5(replace(pg_get_functiondef('public.effect_preview(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.effect_preview(p_player text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_object_agg(pc.card_id::text,
           effect_preview_card(c.rarity::text, coalesce(pc.ascension, 0), pc.stat_points, s.effect)), '{}'::jsonb)
  from player_cards pc join cards c on c.id = pc.card_id join subjects s on s.id = c.subject_id
  where pc.player_id = p_player and pc.quantity > 0 and s.effect->>'primitive' is not null;
$function$;
-- @grants public.effect_preview(text)
grant execute on function public.effect_preview(text) to postgres;
grant execute on function public.effect_preview(text) to service_role;
