-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.element_aliases()
-- md5: 4e5a811f8a784cf6aea70c7e9ff72152   (md5(replace(pg_get_functiondef('public.element_aliases()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.element_aliases()
 RETURNS TABLE(alias text, element text, ord integer)
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $function$
  select a.alias, a.element, a.ord from (values
    ('fire', 'fire', 1), ('flame', 'fire', 1), ('burning', 'fire', 1),
    ('water', 'water', 2), ('aqua', 'water', 2), ('ocean', 'water', 2),
    ('lightning', 'lightning', 3), ('electric', 'lightning', 3), ('thunder', 'lightning', 3),
    ('ice', 'ice', 4), ('frost', 'ice', 4), ('frozen', 'ice', 4),
    ('nature', 'nature', 5), ('grass', 'nature', 5), ('plant', 'nature', 5), ('wood', 'nature', 5),
    ('earth', 'earth', 6), ('rock', 'earth', 6), ('stone', 'earth', 6), ('ground', 'earth', 6),
    ('air', 'air', 7), ('wind', 'air', 7), ('flying', 'air', 7),
    ('shadow', 'shadow', 8), ('dark', 'shadow', 8), ('ghost', 'shadow', 8),
    ('light', 'light', 9), ('holy', 'light', 9), ('radiant', 'light', 9),
    ('arcane', 'arcane', 10), ('magic', 'arcane', 10), ('fairy', 'arcane', 10), ('mystic', 'arcane', 10),
    ('psychic', 'psychic', 11), ('psi', 'psychic', 11),
    ('toxic', 'toxic', 12), ('poison', 'toxic', 12), ('venom', 'toxic', 12),
    ('metal', 'metal', 13), ('robot', 'metal', 13), ('mechanical', 'metal', 13), ('tech', 'metal', 13), ('steel', 'metal', 13)
  ) a(alias, element, ord);
$function$;
-- @grants public.element_aliases()
grant execute on function public.element_aliases() to postgres;
grant execute on function public.element_aliases() to service_role;
