-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.element_of(text)
-- md5: 931bb00073db292f2aa3388511a075f9   (md5(replace(pg_get_functiondef('public.element_of(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.element_of(p_tag text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $function$
  select a.element from public.element_aliases() a where a.alias = lower(trim(regexp_replace(p_tag, '^trait:', '', 'i')));
$function$;
-- @grants public.element_of(text)
grant execute on function public.element_of(text) to postgres;
grant execute on function public.element_of(text) to service_role;
