-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.event_preview(events, timestamp with time zone)
-- md5: dedf175834b9321f16078d6f8d2af145   (md5(replace(pg_get_functiondef('public.event_preview(events, timestamp with time zone)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.event_preview(p_e events, p_now timestamp with time zone DEFAULT now())
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with r as (select x.* from event_recipients(p_e, p_now) x where x.packs > 0 or x.shards > 0 or x.card_id is not null),
  rp as (
    select r.*, exists (select 1 from gift_claims g where p_e.id is not null and g.event_id = p_e.id and g.player_id = r.member_id) as paid
      from r)
  select jsonb_build_object(
    'at', least(p_now, p_e.ends_at),
    'kind', p_e.kind,
    'audience', case when p_e.kind = 'launch_cards' then null else (select count(*) from event_audience(p_e.audience, least(p_now, p_e.ends_at))) end,
    'members', (select count(*) from rp),
    'packs', (select coalesce(sum(packs), 0) from rp),
    'shards', (select coalesce(sum(shards), 0) from rp),
    'cards', (select count(*) from rp where card_id is not null),
    'new_members', (select count(*) from rp where not paid),
    'new_packs', (select coalesce(sum(packs), 0) from rp where not paid),
    'new_shards', (select coalesce(sum(shards), 0) from rp where not paid),
    'new_cards', (select count(*) from rp where card_id is not null and not paid),
    'missing_cards', (select coalesce(jsonb_agg(distinct rp.card_id), '[]') from rp where rp.card_id is not null and not exists (select 1 from cards c where c.id = rp.card_id)),
    'by_rank', (select coalesce(jsonb_agg(jsonb_build_object('rank', b.rank, 'members', b.n, 'packs', b.packs, 'shards', b.shards, 'card_id', b.card_id) order by b.rank), '[]')
                  from (select rank, count(*) as n, sum(packs) as packs, sum(shards) as shards, min(card_id) as card_id from rp where rank is not null group by rank) b),
    'sample', (select coalesce(jsonb_agg(jsonb_build_object('member_id', s.member_id, 'username', s.username, 'rank', s.rank, 'score', s.score,
                  'packs', s.packs, 'shards', s.shards, 'card_id', s.card_id, 'paid', s.paid) order by s.rank nulls last, s.username, s.member_id), '[]')
                 from (select rp.*, p.username from rp join players p on p.id = rp.member_id order by rp.rank nulls last, p.username, rp.member_id limit 25) s));
$function$;
-- @grants public.event_preview(events, timestamp with time zone)
grant execute on function public.event_preview(events, timestamp with time zone) to postgres;
grant execute on function public.event_preview(events, timestamp with time zone) to service_role;
