-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.event_log_write()
-- md5: 6aeebb250bd7ffae8613c9519eb52f50   (md5(replace(pg_get_functiondef('public.event_log_write()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.event_log_write()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_old jsonb; v_new jsonb; v_action text;
  v_actor text := coalesce(nullif(current_setting('events.actor', true), ''), balance_who());
begin
  if tg_op = 'INSERT' then
    insert into event_log (event_id, actor, action, new)
      values (new.id, v_actor, coalesce(nullif(current_setting('events.action', true), ''), 'create'), to_jsonb(new) - 'updated_at');
    return null;
  end if;
  select jsonb_object_agg(o.key, o.value), jsonb_object_agg(o.key, n.value) into v_old, v_new
    from jsonb_each(to_jsonb(old)) o join jsonb_each(to_jsonb(new)) n on n.key = o.key
   where o.value is distinct from n.value and o.key <> 'updated_at';
  if v_new is null then return null; end if;
  v_action := case when old.status is distinct from new.status then
      case new.status when 'scheduled' then 'schedule' when 'draft' then 'unschedule' when 'live' then 'start' when 'ended' then 'end' else 'cancel' end
    else 'edit' end;
  insert into event_log (event_id, actor, action, old, new) values (new.id, v_actor, v_action, v_old, v_new);
  return null;
end $function$;
-- @grants public.event_log_write()
grant execute on function public.event_log_write() to postgres;
grant execute on function public.event_log_write() to service_role;
