-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.events_touch()
-- md5: 1dd6fe97631a5be12092fbff13131c4c   (md5(replace(pg_get_functiondef('public.events_touch()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.events_touch()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  new.updated_at := clock_timestamp();
  return new;
end $function$;
-- @grants public.events_touch()
grant execute on function public.events_touch() to postgres;
grant execute on function public.events_touch() to service_role;
