-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.event_step(bigint, timestamp with time zone)
-- md5: d7a32742b445e7d6d3657ff7ce4014e9   (md5(replace(pg_get_functiondef('public.event_step(bigint, timestamp with time zone)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.event_step(p_id bigint, p_now timestamp with time zone DEFAULT now())
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare e events; v_done jsonb := '[]'; v_late boolean;
begin
  select * into e from events where id = p_id for update;
  if not found then return jsonb_build_object('id', p_id, 'error', 'not_found'); end if;
  v_late := e.kind = 'drop' and coalesce((e.rules->>'late_joiners')::boolean, false);
  if e.status = 'scheduled' and e.starts_at <= p_now then
    update events set status = 'live' where id = p_id;
    e.status := 'live';
    v_done := v_done || jsonb_build_object('live', true);
    if e.kind = 'drop' then v_done := v_done || jsonb_build_object('start', event_pay(p_id, 'start', least(p_now, e.ends_at))); end if;
  end if;
  if e.status = 'live' then
    if e.ends_at <= p_now then
      if e.kind in ('trigger', 'rank') or v_late then v_done := v_done || jsonb_build_object('end', event_pay(p_id, 'end', e.ends_at)); end if;
      update events set status = 'ended', ended_at = p_now where id = p_id;
      v_done := v_done || jsonb_build_object('ended', true);
    elsif e.kind = 'trigger' or v_late then
      v_done := v_done || jsonb_build_object('tick', event_pay(p_id, 'tick', p_now));
    end if;
  end if;
  return jsonb_build_object('id', p_id, 'key', e.key, 'steps', v_done);
end $function$;
-- @grants public.event_step(bigint, timestamp with time zone)
grant execute on function public.event_step(bigint, timestamp with time zone) to postgres;
grant execute on function public.event_step(bigint, timestamp with time zone) to service_role;
