-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.event_row_errors(events)
-- md5: 4326b649836f257bab1f406af76d46e8   (md5(replace(pg_get_functiondef('public.event_row_errors(events)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.event_row_errors(p_e events)
 RETURNS text[]
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare e text[] := '{}'; v_cards bigint[];
begin
  if p_e.key is null or p_e.key !~ '^[a-z0-9][a-z0-9_]{2,47}$' then e := e || 'key: 3 to 48 characters a-z, 0-9 and _'::text;
  elsif exists (select 1 from events x where x.key = p_e.key and x.id is distinct from p_e.id) then e := e || 'key: another event has this key'::text; end if;
  if p_e.title is null or length(trim(p_e.title)) not between 1 and 80 then e := e || 'title: 1 to 80 characters'::text; end if;
  if length(coalesce(p_e.description, '')) > 1000 then e := e || 'description: at most 1000 characters'::text; end if;
  if p_e.starts_at is null or p_e.ends_at is null then e := e || 'the start and the end are required'::text;
  elsif p_e.ends_at <= p_e.starts_at then e := e || 'the end must be after the start'::text; end if;
  e := e || event_shape_errors(p_e.kind, p_e.audience, p_e.rewards, p_e.rules);
  if cardinality(e) = 0 and p_e.kind <> 'launch_cards' then
    v_cards := array(select (p_e.rewards->'per_member'->>'card_id')::bigint where p_e.rewards->'per_member'->>'card_id' is not null
                     union select (t->>'card_id')::bigint from jsonb_array_elements(coalesce(p_e.rewards->'ranks', '[]')) t where t->>'card_id' is not null);
    if exists (select 1 from unnest(v_cards) c where not exists (select 1 from cards x where x.id = c)) then e := e || 'rewards: a card id does not exist'::text; end if;
  end if;
  return e;
end $function$;
-- @grants public.event_row_errors(events)
grant execute on function public.event_row_errors(events) to postgres;
grant execute on function public.event_row_errors(events) to service_role;
