-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.event_tick(timestamp with time zone)
-- md5: 572f7e43fa579ec032693d7e7a0ead16   (md5(replace(pg_get_functiondef('public.event_tick(timestamp with time zone)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.event_tick(p_now timestamp with time zone DEFAULT now())
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_id bigint; v_out jsonb := '[]'; v_actor text := current_setting('events.actor', true);
begin
  if not pg_try_advisory_xact_lock(hashtext('public.event_tick')) then return jsonb_build_object('ok', false, 'error', 'busy'); end if;
  perform set_config('events.actor', 'event_tick', true);
  for v_id in select id from events where status in ('scheduled', 'live') and starts_at <= p_now order by starts_at, id loop
    v_out := v_out || event_step(v_id, p_now);
  end loop;
  perform set_config('events.actor', coalesce(v_actor, ''), true);
  return jsonb_build_object('ok', true, 'at', p_now, 'events', v_out);
end $function$;
-- @grants public.event_tick(timestamp with time zone)
grant execute on function public.event_tick(timestamp with time zone) to postgres;
grant execute on function public.event_tick(timestamp with time zone) to service_role;
