-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.event_reward_errors(jsonb, text, boolean)
-- md5: 4a59801aa975283f6255b0fe87bc42bd   (md5(replace(pg_get_functiondef('public.event_reward_errors(jsonb, text, boolean)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.event_reward_errors(p_item jsonb, p_where text, p_rank boolean)
 RETURNS text[]
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
declare e text[] := '{}'; k text; v jsonb;
begin
  if p_item is null or jsonb_typeof(p_item) <> 'object' then return array[p_where || ' must be an object']; end if;
  for k in select jsonb_object_keys(p_item) loop
    if not (k in ('packs', 'shards', 'card_id') or (p_rank and k in ('from', 'to'))) then e := e || format('%s: unknown key %s', p_where, k); end if;
  end loop;
  foreach k in array case when p_rank then array['packs', 'shards', 'from', 'to'] else array['packs', 'shards'] end loop
    v := p_item->k;
    if v is null then
      if k in ('from', 'to') then e := e || format('%s: %s is required', p_where, k); end if;
      continue;
    end if;
    if jsonb_typeof(v) <> 'number' or (v::text) !~ '^-?[0-9]{1,9}$' then e := e || format('%s: %s must be a whole number', p_where, k); continue; end if;
    if k = 'packs' and (v::text)::numeric not between 0 and 100 then e := e || format('%s: packs must be 0 to 100', p_where); end if;
    if k = 'shards' and (v::text)::numeric not between 0 and 100000 then e := e || format('%s: shards must be 0 to 100000', p_where); end if;
    if k in ('from', 'to') and (v::text)::numeric not between 1 and 1000 then e := e || format('%s: %s must be 1 to 1000', p_where, k); end if;
  end loop;
  v := p_item->'card_id';
  if v is not null and v <> 'null'::jsonb and (jsonb_typeof(v) <> 'number' or (v::text) !~ '^[1-9][0-9]{0,17}$') then
    e := e || format('%s: card_id must be a card id', p_where);
  end if;
  if cardinality(e) = 0 and coalesce((p_item->>'packs')::int, 0) = 0 and coalesce((p_item->>'shards')::int, 0) = 0
     and coalesce(p_item->'card_id', 'null'::jsonb) = 'null'::jsonb then
    e := e || format('%s: give packs, Shards or a card', p_where);
  end if;
  return e;
end $function$;
-- @grants public.event_reward_errors(jsonb, text, boolean)
grant execute on function public.event_reward_errors(jsonb, text, boolean) to postgres;
grant execute on function public.event_reward_errors(jsonb, text, boolean) to service_role;
