-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.expire_auctions()
-- md5: ffda6e215cd3872dc44744be4b22e068   (md5(replace(pg_get_functiondef('public.expire_auctions()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.expire_auctions()
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare a record; b record; n int := 0; cname text;
begin
  -- 1. An accepted bid not confirmed in 24 hours: declined for the bidder.
  for a in select id, seller_id, card_id, accepted_bid_id, ends_at from auctions
            where status = 'accepted' and accepted_at <= now() - interval '24 hours' for update skip locked loop
    select name into cname from cards where id = a.card_id;
    select * into b from auction_bids where id = a.accepted_bid_id;
    update auction_bids set status = 'declined', updated_at = now() where id = a.accepted_bid_id;
    if b.bidder_id is not null then
      perform notify_player(b.bidder_id, 'auction_ended', '🔨 You did not confirm the accepted bid for ' || coalesce(cname, 'a card') || ' within 24 hours. Your bid cards are free again.');
    end if;
    if a.ends_at > now() then
      update auctions set status = 'live', accepted_bid_id = null, accepted_at = null, notice_dirty = true where id = a.id;
      perform notify_player(a.seller_id, 'auction_declined', '🔨 The bidder did not confirm within 24 hours. Your auction for ' || coalesce(cname, 'your card') || ' is open again.');
    else
      for b in select distinct bidder_id from auction_bids where auction_id = a.id and status = 'open' loop
        perform notify_player(b.bidder_id, 'auction_ended', '🔨 The auction for ' || coalesce(cname, 'a card') || ' ended with no sale. Your bid cards are free again.');
      end loop;
      perform return_bids(a.id);
      update auctions set status = 'expired', accepted_bid_id = null, settled_at = now(), notice_dirty = true where id = a.id;
      perform notify_player(a.seller_id, 'auction_ended', '🔨 The bidder did not confirm within 24 hours. Your auction for ' || coalesce(cname, 'your card') || ' ended with no sale. The card is free again.');
    end if;
    n := n + 1;
  end loop;
  -- 2. A live auction whose time is up (hall_auction_notes.sql).
  for a in select id, seller_id, card_id from auctions where status = 'live' and ends_at <= now() for update skip locked loop
    select name into cname from cards where id = a.card_id;
    for b in select distinct bidder_id from auction_bids where auction_id = a.id and status in ('open', 'accepted') loop
      perform notify_player(b.bidder_id, 'auction_ended', '🔨 The auction for ' || coalesce(cname, 'a card') || ' ended with no sale. Your bid cards are free again.');
    end loop;
    perform return_bids(a.id);
    update auctions set status = 'expired', settled_at = now(), notice_dirty = true where id = a.id;
    perform notify_player(a.seller_id, 'auction_ended', '🔨 Your auction for ' || coalesce(cname, 'your card') || ' ended with no sale. The card is free again.');
    n := n + 1;
  end loop;
  return n;
end $function$;
-- @grants public.expire_auctions()
grant execute on function public.expire_auctions() to postgres;
grant execute on function public.expire_auctions() to service_role;
