-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.free_copies(text, bigint)
-- md5: 4c08244f31f87e337abd050ae768a09e   (md5(replace(pg_get_functiondef('public.free_copies(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.free_copies(p_player text, p_card bigint)
 RETURNS integer
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  select coalesce((select quantity from player_cards where player_id = p_player and card_id = p_card), 0)
       - (select count(*)::int from trade_offers
            where from_id = p_player and offer_card_id = p_card and status in ('pending', 'countered'))
       - (select count(*)::int from trade_offers
            where to_id = p_player and request_card_id = p_card and status = 'countered')
       - (select count(*)::int from auctions where seller_id = p_player and card_id = p_card and status in ('live', 'accepted'))
       - (select coalesce(sum((select count(*) from unnest(b.cards) x where x = p_card)), 0)::int
            from auction_bids b where b.bidder_id = p_player and b.status in ('open', 'accepted'));
$function$;
-- @grants public.free_copies(text, bigint)
grant execute on function public.free_copies(text, bigint) to postgres;
grant execute on function public.free_copies(text, bigint) to service_role;
