-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.gauntlet_week(date)
-- md5: 44b2f95c59d7546b97e1687b30a36175   (md5(replace(pg_get_functiondef('public.gauntlet_week(date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.gauntlet_week(p_day date)
 RETURNS date
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select p_day - extract(dow from p_day)::int;
$function$;
-- @grants public.gauntlet_week(date)
grant execute on function public.gauntlet_week(date) to postgres;
grant execute on function public.gauntlet_week(date) to service_role;
