-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.gauntlet_generate(date)
-- md5: 35d01054cd099c9b14a4692faebe34f6   (md5(replace(pg_get_functiondef('public.gauntlet_generate(date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.gauntlet_generate(p_week date)
 RETURNS gauntlet_weeks
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := dungeon_cfg(); gc jsonb := gauntlet_cfg(); k text := coalesce(cfg->>'salt', 'lion') || '|gauntlet|' || p_week::text;
  v_floors jsonb := '[]'; v_rooms jsonb; v_type text; f int; r int; v_name text; rk text; sq jsonb; w gauntlet_weeks;
  names text[] := array['The Proving Grounds','The Iron Trial','The Long Descent','The Lion''s Gauntlet','The Endless Stair','The Crucible'];
  wts jsonb := coalesce(gc->'room_weights', '{"fight":40,"horde":14,"elite":12,"miniboss":8,"rest":10,"choice":16}');
begin
  select * into w from gauntlet_weeks where week = p_week;
  if found then return w; end if;
  sq := gauntlet_squad(p_week);
  if sq is null then raise exception 'gauntlet_generate: no squad fits the budget'; end if;
  v_name := names[1 + floor(dungeon_rand(k || '|name') * array_length(names, 1))::int];
  for f in 1..coalesce((cfg->>'floors')::int, 30) loop
    v_rooms := '[]';
    for r in 1..5 loop
      rk := k || '|' || f || '|' || r;
      v_type := case when r = 5 then 'guardian' when r = 1 then 'fight' else dungeon_pick(wts, dungeon_rand(rk || '|t')) end;
      v_rooms := v_rooms || jsonb_build_object('type', v_type,
        'foes', case when v_type in ('fight', 'horde', 'elite', 'miniboss', 'guardian') then dungeon_room_foes(rk, f, r, v_type) else '[]'::jsonb end);
    end loop;
    v_floors := v_floors || jsonb_build_array(v_rooms);
  end loop;
  insert into gauntlet_weeks (week, name, squad, theme, floors)
  values (p_week, v_name, array(select (e #>> '{}')::bigint from jsonb_array_elements(sq->'squad') e), sq->>'theme', v_floors)
  on conflict (week) do nothing;
  select * into w from gauntlet_weeks where week = p_week;
  return w;
end $function$;
-- @grants public.gauntlet_generate(date)
grant execute on function public.gauntlet_generate(date) to postgres;
grant execute on function public.gauntlet_generate(date) to service_role;
