-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.gauntlet_pool()
-- md5: fc8c3be6cb0ec47e4278723a9bb75c92   (md5(replace(pg_get_functiondef('public.gauntlet_pool()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.gauntlet_pool()
 RETURNS TABLE(id bigint, ckey bigint, role text, cost integer, tags text[], aff text)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select c.id, hashtext(lower(regexp_replace(c.name, '^[^'']*''s[[:space:]]+', '')))::bigint,
         case when s.type in ('Character', 'Creature') then 'attacker' else 'support' end,
         coalesce((dungeon_cfg()->'cost'->>c.rarity::text)::int, 1), coalesce(s.tag_slugs, '{}'), s.ability->>'affinity'
  from cards c join subjects s on s.id = c.subject_id
  where c.source::text not in ('event', 'promo') and c.rarity::text not in ('event', 'promo')
    and (s.type in ('Character', 'Creature') or (s.type is not null and s.ability->>'kind' = 'support'));
$function$;
-- @grants public.gauntlet_pool()
grant execute on function public.gauntlet_pool() to postgres;
grant execute on function public.gauntlet_pool() to service_role;
