-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.gauntlet_squad(date)
-- md5: e04aaa20280c0951341b1be28fa19e3a   (md5(replace(pg_get_functiondef('public.gauntlet_squad(date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.gauntlet_squad(p_week date)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := gauntlet_cfg();
  k text := coalesce(dungeon_cfg()->>'salt', 'lion') || '|gauntlet|' || p_week::text;
  v_budget int := coalesce((cfg->>'budget')::int, (dungeon_cfg()->>'budget')::int, 12);
  th text; pass int; a_id bigint[]; a_key bigint[]; a_cost int[]; a_tags text[]; s_id bigint[]; s_key bigint[]; s_cost int[]; s_aff text[];
  i int; j int; l int; m int; n int; c int; sc int; best int := -1; pick bigint[]; v_tags text[];
begin
  for pass in 1..2 loop
    th := null;
    if pass = 1 then
      select t.aff into th from (select distinct p.aff from gauntlet_pool() p where p.role = 'support' and p.aff is not null) t
      where (select count(distinct a.ckey) from gauntlet_pool() a where a.role = 'attacker' and t.aff = any(a.tags)) >= 3
      order by dungeon_rand(k || '|theme|' || t.aff) limit 1;
      continue when th is null;
    end if;
    -- The candidates (seeded order): 14 attacker cards (with the theme), 8 support cards (the theme first).
    select array_agg(x.id order by x.o), array_agg(x.ckey order by x.o), array_agg(x.cost order by x.o), array_agg(x.tg order by x.o)
      into a_id, a_key, a_cost, a_tags from (
      select p.id, p.ckey, p.cost, array_to_string(p.tags, ',') tg, dungeon_rand(k || '|a|' || p.id) o
      from gauntlet_pool() p where p.role = 'attacker' and (th is null or th = any(p.tags))
      order by o limit 14) x;
    select array_agg(y.id order by y.o), array_agg(y.ckey order by y.o), array_agg(y.cost order by y.o), array_agg(y.aff order by y.o)
      into s_id, s_key, s_cost, s_aff from (
      select p.id, p.ckey, p.cost, p.aff, (case when th is not null and p.aff = th then 0 else 1 end) + dungeon_rand(k || '|s|' || p.id) o
      from gauntlet_pool() p where p.role = 'support'
      order by o limit case when th is null then 12 else 8 end) y;
    continue when coalesce(array_length(a_id, 1), 0) < 3 or coalesce(array_length(s_id, 1), 0) < 2;
    -- Every combination: within the budget, 5 different characters; the best score wins (the first in seeded order).
    for i in 1..array_length(a_id, 1) - 2 loop for j in i + 1..array_length(a_id, 1) - 1 loop for l in j + 1..array_length(a_id, 1) loop
      continue when a_key[i] = a_key[j] or a_key[i] = a_key[l] or a_key[j] = a_key[l];
      v_tags := string_to_array(a_tags[i] || ',' || a_tags[j] || ',' || a_tags[l], ',');
      for m in 1..array_length(s_id, 1) - 1 loop for n in m + 1..array_length(s_id, 1) loop
        continue when s_key[m] = s_key[n] or s_key[m] = any(array[a_key[i], a_key[j], a_key[l]]) or s_key[n] = any(array[a_key[i], a_key[j], a_key[l]]);
        c := a_cost[i] + a_cost[j] + a_cost[l] + s_cost[m] + s_cost[n];
        continue when c > v_budget;
        sc := 100 * (case when c = v_budget then 2 when c = v_budget - 1 then 1 else 0 end)
            + 20 * ((case when th is not null and s_aff[m] = th then 1 else 0 end) + (case when th is not null and s_aff[n] = th then 1 else 0 end))
            + 10 * ((case when s_aff[m] = any(v_tags) then 1 else 0 end) + (case when s_aff[n] = any(v_tags) then 1 else 0 end));
        if sc > best then best := sc; pick := array[a_id[i], a_id[j], a_id[l], s_id[m], s_id[n]]; end if;
      end loop; end loop;
    end loop; end loop; end loop;
    exit when pick is not null;
  end loop;
  if pick is null then return null; end if;
  return jsonb_build_object('squad', to_jsonb(pick), 'theme', th,
    'cost', (select sum(p.cost) from gauntlet_pool() p where p.id = any(pick)));
end $function$;
-- @grants public.gauntlet_squad(date)
grant execute on function public.gauntlet_squad(date) to postgres;
grant execute on function public.gauntlet_squad(date) to service_role;
