-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.gauntlet_board(date, integer)
-- md5: 74965f687e0dc9f93d27b903bebfa176   (md5(replace(pg_get_functiondef('public.gauntlet_board(date, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.gauntlet_board(p_week date DEFAULT NULL::date, p_limit integer DEFAULT 20)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select coalesce(jsonb_agg(row_to_json(x)::jsonb order by x.rank), '[]'::jsonb) from (
    select row_number() over (order by b.floor desc, b.room desc, b.turns, coalesce(b.ended_at, now())) rank,
           b.player_id, p.username, b.floor, b.room, b.turns, b.status, b.day, b.runs
    from (select distinct on (r.player_id) r.player_id, r.floor, r.room, r.turns, r.status, r.ended_at, r.day,
                 count(*) over (partition by r.player_id) runs
          from dungeon_runs r
          where r.mode = 'gauntlet' and r.day between coalesce(p_week, gauntlet_week(dungeon_day())) and coalesce(p_week, gauntlet_week(dungeon_day())) + 6
          order by r.player_id, r.floor desc, r.room desc, r.turns, coalesce(r.ended_at, now())) b
    join players p on p.id = b.player_id
    order by b.floor desc, b.room desc, b.turns, coalesce(b.ended_at, now()) limit p_limit) x;
$function$;
-- @grants public.gauntlet_board(date, integer)
grant execute on function public.gauntlet_board(date, integer) to postgres;
grant execute on function public.gauntlet_board(date, integer) to service_role;
