-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.gift_card(text, text, bigint)
-- md5: 7115dbfa61f8d04307aecff0b0ad1165   (md5(replace(pg_get_functiondef('public.gift_card(text, text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.gift_card(p_from text, p_to text, p_card_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare c record; v_gift bigint;
begin
  if p_from = p_to then return false; end if;
  perform 1 from players where id = p_to;
  if not found then return false; end if;
  select rarity::text as rarity, tradeable into c from cards where id = p_card_id;
  if not found or not c.tradeable or c.rarity = 'gold' then return false; end if;
  if free_copies(p_from, p_card_id) < 1 then return false; end if; -- reserved or not owned
  -- The card waits in the receiver's bell (gift_claims) until they redeem it, like a pack gift
  -- (Nathan, 2026-10-01: a gifted card plays the card animation on redeem). It leaves the sender now;
  -- the sender's row and the receiver's row (claim_gift) point at the same gift.
  insert into gift_claims (player_id, kind, title, amount, reason, from_id, card_id)
  values (p_to, 'card', coalesce((select name from cards where id = p_card_id), 'A card'), 1, 'member_gift', p_from, p_card_id)
  returning id into v_gift;
  if card_move(p_from, p_card_id, -1, 'gift_sent', 'gift', v_gift::text) is null then
    delete from gift_claims where id = v_gift;
    return false;
  end if;
  return true;
end; $function$;
-- @grants public.gift_card(text, text, bigint)
grant execute on function public.gift_card(text, text, bigint) to postgres;
grant execute on function public.gift_card(text, text, bigint) to service_role;
