-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.give_gift(text, text, text, integer, text, text)
-- md5: 49ea7c6c5c3fe8098064b6c148967d9f   (md5(replace(pg_get_functiondef('public.give_gift(text, text, text, integer, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.give_gift(p_player text, p_kind text, p_title text, p_amount integer, p_reason text, p_from text DEFAULT NULL::text)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare g bigint;
begin
  if p_amount is null or p_amount < 1 then return null; end if;
  insert into gift_claims (player_id, kind, title, amount, reason, from_id)
    values (p_player, p_kind, left(coalesce(nullif(trim(p_title), ''), 'A gift'), 80), p_amount, coalesce(p_reason, 'gift_received'), p_from)
    on conflict do nothing returning id into g;
  return g;
end $function$;
-- @grants public.give_gift(text, text, text, integer, text, text)
grant execute on function public.give_gift(text, text, text, integer, text, text) to postgres;
grant execute on function public.give_gift(text, text, text, integer, text, text) to service_role;
