-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.give_card_gift(text, bigint, text, text)
-- md5: 463b0640f85010d294db9bb8cfb85769   (md5(replace(pg_get_functiondef('public.give_card_gift(text, bigint, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.give_card_gift(p_player text, p_card bigint, p_title text, p_reason text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if p_card is null or not exists (select 1 from players where id = p_player) then return false; end if;
  if exists (select 1 from gift_claims where player_id = p_player and reason = p_reason) then return false; end if;
  insert into gift_claims (player_id, kind, title, amount, reason, card_id) values (p_player, 'card', p_title, 1, p_reason, p_card); -- amount 1: the table needs 1..999 (one card)
  return true;
end $function$;
-- @grants public.give_card_gift(text, bigint, text, text)
grant execute on function public.give_card_gift(text, bigint, text, text) to postgres;
grant execute on function public.give_card_gift(text, bigint, text, text) to service_role;
