-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.give_shards_gift_all(text, text, integer, text)
-- md5: d202b8c52658d33ee67537e243aec321   (md5(replace(pg_get_functiondef('public.give_shards_gift_all(text, text, integer, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.give_shards_gift_all(p_kind text, p_title text, p_shards integer, p_by text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare n int;
begin
  if p_kind not like 'once\_%' then raise exception 'a Shards gift for everyone needs a once_ kind'; end if;
  if p_shards is null or p_shards < 1 then return 0; end if;
  insert into gift_claims (player_id, kind, title, amount, shards, reason, from_id)
    select id, p_kind, left(coalesce(nullif(trim(p_title), ''), 'A gift'), 80), 0, p_shards, 'event', p_by from players
    on conflict do nothing;
  get diagnostics n = row_count;
  return n;
end $function$;
-- @grants public.give_shards_gift_all(text, text, integer, text)
grant execute on function public.give_shards_gift_all(text, text, integer, text) to postgres;
grant execute on function public.give_shards_gift_all(text, text, integer, text) to service_role;
