-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.give_gift_all(text, text, integer, text, text)
-- md5: 41441a9439d208adefc800e2086075dc   (md5(replace(pg_get_functiondef('public.give_gift_all(text, text, integer, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.give_gift_all(p_kind text, p_title text, p_amount integer, p_reason text, p_by text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare n int;
begin
  if p_amount is null or p_amount < 1 then return 0; end if;
  insert into gift_claims (player_id, kind, title, amount, reason, from_id)
    select id, p_kind, left(coalesce(nullif(trim(p_title), ''), 'A gift'), 80), p_amount, coalesce(p_reason, 'event'), p_by from players
    on conflict do nothing;
  get diagnostics n = row_count;
  return n;
end $function$;
-- @grants public.give_gift_all(text, text, integer, text, text)
grant execute on function public.give_gift_all(text, text, integer, text, text) to postgres;
grant execute on function public.give_gift_all(text, text, integer, text, text) to service_role;
