-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.grant_packs(text, integer, text, text, text, text)
-- md5: e416fd83997f7dc4c60519c0bf58b4de   (md5(replace(pg_get_functiondef('public.grant_packs(text, integer, text, text, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.grant_packs(p_player_id text, p_amount integer, p_reason text, p_by text DEFAULT NULL::text, p_ref_kind text DEFAULT NULL::text, p_ref_id text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare new_balance int;
begin
  update players set pack_balance = pack_balance + p_amount
    where id = p_player_id
    returning pack_balance into new_balance;
  if new_balance is null then
    return null;  -- unknown player
  end if;
  if p_amount <> 0 then
    -- No ref given but a member (p_by): the ref is that member (play_card_effect: the boon caster).
    insert into pack_ledger (player_id, amount, reason, granted_by, ref_kind, ref_id)
      values (p_player_id, p_amount, p_reason, p_by,
              coalesce(p_ref_kind, case when p_by is not null then 'player' end),
              case when p_ref_kind is null then p_by else p_ref_id end);
  end if;
  return new_balance;
end $function$;
-- @grants public.grant_packs(text, integer, text, text, text, text)
grant execute on function public.grant_packs(text, integer, text, text, text, text) to postgres;
grant execute on function public.grant_packs(text, integer, text, text, text, text) to service_role;
