-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.grant_shards(text, integer, text, text, text)
-- md5: 49f43af735f65133e905910f84e12f67   (md5(replace(pg_get_functiondef('public.grant_shards(text, integer, text, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.grant_shards(p_player text, p_amount integer, p_reason text, p_ref_kind text DEFAULT NULL::text, p_ref_id text DEFAULT NULL::text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_bal integer;
begin
  update players set shard_balance = shard_balance + p_amount where id = p_player returning shard_balance into v_bal;
  if v_bal is null then return null; end if;
  if p_amount <> 0 then
    insert into shard_ledger (player_id, amount, reason, ref_kind, ref_id) values (p_player, p_amount, p_reason, p_ref_kind, p_ref_id);
  end if;
  return v_bal;
end $function$;
-- @grants public.grant_shards(text, integer, text, text, text)
grant execute on function public.grant_shards(text, integer, text, text, text) to postgres;
grant execute on function public.grant_shards(text, integer, text, text, text) to service_role;
