-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.guild_joined(jsonb)
-- md5: a8312c2ce092a880b7f6bafff5ad5cb9   (md5(replace(pg_get_functiondef('public.guild_joined(jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.guild_joined(p_rows jsonb)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare n int;
begin
  if jsonb_typeof(p_rows) <> 'array' then return 0; end if;
  with r as (
    select distinct on (x->>'id') x->>'id' as id, (x->>'at')::timestamptz as at
      from jsonb_array_elements(p_rows) x
     where x->>'id' is not null and x->>'at' is not null
     order by x->>'id', (x->>'at')::timestamptz desc
  )
  update players p set guild_joined_at = r.at
    from r
   where p.id = r.id and (p.guild_joined_at is null or p.guild_joined_at < r.at);
  get diagnostics n = row_count;
  return n;
end $function$;
-- @grants public.guild_joined(jsonb)
grant execute on function public.guild_joined(jsonb) to postgres;
grant execute on function public.guild_joined(jsonb) to service_role;
