-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_round_cap()
-- md5: 2abf92c1a2ae9d1c0c226c26c1842d8e   (md5(replace(pg_get_functiondef('public.hunt_round_cap()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_round_cap()
 RETURNS integer
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select (balance_get('round_cap') #>> '{}')::int;
$function$;
-- @grants public.hunt_round_cap()
grant execute on function public.hunt_round_cap() to postgres;
grant execute on function public.hunt_round_cap() to service_role;
