-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_counter_pick(bigint, text, date, text, text)
-- md5: a85143f9363784915b92bb2cdc8fab0b   (md5(replace(pg_get_functiondef('public.hunt_counter_pick(bigint, text, date, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_counter_pick(p_hunt bigint, p_player text, p_day date, p_boss text, p_act text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_cfg jsonb; v_pool jsonb; v_marks jsonb; v_total numeric; v_r numeric; m jsonb; v_ctrs text; v_bal jsonb;
begin
  select value into v_cfg from settings where key = 'hunt_boss_moves';
  v_pool := v_cfg->p_boss->'moves';
  if v_pool is null or jsonb_typeof(v_pool) <> 'array' or jsonb_array_length(v_pool) = 0 then return null; end if;
  select coalesce(marks, '{}'::jsonb) into v_marks from hunt_combat_state where hunt_id = p_hunt and player_id = p_player and hit_date = p_day;
  if p_act = 'stunned' then
    if coalesce((v_marks->>'rubberband')::boolean, false) then
      update hunt_combat_state set marks = (marks - 'rubberband') || '{"double_next": true}'::jsonb, updated_at = now()
        where hunt_id = p_hunt and player_id = p_player and hit_date = p_day;
    end if;
    return null;
  end if;
  if p_act in ('charging', 'cataclysm') then return null; end if;
  if coalesce((v_marks->>'double_next')::boolean, false) then
    return jsonb_build_object('key', 'rubberband_hit', 'name', 'Rubberband');
  end if;
  -- A squad with none of the countered support meets the usual boss (Nathan, 2026-10-06: cut the support, not the squad).
  v_ctrs := v_cfg->p_boss->>'counters';
  if v_ctrs is not null and not exists (select 1 from hunt_card_hp h join cards c on c.id = h.card_id join subjects s on s.id = c.subject_id
      where h.hunt_id = p_hunt and h.player_id = p_player and h.hit_date = p_day and s.ability->>'kind' = 'support'
        and (v_ctrs = 'support' or s.ability->>'effect' = v_ctrs)) then return null; end if;
  -- The share of the normal turns (balance boss_counters): the boss's own share (boss_share), else share.
  -- The pool (the move keys) is content in settings.hunt_boss_moves; the weights are balance boss_counters.weights.
  v_bal := balance_get('boss_counters');
  if random() >= coalesce((v_bal->'boss_share'->>p_boss)::numeric, balance_num('boss_counters', 'share')) then return null; end if;
  select sum(balance_num('boss_counters', 'weights', e->>'key')) into v_total from jsonb_array_elements(v_pool) e;
  v_r := random() * v_total;
  for m in select e from jsonb_array_elements(v_pool) e loop
    v_r := v_r - balance_num('boss_counters', 'weights', m->>'key');
    if v_r <= 0 then return jsonb_build_object('key', m->>'key', 'name', m->>'name'); end if;
  end loop;
  return jsonb_build_object('key', v_pool->-1->>'key', 'name', v_pool->-1->>'name');
end $function$;
-- @grants public.hunt_counter_pick(bigint, text, date, text, text)
grant execute on function public.hunt_counter_pick(bigint, text, date, text, text) to postgres;
grant execute on function public.hunt_counter_pick(bigint, text, date, text, text) to service_role;
