-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_counter_tick(bigint, text, date, bigint, integer)
-- md5: d1e14eb7849d3857de4dc1de8994ff07   (md5(replace(pg_get_functiondef('public.hunt_counter_tick(bigint, text, date, bigint, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_counter_tick(p_hunt bigint, p_player text, p_day date, p_card bigint, p_round integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_marks jsonb; v_att int := 0; v_tg jsonb := '[]'; v_keep jsonb := '{}'; k text; v jsonb; v_hit jsonb;
begin
  select coalesce(marks, '{}'::jsonb) into v_marks from hunt_combat_state where hunt_id = p_hunt and player_id = p_player and hit_date = p_day;
  if not coalesce(v_marks ? 'dot', false) then return jsonb_build_object('attacker', 0, 'targets', '[]'::jsonb); end if;
  for k, v in select * from jsonb_each(v_marks->'dot') loop
    if (v->>'until')::int >= p_round then
      if k::bigint = p_card then v_att := v_att + (v->>'amt')::int;
      else v_hit := hunt_counter_hit(p_hunt, p_player, p_day, k::bigint, (v->>'amt')::int, false);
           if v_hit is not null then v_tg := v_tg || jsonb_build_array(v_hit); end if;
      end if;
      if (v->>'until')::int > p_round then v_keep := v_keep || jsonb_build_object(k, v); end if;
    end if;
  end loop;
  perform hunt_marks_patch(p_hunt, p_player, p_day, jsonb_build_object('dot', v_keep));
  return jsonb_build_object('attacker', v_att, 'targets', v_tg);
end $function$;
-- @grants public.hunt_counter_tick(bigint, text, date, bigint, integer)
grant execute on function public.hunt_counter_tick(bigint, text, date, bigint, integer) to postgres;
grant execute on function public.hunt_counter_tick(bigint, text, date, bigint, integer) to service_role;
