-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_counter_hit(bigint, text, date, bigint, integer, boolean)
-- md5: ce2d9f9b2973b4708a9f7fe83eee5b81   (md5(replace(pg_get_functiondef('public.hunt_counter_hit(bigint, text, date, bigint, integer, boolean)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_counter_hit(p_hunt bigint, p_player text, p_day date, p_cid bigint, p_dmg integer, p_pierce boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v jsonb; v_take int;
begin
  update hunt_card_hp h set
      hp_remaining = greatest(0, h.hp_remaining - case when p_pierce then p_dmg else greatest(0, p_dmg - coalesce(h.shield, 0)) end),
      shield = case when p_pierce then h.shield else greatest(0, coalesce(h.shield, 0) - p_dmg) end,
      downed = (h.hp_remaining - case when p_pierce then p_dmg else greatest(0, p_dmg - coalesce(h.shield, 0)) end) <= 0,
      updated_at = now()
    where h.hunt_id = p_hunt and h.player_id = p_player and h.hit_date = p_day and h.card_id = p_cid and not h.downed
    returning jsonb_build_object('card_id', h.card_id, 'dmg', p_dmg, 'hp', h.hp_remaining, 'max_hp', h.max_hp, 'downed', h.downed) into v;
  return v;
end $function$;
-- @grants public.hunt_counter_hit(bigint, text, date, bigint, integer, boolean)
grant execute on function public.hunt_counter_hit(bigint, text, date, bigint, integer, boolean) to postgres;
grant execute on function public.hunt_counter_hit(bigint, text, date, bigint, integer, boolean) to service_role;
