-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_counter_cd(bigint, text, date, text, integer, integer)
-- md5: 318ddf23746884fbde1e20926b5dcf59   (md5(replace(pg_get_functiondef('public.hunt_counter_cd(bigint, text, date, text, integer, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_counter_cd(p_hunt bigint, p_player text, p_day date, p_eff text, p_n integer, p_round integer)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare n int;
begin
  update hunt_card_hp h set cd_until_round = greatest(coalesce(h.cd_until_round, 0), p_round) + p_n, updated_at = now()
    from cards c join subjects s on s.id = c.subject_id
    where c.id = h.card_id and h.hunt_id = p_hunt and h.player_id = p_player and h.hit_date = p_day and not h.downed
      and s.ability->>'kind' = 'support' and (p_eff is null or s.ability->>'effect' = p_eff);
  get diagnostics n = row_count;
  return n;
end $function$;
-- @grants public.hunt_counter_cd(bigint, text, date, text, integer, integer)
grant execute on function public.hunt_counter_cd(bigint, text, date, text, integer, integer) to postgres;
grant execute on function public.hunt_counter_cd(bigint, text, date, text, integer, integer) to service_role;
