-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_squad_cards(bigint, text, date, bigint)
-- md5: a1d3cc6165db60a53094316e6ab94fe1   (md5(replace(pg_get_functiondef('public.hunt_squad_cards(bigint, text, date, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_squad_cards(p_hunt bigint, p_player text, p_day date, p_card bigint)
 RETURNS TABLE(card_id bigint, hp integer, max_hp integer, shield integer, buff numeric, kind text, eff text)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select h.card_id, h.hp_remaining, h.max_hp, coalesce(h.shield, 0), coalesce(h.dmg_buff, 1), s.ability->>'kind', s.ability->>'effect'
    from hunt_card_hp h join cards c on c.id = h.card_id join subjects s on s.id = c.subject_id
    where h.hunt_id = p_hunt and h.player_id = p_player and h.hit_date = p_day and h.card_id <> p_card and not h.downed;
$function$;
-- @grants public.hunt_squad_cards(bigint, text, date, bigint)
grant execute on function public.hunt_squad_cards(bigint, text, date, bigint) to postgres;
grant execute on function public.hunt_squad_cards(bigint, text, date, bigint) to service_role;
