-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_commit_card(bigint, text, bigint, date, integer)
-- md5: 165a2c131945eb341f8e4864413f6884   (md5(replace(pg_get_functiondef('public.hunt_commit_card(bigint, text, bigint, date, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_commit_card(p_hunt bigint, p_player text, p_card bigint, p_day date, p_maxhp integer)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_cap int;
begin
  if not hunt_squad_allows(p_hunt, p_player, p_day, p_card) then return false; end if; -- hunt_squads.sql
  if exists (select 1 from hunt_card_hp where hunt_id = p_hunt and player_id = p_player and card_id = p_card and hit_date = p_day) then
    return true;
  end if;
  v_cap := hunt_card_cap();
  if (select count(*) from hunt_card_hp where hunt_id = p_hunt and player_id = p_player and hit_date = p_day) >= v_cap then
    return false;
  end if;
  insert into hunt_card_hp (hunt_id, player_id, card_id, hit_date, hp_remaining, max_hp, downed)
    values (p_hunt, p_player, p_card, p_day, p_maxhp, p_maxhp, false)
    on conflict (hunt_id, player_id, card_id, hit_date) do nothing;
  return true;
end $function$;
-- @grants public.hunt_commit_card(bigint, text, bigint, date, integer)
grant execute on function public.hunt_commit_card(bigint, text, bigint, date, integer) to postgres;
grant execute on function public.hunt_commit_card(bigint, text, bigint, date, integer) to service_role;
