-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_squad_done(bigint, text, date, integer)
-- md5: cb77968a4d1aed36125eed7879400508   (md5(replace(pg_get_functiondef('public.hunt_squad_done(bigint, text, date, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_squad_done(p_hunt bigint, p_player text, p_day date, p_cap integer)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
 SET search_path TO 'public'
AS $function$
declare sq bigint[];
begin
  select card_ids into sq from hunt_squads where hunt_id = p_hunt and player_id = p_player and hit_date = p_day;
  if sq is not null then
    return not exists (
      select 1 from unnest(sq) x join cards c on c.id = x join subjects s on s.id = c.subject_id
       where s.type in ('Character', 'Creature')
         and not exists (select 1 from hunt_card_hp h where h.hunt_id = p_hunt and h.player_id = p_player
                           and h.hit_date = p_day and h.card_id = x and h.downed));
  end if;
  return (select count(*) from hunt_card_hp where hunt_id = p_hunt and player_id = p_player and hit_date = p_day) >= p_cap
     and not exists (select 1 from hunt_card_hp where hunt_id = p_hunt and player_id = p_player and hit_date = p_day and not downed);
end $function$;
-- @grants public.hunt_squad_done(bigint, text, date, integer)
grant execute on function public.hunt_squad_done(bigint, text, date, integer) to postgres;
grant execute on function public.hunt_squad_done(bigint, text, date, integer) to service_role;
