-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_damage_reconcile(bigint)
-- md5: 2dbe9bb6d4c5a61a70bf28ca02339ffd   (md5(replace(pg_get_functiondef('public.hunt_damage_reconcile(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_damage_reconcile(p_hunt bigint)
 RETURNS TABLE(player_id text, hits bigint, logged bigint, adjusted bigint, smite bigint, crasher bigint, unexplained bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with h as (
    select hh.player_id, sum(hh.damage)::bigint as d from hunt_hits hh where hh.hunt_id = p_hunt group by 1
  ), l as (
    select cl.player_id, sum(cl.damage)::bigint as d from hunt_combat_log cl where cl.hunt_id = p_hunt group by 1
  ), a as (
    select ha.player_id, sum(ha.damage)::bigint as d from hunt_adjustments ha where ha.hunt_id = p_hunt group by 1
  ), x as (
    select ca.player_id,
           sum((ca.result->>'value')::bigint) filter (where ca.effect = 'smite')::bigint as smite,
           sum((ca.result->>'value')::bigint) filter (where ca.effect = 'raid_crasher')::bigint as crasher
      from combat_actions ca
     where ca.mode = 'hunt' and ca.ref_id = p_hunt and ca.effect in ('smite', 'raid_crasher')
       and not coalesce((ca.result->>'mirrored')::boolean, false)
     group by 1
  ), players_in as (
    select h.player_id from h union select l.player_id from l union select a.player_id from a union select x.player_id from x
  )
  select pi.player_id, coalesce(h.d, 0), coalesce(l.d, 0), coalesce(a.d, 0), coalesce(x.smite, 0), coalesce(x.crasher, 0),
         (coalesce(h.d, 0) - coalesce(l.d, 0) - coalesce(a.d, 0) - coalesce(x.smite, 0) - coalesce(x.crasher, 0))::bigint
    from players_in pi
    left join h on h.player_id = pi.player_id left join l on l.player_id = pi.player_id
    left join a on a.player_id = pi.player_id left join x on x.player_id = pi.player_id
   order by 1
$function$;
-- @grants public.hunt_damage_reconcile(bigint)
grant execute on function public.hunt_damage_reconcile(bigint) to postgres;
grant execute on function public.hunt_damage_reconcile(bigint) to service_role;
