-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_leaderboard(bigint, integer)
-- md5: c88f3e039d10f7dc2eb42da321e36ec8   (md5(replace(pg_get_functiondef('public.hunt_leaderboard(bigint, integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_leaderboard(p_hunt bigint, p_limit integer DEFAULT 20)
 RETURNS TABLE(player_id text, username text, damage bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select h.player_id, p.username, sum(h.damage)::bigint
  from hunt_hits h join players p on p.id = h.player_id
  where h.hunt_id = p_hunt
  group by h.player_id, p.username
  order by 3 desc
  limit greatest(1, least(100, coalesce(p_limit, 20)));
$function$;
-- @grants public.hunt_leaderboard(bigint, integer)
grant execute on function public.hunt_leaderboard(bigint, integer) to postgres;
grant execute on function public.hunt_leaderboard(bigint, integer) to service_role;
