-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.hunt_combat_stats(bigint)
-- md5: 37caa0f6219c482b719f4a69c2d96ced   (md5(replace(pg_get_functiondef('public.hunt_combat_stats(bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.hunt_combat_stats(p_hunt bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with l as (select * from hunt_combat_log where p_hunt is null or hunt_id = p_hunt)
  select jsonb_build_object(
    'attacks',      count(*),
    'miss_pct',     round(100.0 * count(*) filter (where outcome = 'miss')    / greatest(count(*), 1), 1),
    'crit_pct',     round(100.0 * count(*) filter (where crit)                / greatest(count(*), 1), 1),
    'block_pct',    round(100.0 * count(*) filter (where block)               / greatest(count(*), 1), 1),
    'weak_pct',     round(100.0 * count(*) filter (where bonus)               / greatest(count(*), 1), 1),
    'counter_pct',  round(100.0 * count(*) filter (where countered)           / greatest(count(*), 1), 1),
    'downs',        count(*) filter (where card_downed),
    'avg_damage',   round(coalesce(avg(damage), 0)::numeric, 1),
    'total_damage', coalesce(sum(damage), 0)
  ) from l;
$function$;
-- @grants public.hunt_combat_stats(bigint)
grant execute on function public.hunt_combat_stats(bigint) to postgres;
grant execute on function public.hunt_combat_stats(bigint) to service_role;
