-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.launch_player_gift(text)
-- md5: d8530e349fd439f5367768b2a88db4f5   (md5(replace(pg_get_functiondef('public.launch_player_gift(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.launch_player_gift(p_player text)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := (select value from settings where key = 'launch_event_cards');
begin
  if cfg->>'player_card' is null or now() >= (cfg->>'player_until')::timestamptz then return false; end if;
  return give_card_gift(p_player, (cfg->>'player_card')::bigint, 'Launch Day Player', 'event:launch_player');
end $function$;
-- @grants public.launch_player_gift(text)
grant execute on function public.launch_player_gift(text) to postgres;
grant execute on function public.launch_player_gift(text) to service_role;
