-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.launch_raider_gift()
-- md5: 29bb8b3672f64105ea8506b1c084fd44   (md5(replace(pg_get_functiondef('public.launch_raider_gift()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.launch_raider_gift()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := (select value from settings where key = 'launch_event_cards');
begin
  if cfg->>'raider_card' is not null and new.hunt_id in (
       select id from hunts where id >= (cfg->>'raider_hunts_from')::bigint order by id limit (cfg->>'raider_hunt_count')::int) then
    perform give_card_gift(new.player_id, (cfg->>'raider_card')::bigint, 'Launch Day Raider', 'event:launch_raider');
  end if;
  return new;
end $function$;
-- @grants public.launch_raider_gift()
grant execute on function public.launch_raider_gift() to postgres;
grant execute on function public.launch_raider_gift() to service_role;
