-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.ledger_reason_guard()
-- md5: 6fe009cba98bb9d335d133687b2280ee   (md5(replace(pg_get_functiondef('public.ledger_reason_guard()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.ledger_reason_guard()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_status text;
begin
  if new.reason is null then return new; end if;
  select status into v_status from ledger_reasons where ledger = tg_argv[0] and reason = new.reason;
  if v_status is null or v_status = 'retired' then
    raise exception '%: the % reason "%" is %', tg_table_name, tg_argv[0], new.reason,
      case when v_status is null then 'not in ledger_reasons' else 'retired (old rows only)' end
      using errcode = 'check_violation', constraint = tg_argv[1], table = tg_table_name,
            hint = 'Add the reason to public.ledger_reasons (with a note) before code writes it.';
  end if;
  return new;
end $function$;
-- @grants public.ledger_reason_guard()
grant execute on function public.ledger_reason_guard() to postgres;
grant execute on function public.ledger_reason_guard() to service_role;
