-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.list_for_trade(text, bigint)
-- md5: e8333916a741db120c5622443d6bb33e   (md5(replace(pg_get_functiondef('public.list_for_trade(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.list_for_trade(p_player text, p_card bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare c record; lid bigint;
begin
  select rarity::text as rarity, tradeable into c from cards where id = p_card;
  if not found or not c.tradeable then return jsonb_build_object('ok', false, 'error', 'not_tradeable'); end if;
  if free_copies(p_player, p_card) < 1 then return jsonb_build_object('ok', false, 'error', 'no_copy'); end if;
  if (select count(*) from trade_listings where player_id = p_player and status = 'open') >= 5 then
    return jsonb_build_object('ok', false, 'error', 'too_many');
  end if;
  insert into trade_listings (player_id, card_id) values (p_player, p_card)
    on conflict (player_id, card_id) where status = 'open' do nothing returning id into lid;
  if lid is null then return jsonb_build_object('ok', false, 'error', 'already_listed'); end if;
  return jsonb_build_object('ok', true, 'id', lid);
end $function$;
-- @grants public.list_for_trade(text, bigint)
grant execute on function public.list_for_trade(text, bigint) to postgres;
grant execute on function public.list_for_trade(text, bigint) to service_role;
