-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.notify_player(text, text, text)
-- md5: 4999cf71d322d9fd2ed323c187558717   (md5(replace(pg_get_functiondef('public.notify_player(text, text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.notify_player(p_player text, p_kind text, p_message text)
 RETURNS void
 LANGUAGE sql
 SET search_path TO 'public'
AS $function$
  insert into notifications (player_id, kind, message) values (p_player, p_kind, p_message);
$function$;
-- @grants public.notify_player(text, text, text)
grant execute on function public.notify_player(text, text, text) to postgres;
grant execute on function public.notify_player(text, text, text) to service_role;
