-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.nudge_hunt()
-- md5: a6e6a457ce0f190c50568165818ac806   (md5(replace(pg_get_functiondef('public.nudge_hunt()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.nudge_hunt()
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_id bigint; v_name text; v_close timestamptz; v_hp bigint; v_max bigint;
begin
  select id, name, closes_at, hp_remaining, hp_max into v_id, v_name, v_close, v_hp, v_max
    from hunts where status = 'active' order by id desc limit 1;
  if v_id is null then return jsonb_build_object('ok', true, 'note', 'no_active'); end if;
  insert into hunt_events (hunt_id, kind, payload)
    values (v_id, 'nudge', jsonb_build_object('name', v_name, 'closes_at', v_close,
      'hp_remaining', v_hp, 'hp_max', v_max));
  return jsonb_build_object('ok', true, 'nudged', v_id);
end $function$;
-- @grants public.nudge_hunt()
grant execute on function public.nudge_hunt() to postgres;
grant execute on function public.nudge_hunt() to service_role;
