-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.offer_on_listing(text, bigint, bigint)
-- md5: 557b0bcd21525cf449244091e6c0e3b4   (md5(replace(pg_get_functiondef('public.offer_on_listing(text, bigint, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.offer_on_listing(p_from text, p_listing bigint, p_offer bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare l trade_listings; oid bigint;
begin
  select * into l from trade_listings where id = p_listing and status = 'open';
  if not found then return jsonb_build_object('ok', false, 'error', 'listing_closed'); end if;
  if l.player_id = p_from then return jsonb_build_object('ok', false, 'error', 'own_listing'); end if;
  if free_copies(l.player_id, l.card_id) < 1 then return jsonb_build_object('ok', false, 'error', 'listing_gone'); end if;
  if exists (select 1 from trade_offers where from_id = p_from and listing_id = p_listing and status = 'pending') then
    return jsonb_build_object('ok', false, 'error', 'already_offered');
  end if;
  oid := create_trade(p_from, l.player_id, p_offer, l.card_id);
  if oid is null then return jsonb_build_object('ok', false, 'error', 'cannot_trade'); end if;
  update trade_offers set listing_id = p_listing where id = oid;
  return jsonb_build_object('ok', true, 'id', oid, 'to', l.player_id);
end $function$;
-- @grants public.offer_on_listing(text, bigint, bigint)
grant execute on function public.offer_on_listing(text, bigint, bigint) to postgres;
grant execute on function public.offer_on_listing(text, bigint, bigint) to service_role;
