-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.open_packs(text, bigint[], integer)
-- md5: 78cb45be91d898fa0b3dcbde7c8dcd10   (md5(replace(pg_get_functiondef('public.open_packs(text, bigint[], integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.open_packs(p_player_id text, p_cards bigint[], p_size integer)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_want int; v_have int; v_n int; v_open text := gen_random_uuid()::text; -- one id for the packs of this open
begin
  v_want := coalesce(array_length(p_cards, 1), 0) / greatest(1, p_size);
  if v_want < 1 or v_want > 10 then return 0; end if;
  -- The row lock makes concurrent opens of one player wait, so the balance never goes below 0.
  select pack_balance into v_have from players where id = p_player_id for update;
  v_n := least(coalesce(v_have, 0), v_want);
  if v_n <= 0 then return 0; end if;
  update players set pack_balance = pack_balance - v_n where id = p_player_id;
  insert into pack_ledger (player_id, amount, reason, ref_kind, ref_id)
    select p_player_id, -1, 'opened', 'open', v_open from generate_series(1, v_n);
  perform add_cards_to_player(p_player_id, p_cards[1 : v_n * p_size]);
  return v_n;
end $function$;
-- @grants public.open_packs(text, bigint[], integer)
grant execute on function public.open_packs(text, bigint[], integer) to postgres;
grant execute on function public.open_packs(text, bigint[], integer) to service_role;
