-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.open_packs(text, bigint[], integer)
-- md5: 78cb45be91d898fa0b3dcbde7c8dcd10   (md5(replace(pg_get_functiondef('public.open_packs(text, bigint[], integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.open_packs(p_player_id text, p_cards bigint[], p_size integer)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_want int; v_have int; v_n int; v_open text := gen_random_uuid()::text; -- one id for the packs of this open
begin
  v_want := coalesce(array_length(p_cards, 1), 0) / greatest(1, p_size);
  if v_want < 1 or v_want > 10 then return 0; end if;
  -- The row lock makes concurrent opens of one player wait, so the balance never goes below 0.
  select pack_balance into v_have from players where id = p_player_id for update;
  v_n := least(coalesce(v_have, 0), v_want);
  if v_n <= 0 then return 0; end if;
  update players set pack_balance = pack_balance - v_n where id = p_player_id;
  insert into pack_ledger (player_id, amount, reason, ref_kind, ref_id)
    select p_player_id, -1, 'opened', 'open', v_open from generate_series(1, v_n);
  perform add_cards_to_player(p_player_id, p_cards[1 : v_n * p_size]);
  return v_n;
end $function$;
-- @grants public.open_packs(text, bigint[], integer)
grant execute on function public.open_packs(text, bigint[], integer) to postgres;
grant execute on function public.open_packs(text, bigint[], integer) to service_role;

-- @function public.open_packs(text, bigint[], integer, text)
-- md5: 27536bef052197d6d509fa7ba49f4ee5   (md5(replace(pg_get_functiondef('public.open_packs(text, bigint[], integer, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.open_packs(p_player_id text, p_cards bigint[], p_size integer, p_set text)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_want int; v_have int; v_n int; v_open text := gen_random_uuid()::text; -- one id for the packs of this open
begin
  if not exists (select 1 from card_sets where id = p_set and pullable) then
    raise exception 'set_not_pullable: %', coalesce(p_set, 'null') using errcode = 'P0001';
  end if;
  if exists (select 1 from unnest(p_cards) x(id) where not exists (select 1 from draw_pool d where d.id = x.id and d.set_id = p_set)) then
    raise exception 'open_packs: a card is not in the draw pool of set %', p_set using errcode = 'P0001';
  end if;
  v_want := coalesce(array_length(p_cards, 1), 0) / greatest(1, p_size);
  if v_want < 1 or v_want > 10 then return 0; end if;
  -- The row lock makes concurrent opens of one player wait, so the balance never goes below 0.
  select pack_balance into v_have from players where id = p_player_id for update;
  v_n := least(coalesce(v_have, 0), v_want);
  if v_n <= 0 then return 0; end if;
  update players set pack_balance = pack_balance - v_n, last_open_set = p_set where id = p_player_id; -- D-85
  insert into pack_ledger (player_id, amount, reason, ref_kind, ref_id, set_id)
    select p_player_id, -1, 'opened', 'open', v_open, p_set from generate_series(1, v_n);
  perform add_cards_to_player(p_player_id, p_cards[1 : v_n * p_size]);
  return v_n;
end $function$;
-- @grants public.open_packs(text, bigint[], integer, text)
grant execute on function public.open_packs(text, bigint[], integer, text) to postgres;
grant execute on function public.open_packs(text, bigint[], integer, text) to service_role;
