-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.pack_ledger_reconcile()
-- md5: 913fc22a3e4924ceb71bccb097a19a61   (md5(replace(pg_get_functiondef('public.pack_ledger_reconcile()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.pack_ledger_reconcile()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with s as (
    select p.id, p.pack_balance, coalesce(sum(l.amount), 0)::bigint as ledger
      from players p left join pack_ledger l on l.player_id = p.id
     group by p.id, p.pack_balance
  ), x as (
    select (select count(*) from s) as players,
           (select count(*) from s where s.ledger <> s.pack_balance) as mismatched,
           (select coalesce(jsonb_agg(jsonb_build_object('player_id', s.id, 'balance', s.pack_balance, 'ledger', s.ledger)), '[]'::jsonb)
              from s where s.ledger <> s.pack_balance) as mismatched_rows,
           (select count(*) from pack_ledger) as rows,
           (select count(*) from pack_ledger where ref_kind is null or ref_id is null) as rows_without_ref,
           coalesce((select convalidated from pg_constraint where conname = 'pack_ledger_reason_check' and conrelid = 'public.pack_ledger'::regclass), false) as reason_check,
           coalesce((select convalidated from pg_constraint where conname = 'players_pack_balance_nonneg' and conrelid = 'public.players'::regclass), false) as balance_check
  )
  select jsonb_build_object('ok', x.mismatched = 0 and x.rows_without_ref = 0 and x.reason_check and x.balance_check,
    'players', x.players, 'mismatched', x.mismatched, 'rows', x.rows, 'rows_without_ref', x.rows_without_ref,
    'reason_check', x.reason_check, 'balance_check', x.balance_check, 'mismatched_rows', x.mismatched_rows)
    from x;
$function$;
-- @grants public.pack_ledger_reconcile()
grant execute on function public.pack_ledger_reconcile() to postgres;
grant execute on function public.pack_ledger_reconcile() to service_role;
