-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.playing_today(text)
-- md5: 6311e6e45a217ddd74ccb8ca638013b9   (md5(replace(pg_get_functiondef('public.playing_today(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.playing_today(p_player text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with d as (select (now() at time zone 'America/Denver')::date as day,
                    ((now() at time zone 'America/Denver')::date)::timestamp at time zone 'America/Denver' as t0)
  select jsonb_build_object(
    'name', (select username from players where id = p_player),
    'avatar', (select avatar from players where id = p_player),
    'playing_pref', coalesce((select notify_prefs->>'playing' from players where id = p_player), 'true'),
    'packs', (select count(*) from pack_ledger, d where player_id = p_player and reason = 'opened' and created_at >= d.t0),
    'damage', (select coalesce(sum(damage), 0) from hunt_hits, d where player_id = p_player and hit_date = d.day),
    'best', (select jsonb_build_object('id', c.id, 'name', c.name, 'rarity', c.rarity, 'image_url', c.image_url)
               from player_cards pc join cards c on c.id = pc.card_id, d
              where pc.player_id = p_player and pc.first_obtained_at >= d.t0
              order by public.rarity_rank(c.rarity::text) desc, pc.first_obtained_at desc
              limit 1));
$function$;
-- @grants public.playing_today(text)
grant execute on function public.playing_today(text) to postgres;
grant execute on function public.playing_today(text) to service_role;
