-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.profile_log_write()
-- md5: a3c1f7790f3285f1f29dec5592664d9c   (md5(replace(pg_get_functiondef('public.profile_log_write()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.profile_log_write()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_by text := balance_who();
begin
  insert into profile_log (player_id, field, old_value, new_value, changed_by)
  select new.id, f.field, f.o, f.n, v_by
    from (values
      (1, 'username', to_jsonb(old.username), to_jsonb(new.username)),
      (2, 'avatar', to_jsonb(old.avatar), to_jsonb(new.avatar)),
      (3, 'title', to_jsonb(old.title), to_jsonb(new.title)),
      (4, 'frame', to_jsonb(old.frame), to_jsonb(new.frame)),
      (5, 'spotlight', to_jsonb(old.spotlight), to_jsonb(new.spotlight))) f(ord, field, o, n)
   where f.o is distinct from f.n order by f.ord;
  -- The two jsonb columns: one row per top-level key that changed (notify_prefs.all, tutorial.done, ...).
  -- A value that is not an object is logged as the whole column.
  if old.notify_prefs is distinct from new.notify_prefs then
    if jsonb_typeof(old.notify_prefs) = 'object' and jsonb_typeof(new.notify_prefs) = 'object' then
      insert into profile_log (player_id, field, old_value, new_value, changed_by)
      select new.id, 'notify_prefs.' || k2, old.notify_prefs -> k2, new.notify_prefs -> k2, v_by
        from (select jsonb_object_keys(old.notify_prefs) union select jsonb_object_keys(new.notify_prefs)) x(k2)
       where (old.notify_prefs -> k2) is distinct from (new.notify_prefs -> k2) order by k2;
    else
      insert into profile_log (player_id, field, old_value, new_value, changed_by) values (new.id, 'notify_prefs', old.notify_prefs, new.notify_prefs, v_by);
    end if;
  end if;
  if old.tutorial is distinct from new.tutorial then
    if jsonb_typeof(old.tutorial) = 'object' and jsonb_typeof(new.tutorial) = 'object' then
      insert into profile_log (player_id, field, old_value, new_value, changed_by)
      select new.id, 'tutorial.' || k2, old.tutorial -> k2, new.tutorial -> k2, v_by
        from (select jsonb_object_keys(old.tutorial) union select jsonb_object_keys(new.tutorial)) x(k2)
       where (old.tutorial -> k2) is distinct from (new.tutorial -> k2) order by k2;
    else
      insert into profile_log (player_id, field, old_value, new_value, changed_by) values (new.id, 'tutorial', old.tutorial, new.tutorial, v_by);
    end if;
  end if;
  return new;
end $function$;
-- @grants public.profile_log_write()
grant execute on function public.profile_log_write() to postgres;
grant execute on function public.profile_log_write() to service_role;
