-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.prune_old_rows()
-- md5: 2f6d787ba994e391b6151a066d581bd0   (md5(replace(pg_get_functiondef('public.prune_old_rows()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.prune_old_rows()
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare n_notes int; n_events int; n_fx int; n_cron int;
begin
  delete from public.notifications
   where (read and created_at < now() - interval '30 days')
      or (not read and created_at < now() - interval '90 days');
  get diagnostics n_notes = row_count;

  delete from public.hunt_events
   where posted_at is not null and posted_at < now() - interval '30 days';
  get diagnostics n_events = row_count;

  delete from public.discord_effects
   where status in ('done', 'reverted', 'skipped', 'failed')
     and updated_at < now() - interval '30 days' and created_at < now() - interval '30 days';
  get diagnostics n_fx = row_count;

  delete from cron.job_run_details
   where status <> 'running' and coalesce(end_time, start_time) < now() - interval '14 days';
  get diagnostics n_cron = row_count;

  return jsonb_build_object('notifications', n_notes, 'hunt_events', n_events,
    'discord_effects', n_fx, 'cron_job_run_details', n_cron);
end $function$;
-- @grants public.prune_old_rows()
grant execute on function public.prune_old_rows() to postgres;
grant execute on function public.prune_old_rows() to service_role;
