-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.pullable_sets(text)
-- md5: d1d818b4d246e4490c7c2c0bd6f14d58   (md5(replace(pg_get_functiondef('public.pullable_sets(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.pullable_sets(p_player text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with s as (select * from card_sets where pullable),
  newest as (select id from s order by released_at desc nulls last, sort desc, id desc limit 1),
  n as (select set_id, count(*) as cards from draw_pool group by set_id),
  o as (select d.set_id, count(*) as owned from player_cards pc join draw_pool d on d.id = pc.card_id
         where pc.player_id = p_player and pc.quantity > 0 group by d.set_id)
  select jsonb_build_object(
    'sets', coalesce((select jsonb_agg(jsonb_build_object(
        'id', s.id, 'name', s.name, 'code', s.code, 'season', s.season, 'released_at', s.released_at,
        'is_new', s.id = (select id from newest) and (select count(*) from s) > 1,
        'cards', coalesce(n.cards, 0), 'owned', coalesce(o.owned, 0),
        'cover_card_id', s.cover_card_id, 'cover_image_url', c.image_url,
        'pack_color', s.pack_color, 'pack_art_url', s.pack_art_url)
      order by s.sort, s.id)
      from s left join n on n.set_id = s.id left join o on o.set_id = s.id left join cards c on c.id = s.cover_card_id), '[]'::jsonb),
    'last_set', coalesce((select p.last_open_set from players p join s on s.id = p.last_open_set where p.id = p_player),
                         (select id from newest)));
$function$;
-- @grants public.pullable_sets(text)
grant execute on function public.pullable_sets(text) to postgres;
grant execute on function public.pullable_sets(text) to service_role;
