-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.record_activity(text, date)
-- md5: 60d0bf11f67ffe64327a03b53da5679c   (md5(replace(pg_get_functiondef('public.record_activity(text, date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.record_activity(p_player_id text, p_date date)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare new_count int;
begin
  insert into daily_activity (player_id, activity_date, message_count)
  values (p_player_id, p_date, 1)
  on conflict (player_id, activity_date)
  do update set message_count = daily_activity.message_count + 1
  returning message_count into new_count;
  return new_count;
end; $function$;
-- @grants public.record_activity(text, date)
grant execute on function public.record_activity(text, date) to postgres;
grant execute on function public.record_activity(text, date) to service_role;
