-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.refund_card_play(bigint, text)
-- md5: eaf8ee2b278b70f793568e5f5d5fc124   (md5(replace(pg_get_functiondef('public.refund_card_play(bigint, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.refund_card_play(p_play bigint, p_reason text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_player text; v_subject bigint;
begin
  update card_plays set outcome = 'refunded', refund_reason = left(coalesce(p_reason, 'refused'), 60)
   where id = p_play and outcome <> 'refunded'
  returning player_id, subject_id into v_player, v_subject;
  if not found then return jsonb_build_object('ok', false, 'error', 'no_play'); end if;
  delete from card_effect_cooldowns where player_id = v_player and subject_id = v_subject;
  return jsonb_build_object('ok', true, 'player', v_player, 'subject', v_subject);
end $function$;
-- @grants public.refund_card_play(bigint, text)
grant execute on function public.refund_card_play(bigint, text) to postgres;
grant execute on function public.refund_card_play(bigint, text) to service_role;
