-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.remove_card_from_player(text, bigint)
-- md5: 21d5736103da9e8c5f082ef0e5662867   (md5(replace(pg_get_functiondef('public.remove_card_from_player(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.remove_card_from_player(p_player_id text, p_card_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  -- No path calls it since card_ledger.sql (each calls card_move with its ref). Kept for old callers: an admin move.
  return card_move(p_player_id, p_card_id, -1, 'admin', 'tx', txid_current()::text) is not null;
end; $function$;
-- @grants public.remove_card_from_player(text, bigint)
grant execute on function public.remove_card_from_player(text, bigint) to postgres;
grant execute on function public.remove_card_from_player(text, bigint) to service_role;
