-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.roster_snapshot()
-- md5: 9ebbc5b0d0dae19321f488750dd06d0c   (md5(replace(pg_get_functiondef('public.roster_snapshot()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.roster_snapshot()
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare v_pow bigint; v_dep bigint; v_cards int; v_owners int; v_players int; v_id bigint; v_hp jsonb;
begin
  select coalesce(sum(card_power(c.rarity::text, pc.ascension, s.cp_mod)), 0)::bigint, count(*)::int, count(distinct pc.player_id)::int
    into v_pow, v_cards, v_owners
    from player_cards pc join cards c on c.id = pc.card_id join subjects s on s.id = c.subject_id
    where pc.quantity >= 1;
  v_dep := deployable_power();
  select count(*)::int into v_players from players;
  v_hp := roster_boss_hp(v_dep);   -- the estimate of balance boss_hp_estimate (not the real boss HP), the same as roster_stats
  insert into roster_power_history (players, owned_cards, total_power, deployable_power, boss_hp_normal, boss_hp_heroic, boss_hp_mythic)
    values (v_players, v_cards, v_pow, v_dep,
      (v_hp->>'Normal')::bigint, (v_hp->>'Heroic')::bigint, (v_hp->>'Mythic')::bigint)
    returning id into v_id;
  return v_id;
end $function$;
-- @grants public.roster_snapshot()
grant execute on function public.roster_snapshot() to postgres;
grant execute on function public.roster_snapshot() to service_role;
