-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.roster_stats()
-- md5: 79b65ad0a29dcd326061c1b2ef623633   (md5(replace(pg_get_functiondef('public.roster_stats()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.roster_stats()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with owned as (
    select pc.player_id, pc.card_id, pc.ascension, c.rarity::text as rarity, s.cp_mod, s.type,
           card_power(c.rarity::text, pc.ascension, s.cp_mod) as power
    from player_cards pc
    join cards c on c.id = pc.card_id
    join subjects s on s.id = c.subject_id
    where pc.quantity >= 1
  ), agg as (
    select coalesce(sum(power), 0)::bigint as total_power,
           count(*)::int as owned_cards,
           count(distinct player_id)::int as owners
    from owned
  )
  select jsonb_build_object(
    'players',        (select count(*) from players),
    'owners',         a.owners,
    'owned_cards',    a.owned_cards,
    'total_power',    a.total_power,
    'deployable_power', deployable_power(),
    'avg_power_owner', case when a.owners > 0 then round(a.total_power::numeric / a.owners, 1) else 0 end,
    'boss_hp', roster_boss_hp(deployable_power()),   -- the estimate of balance boss_hp_estimate (not the real boss HP)
    'by_rarity',   (select jsonb_object_agg(rarity, cnt) from (select rarity, count(*) cnt from owned group by rarity) r),
    'by_ascension',(select jsonb_object_agg(ascension::text, cnt) from (select ascension, count(*) cnt from owned group by ascension) x)
  ) from agg a;
$function$;
-- @grants public.roster_stats()
grant execute on function public.roster_stats() to postgres;
grant execute on function public.roster_stats() to service_role;
