-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.season_number(text)
-- md5: d182525efb2ce5c8367539a5c32edb6d   (md5(replace(pg_get_functiondef('public.season_number(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.season_number(p_season text)
 RETURNS integer
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select substring(coalesce(nullif(p_season, ''), 'Season 1') from '^Season ([0-9]+)$')::int;
$function$;
-- @grants public.season_number(text)
grant execute on function public.season_number(text) to postgres;
grant execute on function public.season_number(text) to service_role;
