-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.settings_log_write()
-- md5: 9ddb55e6c54d5c4ae38f6d5b2f2c4856   (md5(replace(pg_get_functiondef('public.settings_log_write()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.settings_log_write()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if tg_op = 'DELETE' then
    insert into settings_log (key, op, old_value, new_value, changed_by) values (old.key, 'delete', old.value, null, balance_who());
    return old;
  end if;
  if tg_op = 'UPDATE' and old.value = new.value and old.key = new.key then return new; end if; -- only updated_at: no row
  insert into settings_log (key, op, old_value, new_value, changed_by)
    values (new.key, lower(tg_op), case when tg_op = 'UPDATE' then old.value end, new.value, balance_who());
  return new;
end $function$;
-- @grants public.settings_log_write()
grant execute on function public.settings_log_write() to postgres;
grant execute on function public.settings_log_write() to service_role;
