-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.shop_pick_stock(date)
-- md5: 589f407a4c0961c9ccfdbcc7bc6df5c9   (md5(replace(pg_get_functiondef('public.shop_pick_stock(date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.shop_pick_stock(p_day date)
 RETURNS integer
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare cfg jsonb := shard_cfg(); v_cool int := coalesce((cfg->>'cooldown_days')::int, 7);
  r record; v_slot int := 0; v_n int;
begin
  perform pg_advisory_xact_lock(hashtext('shop_pick_stock'), (p_day - date '2000-01-01'));
  if exists (select 1 from shop_stock where day = p_day) then
    return (select count(*) from shop_stock where day = p_day);
  end if;
  for r in select k as rarity, (cfg->'stock'->>k)::int as n
             from unnest(array['normal', 'illustrated_rare', 'secret_rare']) k loop
    v_n := coalesce(r.n, 0);
    if v_n <= 0 then continue; end if;
    insert into shop_stock (day, slot, card_id, rarity, price)
    select p_day, v_slot + row_number() over (), c.id, r.rarity, (cfg->'prices'->>r.rarity)::int
      from (select c.id from draw_pool c
             where c.rarity::text = r.rarity
               and c.rarity::text not in ('gold', 'full_art', 'event', 'promo')
               and not exists (select 1 from shop_stock s where s.card_id = c.id
                                and s.day > p_day - v_cool and s.day < p_day)
             order by random() limit v_n) c;
    get diagnostics v_n = row_count;
    v_slot := v_slot + v_n;
  end loop;
  return v_slot;
end $function$;
-- @grants public.shop_pick_stock(date)
grant execute on function public.shop_pick_stock(date) to postgres;
grant execute on function public.shop_pick_stock(date) to service_role;
