-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.shop_day()
-- md5: be6e3e711f47dfa599b85aab8261cf41   (md5(replace(pg_get_functiondef('public.shop_day()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.shop_day()
 RETURNS date
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select game_day();
$function$;
-- @grants public.shop_day()
grant execute on function public.shop_day() to postgres;
grant execute on function public.shop_day() to service_role;
