-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.spend_stat_points(text, bigint, jsonb)
-- md5: 37f6cdc603e05ba871f5d9f1dadb80a6   (md5(replace(pg_get_functiondef('public.spend_stat_points(text, bigint, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.spend_stat_points(p_player text, p_card bigint, p_add jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v_asc int; v_pts jsonb; v_rar text; v_mod numeric; v_new jsonb; k text; v jsonb; v_n int; v_total int; v_cap int;
begin
  if not coalesce((stat_cfg()->>'enabled')::boolean, false) then
    return jsonb_build_object('ok', false, 'error', 'disabled'); end if;
  if p_add is null or jsonb_typeof(p_add) <> 'object' or p_add = '{}'::jsonb then
    return jsonb_build_object('ok', false, 'error', 'bad_request'); end if;
  select pc.ascension, pc.stat_points, c.rarity::text, s.cp_mod into v_asc, v_pts, v_rar, v_mod
    from player_cards pc join cards c on c.id = pc.card_id left join subjects s on s.id = c.subject_id
    where pc.player_id = p_player and pc.card_id = p_card and pc.quantity > 0
    for update of pc;
  if not found then return jsonb_build_object('ok', false, 'error', 'not_owned'); end if;
  v_new := coalesce(v_pts, '{}'::jsonb);
  for k, v in select * from jsonb_each(p_add) loop
    if k not in ('attack', 'vitality', 'precision', 'potency', 'haste') then
      return jsonb_build_object('ok', false, 'error', 'bad_stat', 'stat', k); end if;
    if jsonb_typeof(v) <> 'number' or (v #>> '{}') !~ '^[0-9]{1,2}$' then
      return jsonb_build_object('ok', false, 'error', 'bad_amount'); end if;
    v_n := (v #>> '{}')::int;
    if v_n > 0 then v_new := v_new || jsonb_build_object(k, stat_pt(v_new, k) + v_n); end if;
  end loop;
  v_total := stat_pt(v_new, 'attack') + stat_pt(v_new, 'vitality') + stat_pt(v_new, 'precision')
           + stat_pt(v_new, 'potency') + stat_pt(v_new, 'haste');
  v_cap := coalesce((stat_cfg()->>'per_star')::int, 3) * coalesce(v_asc, 0);
  if v_total > v_cap then
    return jsonb_build_object('ok', false, 'error', 'not_enough',
      'free', (card_combat(v_rar, v_asc, v_mod, v_pts)->>'free')::int); end if;
  update player_cards set stat_points = v_new where player_id = p_player and card_id = p_card;
  return jsonb_build_object('ok', true, 'points', v_new, 'stats', card_combat(v_rar, v_asc, v_mod, v_new));
end $function$;
-- @grants public.spend_stat_points(text, bigint, jsonb)
grant execute on function public.spend_stat_points(text, bigint, jsonb) to postgres;
grant execute on function public.spend_stat_points(text, bigint, jsonb) to service_role;
