-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.stat_pt(jsonb, text)
-- md5: 521ff10a291b32e121412cc192eef43d   (md5(replace(pg_get_functiondef('public.stat_pt(jsonb, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.stat_pt(p_pts jsonb, p_key text)
 RETURNS integer
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select greatest(0, least(balance_num('stat_points', 'max_per_stat')::int, coalesce(case when jsonb_typeof(p_pts->p_key) = 'number'
    then floor((p_pts->>p_key)::numeric)::int end, 0)));
$function$;
-- @grants public.stat_pt(jsonb, text)
grant execute on function public.stat_pt(jsonb, text) to postgres;
grant execute on function public.stat_pt(jsonb, text) to service_role;
