-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.streak_shield_waiting(text, date)
-- md5: 161f533dcd3765763d1f023f90940d35   (md5(replace(pg_get_functiondef('public.streak_shield_waiting(text, date)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.streak_shield_waiting(p_player text, p_day date)
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select not exists (select 1 from daily_claims where player_id = p_player and task = 'checkin' and day in (p_day, p_day - 1))
     and not exists (select 1 from player_effects where player_id = p_player and primitive = 'streak_shield'
                       and options->>'shield_day' = to_char(p_day - 1, 'YYYY-MM-DD'))
     and exists (select 1 from daily_claims where player_id = p_player and task = 'checkin' and day = p_day - 2)
     and exists (select 1 from player_effects where player_id = p_player and primitive = 'streak_shield'
                   and consumed_at is null and starts_at <= now() and (expires_at is null or expires_at > now()));
$function$;
-- @grants public.streak_shield_waiting(text, date)
grant execute on function public.streak_shield_waiting(text, date) to postgres;
grant execute on function public.streak_shield_waiting(text, date) to service_role;
