-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.subjects_flatten_tags()
-- md5: e0d25349f27786b066b05418eb5bcca9   (md5(replace(pg_get_functiondef('public.subjects_flatten_tags()'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.subjects_flatten_tags()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  v text[] := '{}';
  facet text;
  val jsonb;
  item jsonb;
  prefix text;
begin
  for facet, val in select key, value from jsonb_each(coalesce(new.tags, '{}'::jsonb)) loop
    prefix := case facet when 'traits' then 'trait' else facet end;
    if jsonb_typeof(val) = 'array' then
      for item in select value from jsonb_array_elements(val) loop
        if nullif(trim(item #>> '{}'), '') is not null then
          v := v || (prefix || ':' || lower(trim(item #>> '{}')));
        end if;
      end loop;
    elsif jsonb_typeof(val) = 'string' then
      if nullif(trim(val #>> '{}'), '') is not null then
        v := v || (prefix || ':' || lower(trim(val #>> '{}')));
      end if;
    end if;
  end loop;
  new.tag_slugs := v;
  return new;
end $function$;
-- @grants public.subjects_flatten_tags()
grant execute on function public.subjects_flatten_tags() to postgres;
grant execute on function public.subjects_flatten_tags() to service_role;
