-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.submit_report(text, text, text, jsonb)
-- md5: 255f581636053642180ccf7dc08863dc   (md5(replace(pg_get_functiondef('public.submit_report(text, text, text, jsonb)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.submit_report(p_player text, p_kind text, p_body text, p_context jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare
  lim int := coalesce((select (value->>'per_day')::int from settings where key = 'reports'), 3);
  body text := btrim(coalesce(p_body, ''));
  used int;
  new_id bigint;
begin
  if p_kind is null or p_kind not in ('bug', 'feedback', 'idea') then return jsonb_build_object('ok', false, 'error', 'kind'); end if;
  if char_length(body) < 5 then return jsonb_build_object('ok', false, 'error', 'short'); end if;
  if char_length(body) > 1500 then return jsonb_build_object('ok', false, 'error', 'long'); end if;
  if lim <= 0 then return jsonb_build_object('ok', false, 'error', 'off'); end if;
  if not exists (select 1 from players where id = p_player) then return jsonb_build_object('ok', false, 'error', 'player'); end if;
  -- One member at a time, so two fast taps cannot both pass the limit.
  perform pg_advisory_xact_lock(hashtext('player_reports:' || p_player));
  select count(*) into used from player_reports
   where player_id = p_player
     and (created_at at time zone 'America/Denver')::date = (now() at time zone 'America/Denver')::date;
  if used >= lim then return jsonb_build_object('ok', false, 'error', 'limit', 'limit', lim); end if;
  insert into player_reports (player_id, kind, body, context)
  values (p_player, p_kind, body, coalesce(p_context, '{}'::jsonb))
  returning id into new_id;
  return jsonb_build_object('ok', true, 'id', new_id, 'left', lim - used - 1);
end $function$;
-- @grants public.submit_report(text, text, text, jsonb)
grant execute on function public.submit_report(text, text, text, jsonb) to postgres;
grant execute on function public.submit_report(text, text, text, jsonb) to service_role;
