-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.top_collection_power(integer)
-- md5: 529a2cacae1407a63e5e304960e81f8c   (md5(replace(pg_get_functiondef('public.top_collection_power(integer)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.top_collection_power(p_limit integer DEFAULT 20)
 RETURNS TABLE(player_id text, username text, power bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  with subj_totals as (select subject_id, count(*) tv from cards group by subject_id),
  ps as (
    select pc.player_id, c.subject_id,
           sum(card_power(c.rarity::text, pc.ascension, s.cp_mod)) base_cp,
           count(*) ov
    from player_cards pc
    join cards c    on c.id = pc.card_id
    join subjects s on s.id = c.subject_id
    where pc.quantity >= 1
    group by pc.player_id, c.subject_id
  ),
  totals as (
    select ps.player_id,
           sum(case when ps.ov = st.tv then round(ps.base_cp * (balance_get('set_bonus') #>> '{}')::numeric) else ps.base_cp end)::bigint cp
    from ps join subj_totals st on st.subject_id = ps.subject_id
    group by ps.player_id
  )
  select t.player_id, p.username, t.cp
  from totals t join players p on p.id = t.player_id
  order by t.cp desc
  limit greatest(1, least(100, coalesce(p_limit, 20)));
$function$;
-- @grants public.top_collection_power(integer)
grant execute on function public.top_collection_power(integer) to postgres;
grant execute on function public.top_collection_power(integer) to service_role;
