-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.unlist_for_trade(text, bigint)
-- md5: 4ce3bcb77b10e5dbef245cd877932873   (md5(replace(pg_get_functiondef('public.unlist_for_trade(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.unlist_for_trade(p_player text, p_listing bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  update trade_listings set status = 'closed', closed_at = now() where id = p_listing and player_id = p_player and status = 'open';
  if not found then return jsonb_build_object('ok', false, 'error', 'not_found'); end if;
  update trade_offers set status = 'declined', resolved_at = now() where listing_id = p_listing and status = 'pending';
  return jsonb_build_object('ok', true);
end $function$;
-- @grants public.unlist_for_trade(text, bigint)
grant execute on function public.unlist_for_trade(text, bigint) to postgres;
grant execute on function public.unlist_for_trade(text, bigint) to service_role;
