-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.use_effect_charge(text, text)
-- md5: ccb1dc0ea522cbd11107bf1e2842d112   (md5(replace(pg_get_functiondef('public.use_effect_charge(text, text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.use_effect_charge(p_player text, p_primitive text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
declare e player_effects; left_n int;
begin
  select * into e from player_effects
   where player_id = p_player and primitive = p_primitive and consumed_at is null
     and starts_at <= now() and (expires_at is null or expires_at > now())
   order by created_at limit 1 for update skip locked;
  if not found then return null; end if;
  left_n := greatest(1, coalesce((e.options->>'uses')::int, 1)) - 1;
  if left_n <= 0 then update player_effects set consumed_at = now() where id = e.id;
  else update player_effects set options = options || jsonb_build_object('uses', left_n) where id = e.id; end if;
  return jsonb_build_object('amount', coalesce(e.amount, 0), 'options', e.options);
end $function$;
-- @grants public.use_effect_charge(text, text)
grant execute on function public.use_effect_charge(text, text) to postgres;
grant execute on function public.use_effect_charge(text, text) to service_role;
