-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.weekly_boss_tick(text)
-- md5: dd6116ecf38a8eb84f4de0ee359aae05   (md5(replace(pg_get_functiondef('public.weekly_boss_tick(text)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.weekly_boss_tick(p_kind text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  if not hunt_mt_slot(p_kind, now()) then return jsonb_build_object('ok', true, 'note', 'not_this_hour'); end if;
  if p_kind = 'spawn' then
    if exists (select 1 from hunts where opens_at > now() - interval '6 hours') then
      return jsonb_build_object('ok', true, 'note', 'already_spawned'); end if;
    return spawn_weekly_boss();
  elsif p_kind = 'nudge' then return nudge_hunt();
  elsif p_kind = 'close' then return close_weekly_boss();
  end if;
  return jsonb_build_object('ok', false, 'error', 'bad_kind');
end $function$;
-- @grants public.weekly_boss_tick(text)
grant execute on function public.weekly_boss_tick(text) to postgres;
grant execute on function public.weekly_boss_tick(text) to service_role;
