-- Generated by card-studio/scripts/gen-schema-snapshot.mjs from the database catalog. Do not edit by hand.

-- @function public.withdraw_bid(text, bigint)
-- md5: 6f2c61c92e8cd7400c26bd8d3426fa7b   (md5(replace(pg_get_functiondef('public.withdraw_bid(text, bigint)'::regprocedure), chr(13), '')))
-- owner: postgres
CREATE OR REPLACE FUNCTION public.withdraw_bid(p_bidder text, p_auction bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  update auction_bids set status = 'withdrawn', updated_at = now() where auction_id = p_auction and bidder_id = p_bidder and status = 'open';
  if not found then return jsonb_build_object('ok', false, 'error', 'no_bid'); end if;
  update auctions set notice_dirty = true where id = p_auction;
  return jsonb_build_object('ok', true);
end $function$;
-- @grants public.withdraw_bid(text, bigint)
grant execute on function public.withdraw_bid(text, bigint) to postgres;
grant execute on function public.withdraw_bid(text, bigint) to service_role;
